In [1]:
# 기본
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 경고 뜨지 않게 설정
import warnings
warnings.filterwarnings('ignore')

In [2]:
# 그래프 설정
sns.set()

plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14

# 데이터 전처리 알고리즘
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# 학습용과 검증용으로 나누는 함수
from sklearn.model_selection import train_test_split


# 차원 축소
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

# 학습 모델 저장을 위한 라이브러리
import pickle

In [3]:
# 데이터를 읽어온다.
df = pd.read_parquet('Seleted(C_D_NotCD)_delecteE_all_train.parquet')
df

,기준년월,ID,Group,_1순위카드이용금액,이용금액_R3M_신용체크,이용금액_R3M_신용,카드이용한도금액_B1M,카드이용한도금액_B2M,카드이용한도금액,CA한도금액,...,이용금액_오프라인_R3M,_2순위쇼핑업종_이용금액,_3순위업종_이용금액,이용금액_오프라인_B0M,_2순위업종_이용금액,_1순위업종_이용금액,_3순위쇼핑업종_이용금액,청구금액_R6M,청구금액_R3M,청구금액_B0
0,201807,TRAIN_000000,D,3681,196,196,20805,19723,19354,7270,...,4131,0,672,4043,1408,1928,0,88693,46588,12226
1,201807,TRAIN_000002,C,24493,23988,23988,78730,77975,88193,35207,...,12250,1038,1362,4524,1539,16924,924,165221,85931,21866
2,201807,TRAIN_000003,D,5933,3904,3904,20523,19226,19062,6531,...,10408,487,774,3975,2284,2405,0,127371,61518,16356
3,201807,TRAIN_000008,C,68078,124967,121279,199966,208224,199862,62007,...,59760,2590,6245,16045,12427,88663,2162,94241,62715,20512
4,201807,TRAIN_000010,D,18796,21001,21001,100037,100056,100017,31378,...,7066,0,0,2437,4751,8886,0,35723,30449,22512
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
477943,201812,TRAIN_399979,D,27337,31187,31187,76798,84977,88823,26268,...,32849,1006,2275,10581,2670,9379,925,74153,41812,11817
477944,201812,TRAIN_399987,C,35751,42492,42492,37302,37740,42192,10026,...,35760,1719,2651,11488,3673,12882,1619,132623,68356,17859
477945,201812,TRAIN_399993,C,27792,72348,72348,60057,61134,53999,22513,...,37672,1789,4954,12819,10561,11351,1183,72474,34890,10810
477946,201812,TRAIN_399996,D,26357,27636,27636,78997,78140,84217,31159,...,25205,714,1547,4676,1810,5608,346,99849,37515,14402
477947,201812,TRAIN_399997,C,17171,23187,23187,61315,63374,52612,19429,...,13267,400,2302,4516,2315,3634,305,41073,22274,5731

In [4]:
print(df.columns)

Index(['기준년월', 'ID', 'Group', '_1순위카드이용금액', '이용금액_R3M_신용체크', '이용금액_R3M_신용',
       '카드이용한도금액_B1M', '카드이용한도금액_B2M', '카드이용한도금액', 'CA한도금액', '이용금액_일시불_R12M',
       '이용금액_일시불_B0M', '이용금액_일시불_R3M', '이용금액_일시불_R6M', '최대이용금액_일시불_R12M',
       '쇼핑_도소매_이용금액', '이용금액_오프라인_R6M', '이용금액_오프라인_R3M', '_2순위쇼핑업종_이용금액',
       '_3순위업종_이용금액', '이용금액_오프라인_B0M', '_2순위업종_이용금액', '_1순위업종_이용금액',
       '_3순위쇼핑업종_이용금액', '청구금액_R6M', '청구금액_R3M', '청구금액_B0'],
      dtype='object')

In [5]:
# pca 사용
# n_components : 축소될 결과의 컬럼 개수
from sklearn.decomposition import PCA
pca = PCA(n_components=20)
# 결과 데이터를 제거한다.
X = df.drop(['기준년월', 'ID', 'Group'], axis=1)
# 학습한다.
pca.fit(X)
# 데이터를 변환한다.
r1 = pca.transform(X)
r1

array([[-1.50783968e+05, -5.60820209e+04,  5.10379417e+04, ...,
         5.11718859e+02, -1.12275637e+03,  1.23505008e+02],
       [-2.93933800e+04,  9.93840443e+03,  1.15081083e+05, ...,
        -1.42239733e+03,  6.35862388e+02,  6.44018418e+02],
       [-1.42353566e+05, -6.41542237e+04,  9.32211994e+04, ...,
         2.96830258e+02, -6.53930605e+02, -1.27836243e+02],
       ...,
       [ 4.74823897e+04, -4.82150213e+04, -4.69321951e+04, ...,
        -6.80865443e+02,  3.70019957e+02, -7.19823786e+02],
       [ 2.51633407e+04, -5.83695451e+01, -2.92088664e+03, ...,
        -2.80833738e+03,  4.66888353e+02,  3.07112222e+02],
       [-1.02725847e+05,  5.07964294e+03, -9.92052264e+03, ...,
        -8.07619842e+02,  5.87294830e+02,  8.47528691e+02]])

In [6]:
# 결과 데이터를 데이터프레임으로 변환
pca_df = pd.DataFrame(r1, columns=[f'p{i+1}' for i in range(r1.shape[1])])

# Segment 컬럼을 원본 df에서 가져와서 붙이기
pca_df['Group'] = df['Group'].values

# 결과 확인
pca_df

,p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,...,p12,p13,p14,p15,p16,p17,p18,p19,p20,Group
0,-150783.968438,-56082.020946,51037.941736,-27832.077192,16764.902567,-6722.901448,8017.228716,-1589.899745,-1903.356424,-619.245196,...,258.396459,-2619.413945,695.702007,-2118.462504,-1639.881651,920.069726,511.718859,-1122.756368,123.505008,D
1,-29393.379986,9938.404430,115081.083211,-20135.707035,-5857.585601,-10019.036113,4556.178547,2057.356990,3765.857653,7995.277636,...,-1938.234321,7891.671047,-1951.968365,1409.617899,-5706.378995,-1780.678516,-1422.397326,635.862388,644.018418,C
2,-142353.565715,-64154.223712,93221.199407,-23492.918679,20369.557438,3236.070104,15395.461901,-5636.916532,2905.972770,1382.190089,...,3687.824183,-3773.212836,1017.672162,-261.330256,-2476.748714,2372.291183,296.830258,-653.930605,-127.836243,D
3,340845.132838,117915.936314,-93128.551494,19111.767843,-46991.887054,-4445.300905,13447.551193,-16563.630643,46086.915040,-5327.911980,...,-4381.567365,4355.323364,-5701.039627,-12319.162335,-1307.383944,-2781.299443,-930.195183,-1520.976434,-729.562992,C
4,-97905.472256,78320.279698,6494.134578,-4516.307322,-11954.702338,-9874.741005,13430.785456,290.018531,3971.263032,-258.815143,...,5163.766164,528.753605,476.545295,7168.964576,10412.741513,356.362678,-2980.915622,808.135107,-1931.182976,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
477943,-29150.170034,22181.385835,9281.710609,17381.517971,12538.906825,-8956.998938,3810.385934,-4792.506364,796.826643,4882.946518,...,-177.804772,-195.079623,-6904.505576,3599.247784,-1534.464112,-832.748652,2307.587176,-934.073365,202.979713,D
477944,-17513.333798,-70697.580000,53946.608206,18710.117945,4641.402693,-8406.709125,179.866941,2628.154881,-20.116104,3924.466640,...,-948.245824,-5216.903256,-1575.192315,5945.342511,-4745.918684,-1407.972710,1362.822015,-1292.967815,403.869160,C
477945,47482.389701,-48215.021320,-46932.195110,18507.641154,-23785.809085,-6300.144546,-17444.229352,883.859491,-14881.342817,-7770.090738,...,5237.278551,1587.809717,954.730644,-7979.744714,170.807025,3883.683243,-680.865443,370.019957,-719.823786,C
477946,25163.340661,-58.369545,-2920.886645,-25589.429101,24855.350199,1761.901868,-4908.108591,17155.243996,-3882.382805,5421.548716,...,-429.107326,5225.673374,-678.111723,650.241867,2302.705505,-4382.323726,-2808.337380,466.888353,307.112222,D
477947,-102725.847290,5079.642936,-9920.522636,699.156205,3391.855767,-2000.808652,2220.694673,-93.875303,49.187195,-8073.610186,...,5401.038531,-83.059338,622.965970,3978.437114,-2164.901022,-68.383948,-807.619842,587.294830,847.528691,C

In [7]:
pca_df['기준년월']=df['기준년월']
pca_df['ID']=df['ID']
pca_df

,p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,...,p14,p15,p16,p17,p18,p19,p20,Group,기준년월,ID
0,-150783.968438,-56082.020946,51037.941736,-27832.077192,16764.902567,-6722.901448,8017.228716,-1589.899745,-1903.356424,-619.245196,...,695.702007,-2118.462504,-1639.881651,920.069726,511.718859,-1122.756368,123.505008,D,201807,TRAIN_000000
1,-29393.379986,9938.404430,115081.083211,-20135.707035,-5857.585601,-10019.036113,4556.178547,2057.356990,3765.857653,7995.277636,...,-1951.968365,1409.617899,-5706.378995,-1780.678516,-1422.397326,635.862388,644.018418,C,201807,TRAIN_000002
2,-142353.565715,-64154.223712,93221.199407,-23492.918679,20369.557438,3236.070104,15395.461901,-5636.916532,2905.972770,1382.190089,...,1017.672162,-261.330256,-2476.748714,2372.291183,296.830258,-653.930605,-127.836243,D,201807,TRAIN_000003
3,340845.132838,117915.936314,-93128.551494,19111.767843,-46991.887054,-4445.300905,13447.551193,-16563.630643,46086.915040,-5327.911980,...,-5701.039627,-12319.162335,-1307.383944,-2781.299443,-930.195183,-1520.976434,-729.562992,C,201807,TRAIN_000008
4,-97905.472256,78320.279698,6494.134578,-4516.307322,-11954.702338,-9874.741005,13430.785456,290.018531,3971.263032,-258.815143,...,476.545295,7168.964576,10412.741513,356.362678,-2980.915622,808.135107,-1931.182976,D,201807,TRAIN_000010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
477943,-29150.170034,22181.385835,9281.710609,17381.517971,12538.906825,-8956.998938,3810.385934,-4792.506364,796.826643,4882.946518,...,-6904.505576,3599.247784,-1534.464112,-832.748652,2307.587176,-934.073365,202.979713,D,201812,TRAIN_399979
477944,-17513.333798,-70697.580000,53946.608206,18710.117945,4641.402693,-8406.709125,179.866941,2628.154881,-20.116104,3924.466640,...,-1575.192315,5945.342511,-4745.918684,-1407.972710,1362.822015,-1292.967815,403.869160,C,201812,TRAIN_399987
477945,47482.389701,-48215.021320,-46932.195110,18507.641154,-23785.809085,-6300.144546,-17444.229352,883.859491,-14881.342817,-7770.090738,...,954.730644,-7979.744714,170.807025,3883.683243,-680.865443,370.019957,-719.823786,C,201812,TRAIN_399993
477946,25163.340661,-58.369545,-2920.886645,-25589.429101,24855.350199,1761.901868,-4908.108591,17155.243996,-3882.382805,5421.548716,...,-678.111723,650.241867,2302.705505,-4382.323726,-2808.337380,466.888353,307.112222,D,201812,TRAIN_399996
477947,-102725.847290,5079.642936,-9920.522636,699.156205,3391.855767,-2000.808652,2220.694673,-93.875303,49.187195,-8073.610186,...,622.965970,3978.437114,-2164.901022,-68.383948,-807.619842,587.294830,847.528691,C,201812,TRAIN_399997

### train 저장

In [8]:
pca_df.to_csv('(C_D_NotCD)_pca(20)_train_final.csv', index=False, encoding='utf-8-sig')

## Test

In [13]:
df_test = pd.read_parquet('Seleted(C_D_NotCD)_all_test.parquet')

In [9]:
df1 = pd.read_csv('data/test_model3_notE.csv')

In [10]:
filtered_ids = df1[['ID', '기준년월']]

In [14]:
# filtered_ids가 [(ID1, 기준년월1), (ID2, 기준년월2), ...] 형태라고 가정
filtered_df = pd.DataFrame(filtered_ids, columns=['ID', '기준년월'])

# df_test와 ID & 기준년월 기준으로 inner merge
final_df_test = df_test.merge(filtered_df, on=['ID', '기준년월'], how='inner')

In [15]:
final_df_test

,기준년월,ID,청구금액_R6M,청구금액_R3M,청구금액_B0,이용금액_일시불_R12M,_1순위카드이용금액,이용금액_R3M_신용체크,이용금액_일시불_B0M,이용금액_일시불_R3M,...,_2순위쇼핑업종_이용금액,_3순위업종_이용금액,카드이용한도금액_B1M,카드이용한도금액_B2M,카드이용한도금액,이용금액_오프라인_B0M,_2순위업종_이용금액,CA한도금액,_1순위업종_이용금액,_3순위쇼핑업종_이용금액
0,201807,TEST_00002,71867,50508,13223,73003,27071,40758,8547,25225,...,1178,2680,100053,100056,100045,11298,7271,30505,7594,1094
1,201807,TEST_00010,12797,6847,0,29326,7544,45764,3862,7267,...,0,0,30007,30003,50274,0,0,25451,3144,0
2,201807,TEST_00012,63042,33803,7283,86805,24425,37849,7940,26365,...,491,2427,65608,60334,48071,10864,4200,18629,5749,307
3,201807,TEST_00016,77903,41328,12194,207417,42636,51440,17139,49967,...,1645,2222,21313,21749,19300,13105,4815,10392,30003,1489
4,201807,TEST_00032,11525,4259,769,21910,3885,54632,1172,3875,...,0,0,65139,62407,49727,1006,0,18118,42,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96493,201812,TEST_99957,66775,28638,14349,136892,38644,61148,12865,35578,...,1117,2517,50015,50010,52373,11170,3498,19032,20140,1069
96494,201812,TEST_99961,58282,26095,7195,117578,25961,30318,8266,30291,...,729,5474,36138,37379,45661,10786,6852,18298,10615,618
96495,201812,TEST_99982,129230,65023,11710,447150,70955,94440,21254,64786,...,1072,4149,197044,197112,199981,15527,6088,58290,9283,387
96496,201812,TEST_99994,150417,98428,28423,33505,29020,31697,3677,10608,...,2715,0,78880,79084,86186,9996,1343,26945,23262,242
96497,201812,TEST_99998,108420,48141,21273,423882,63592,173263,22617,66757,...,2208,4612,37999,37139,42610,15388,16296,17362,64203,1965

In [16]:
# 불필요한 컬럼 제거
X_test = final_df_test.drop(['기준년월', 'ID'], axis=1)
X_test

,청구금액_R6M,청구금액_R3M,청구금액_B0,이용금액_일시불_R12M,_1순위카드이용금액,이용금액_R3M_신용체크,이용금액_일시불_B0M,이용금액_일시불_R3M,이용금액_일시불_R6M,이용금액_R3M_신용,...,_2순위쇼핑업종_이용금액,_3순위업종_이용금액,카드이용한도금액_B1M,카드이용한도금액_B2M,카드이용한도금액,이용금액_오프라인_B0M,_2순위업종_이용금액,CA한도금액,_1순위업종_이용금액,_3순위쇼핑업종_이용금액
0,71867,50508,13223,73003,27071,40758,8547,25225,48483,40758,...,1178,2680,100053,100056,100045,11298,7271,30505,7594,1094
1,12797,6847,0,29326,7544,45764,3862,7267,19540,7024,...,0,0,30007,30003,50274,0,0,25451,3144,0
2,63042,33803,7283,86805,24425,37849,7940,26365,46059,37849,...,491,2427,65608,60334,48071,10864,4200,18629,5749,307
3,77903,41328,12194,207417,42636,51440,17139,49967,98761,51440,...,1645,2222,21313,21749,19300,13105,4815,10392,30003,1489
4,11525,4259,769,21910,3885,54632,1172,3875,12229,4259,...,0,0,65139,62407,49727,1006,0,18118,42,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96493,66775,28638,14349,136892,38644,61148,12865,35578,74022,59950,...,1117,2517,50015,50010,52373,11170,3498,19032,20140,1069
96494,58282,26095,7195,117578,25961,30318,8266,30291,67949,30318,...,729,5474,36138,37379,45661,10786,6852,18298,10615,618
96495,129230,65023,11710,447150,70955,94440,21254,64786,129251,94440,...,1072,4149,197044,197112,199981,15527,6088,58290,9283,387
96496,150417,98428,28423,33505,29020,31697,3677,10608,20070,31697,...,2715,0,78880,79084,86186,9996,1343,26945,23262,242
96497,108420,48141,21273,423882,63592,173263,22617,66757,133431,113786,...,2208,4612,37999,37139,42610,15388,16296,17362,64203,1965

In [19]:
# train 데이터에서 feature 컬럼 리스트 확보
feature_columns = X.columns.tolist()

# test 데이터에서 동일한 컬럼, 동일한 순서로 선택
X_test = final_df_test[feature_columns]

In [20]:
X_test

,_1순위카드이용금액,이용금액_R3M_신용체크,이용금액_R3M_신용,카드이용한도금액_B1M,카드이용한도금액_B2M,카드이용한도금액,CA한도금액,이용금액_일시불_R12M,이용금액_일시불_B0M,이용금액_일시불_R3M,...,이용금액_오프라인_R3M,_2순위쇼핑업종_이용금액,_3순위업종_이용금액,이용금액_오프라인_B0M,_2순위업종_이용금액,_1순위업종_이용금액,_3순위쇼핑업종_이용금액,청구금액_R6M,청구금액_R3M,청구금액_B0
0,27071,40758,40758,100053,100056,100045,30505,73003,8547,25225,...,41402,1178,2680,11298,7271,7594,1094,71867,50508,13223
1,7544,45764,7024,30007,30003,50274,25451,29326,3862,7267,...,0,0,0,0,0,3144,0,12797,6847,0
2,24425,37849,37849,65608,60334,48071,18629,86805,7940,26365,...,29122,491,2427,10864,4200,5749,307,63042,33803,7283
3,42636,51440,51440,21313,21749,19300,10392,207417,17139,49967,...,38194,1645,2222,13105,4815,30003,1489,77903,41328,12194
4,3885,54632,4259,65139,62407,49727,18118,21910,1172,3875,...,1513,0,0,1006,0,42,0,11525,4259,769
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96493,38644,61148,59950,50015,50010,52373,19032,136892,12865,35578,...,32838,1117,2517,11170,3498,20140,1069,66775,28638,14349
96494,25961,30318,30318,36138,37379,45661,18298,117578,8266,30291,...,32618,729,5474,10786,6852,10615,618,58282,26095,7195
96495,70955,94440,94440,197044,197112,199981,58290,447150,21254,64786,...,47571,1072,4149,15527,6088,9283,387,129230,65023,11710
96496,29020,31697,31697,78880,79084,86186,26945,33505,3677,10608,...,20428,2715,0,9996,1343,23262,242,150417,98428,28423
96497,63592,173263,113786,37999,37139,42610,17362,423882,22617,66757,...,44309,2208,4612,15388,16296,64203,1965,108420,48141,21273

In [22]:
# transform
X_test_pca = pca.transform(X_test)

# DataFrame 변환
pca_columns = [f'p{i+1}' for i in range(X_test_pca.shape[1])]
pca_df_test = pd.DataFrame(X_test_pca, columns=pca_columns)

# ID 붙이기
pca_df_test['ID'] = final_df_test['ID'].values

In [23]:
pca_df_test

,p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,...,p12,p13,p14,p15,p16,p17,p18,p19,p20,ID
0,-13705.067440,46467.691559,15942.555179,50207.425732,13279.118384,-10540.445197,8275.998167,597.220989,-2948.674740,-439.575976,...,1706.048258,-965.838040,-161.714809,-719.020089,-2860.625905,3313.634852,342.230181,-284.058508,-1063.562006,TEST_00002
1,-157243.879719,-13302.476700,-30608.699050,-10141.276718,-20191.567610,16734.803593,3865.040703,2766.081509,-7436.949339,15593.166090,...,-12124.200787,11666.408502,-4085.345752,752.390808,-1908.040291,-2157.231466,-2163.578964,157.956699,178.894712,TEST_00010
2,-48997.752561,-17050.828103,-8785.969908,12658.477978,976.577391,-4781.244178,-1387.027484,3497.772702,-3101.396425,-10387.737288,...,3833.353734,-924.614911,6633.882026,1840.229396,-4320.036898,2559.579926,2611.515095,1951.500122,-453.318890,TEST_00012
3,52617.221072,-117970.778109,-63093.266659,-13703.021001,-525.569384,-20709.360313,-11409.284360,16661.488453,4419.949193,-1665.345793,...,-9062.662800,1465.081008,-557.481777,-979.536980,-1589.199659,-1228.275578,1990.620854,3028.806924,-720.985493,TEST_00016
4,-150893.648894,23186.461190,-25302.261145,-980.885632,-19613.383003,27205.851461,8992.013284,-103.473319,-6977.553648,-11877.372912,...,-15599.675321,732.953370,4740.377962,648.517284,-539.828000,-1710.122138,-865.854859,-827.977316,-66.660295,TEST_00032
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96493,5534.292187,-48302.147655,-35833.803086,20868.002514,-16374.674953,-5379.702512,-11563.581200,-3282.599440,2630.263551,1120.416128,...,2287.983091,1015.485091,160.905425,5216.652475,3256.013247,-3489.050837,1456.987510,541.779349,-382.434722,TEST_99957
96494,-32783.504355,-53443.942457,-33865.260054,9599.980027,16651.123902,-15976.790692,-13476.342166,1921.854194,-4305.693411,5777.082963,...,-5417.860671,3484.478509,-2302.378322,-1166.886929,-226.575257,1158.781200,-789.949760,-2876.429032,2098.222234,TEST_99961
96495,390074.729741,96464.046501,-105134.555049,-88208.920785,-2426.837122,19983.301997,13348.602388,41972.099226,-16046.998083,4965.756830,...,9229.586083,1084.252045,-2342.334199,12283.910664,-11720.708318,-2909.645085,1386.512242,1992.611980,-131.153143,TEST_99982
96496,-46298.872570,13607.202059,118027.253642,-1223.211427,-13979.589030,-10674.375726,27371.224836,9007.675594,12317.703831,8117.270221,...,1389.377297,-382.730890,-2926.906637,3525.806139,-4855.369976,-508.454855,3470.659567,-894.316036,-765.165143,TEST_99994
96497,280723.132512,-161698.898857,-142736.969338,-43064.312408,-75343.017197,38329.113651,10618.640129,-9400.235482,12479.288455,3852.132888,...,-21484.319654,4216.558776,-182.169296,-3338.510872,4572.614387,528.180119,-1267.450181,-2988.717889,-3242.599772,TEST_99998

In [25]:
pca_df_test.to_csv('(C_D_NotCD)_pca(20)_test.csv', index=False, encoding='utf-8-sig')