In [1]:
# 기본
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 경고 뜨지 않게 설정
import warnings
warnings.filterwarnings('ignore')

# 그래프 설정
sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False

# 데이터 전처리 알고리즘
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# 학습용과 검증용으로 나누는 함수
from sklearn.model_selection import train_test_split

# 교차 검증'
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

# 평가함수
# 분류용
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

# 회귀용
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

# 모델의 최적의 하이퍼 파라미터를 찾기 위한 도구
from sklearn.model_selection import GridSearchCV

# 머신러닝 알고리즘 - 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import VotingClassifier

# 머신러닝 알고리즘 - 회귀
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from sklearn.ensemble import VotingRegressor

# 차원 축소
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

# 군집
from sklearn.cluster import KMeans
from sklearn.cluster import MeanShift
from sklearn.cluster import estimate_bandwidth

# 학습 모델 저장을 위한 라이브러리
import pickle

In [2]:
train_ab = pd.read_csv(r'train_A,B (변수선택).csv')
test_ab = pd.read_csv(r'test_A,B (변수선택).csv')

In [3]:
all_df_ab = pd.concat([train_ab, test_ab], axis=0, ignore_index=True)
all_df_ab

,ID,기준년월,방문횟수_앱_R6M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M,방문일수_PC_R6M,방문횟수_PC_R6M,이용후경과월_할부_무이자,이용후경과월_할부,이용개월수_할부_무이자_R12M,...,이용건수_할부_R3M,이용금액_할부_무이자_R6M,거주시도명,연령,Life_Stage,캠페인접촉건수_R12M,대표청구서수령지구분코드,청구서수령방법,캠페인접촉일수_R12M,할인건수_R3M
0,TRAIN_002898,201807,1회 이상,10회 이상,10회 이상,1회 이상,1회 이상,0,0,9,...,7,40359,경기,40대,자녀성장(1),5회 이상,우편,우편,5일 이상,1회 이상
1,TRAIN_005253,201807,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,0,0,9,...,5,29199,부산,50대,자녀성장(2),1회 이상,이메일,이메일,1일 이상,1회 이상
2,TRAIN_008128,201807,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1,1,9,...,5,41888,경기,40대,자녀성장(2),1회 이상,이메일,이메일,1일 이상,1회 이상
3,TRAIN_010808,201807,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1,1,4,...,1,4535,경기,40대,자녀성장(1),5회 이상,이메일,이메일,5일 이상,1회 이상
4,TRAIN_014951,201807,1회 이상,1회 이상,1회 이상,20회 이상,30회 이상,1,1,7,...,4,40012,서울,30대,자녀성장(1),1회 이상,당사페이앱+이메일,문자메세지,1일 이상,1회 이상
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
601111,TEST_99995,201812,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,12,12,0,...,0,0,경기,60대,노년생활,1회 이상,우편,우편,1일 이상,1회 이상
601112,TEST_99996,201812,10회 이상,1회 이상,1회 이상,1회 이상,1회 이상,12,12,0,...,0,0,서울,30대,자녀출산기,1회 이상,우편,우편,1일 이상,1회 이상
601113,TEST_99997,201812,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,12,12,0,...,0,0,경남,30대,자녀성장(1),1회 이상,이메일,이메일,1일 이상,1회 이상
601114,TEST_99998,201812,40회 이상,1회 이상,1회 이상,1회 이상,1회 이상,2,2,3,...,0,0,경남,30대,가족구축기,5회 이상,K톡명세서+이메일,K톡,5일 이상,1회 이상
601115,TEST_99999,201812,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,12,12,0,...,0,0,경기,30대,자녀출산기,1회 이상,우편,우편,1일 이상,1회 이상

In [4]:
all_df_ab2=all_df_ab.copy()
all_df_ab2.drop(columns=['ID', '기준년월'], inplace=True)
all_df_ab2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 601116 entries, 0 to 601115
Data columns (total 28 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   방문횟수_앱_R6M         601116 non-null  object
 1   인입횟수_ARS_R6M       601116 non-null  object
 2   이용메뉴건수_ARS_R6M     601116 non-null  object
 3   방문일수_PC_R6M        601116 non-null  object
 4   방문횟수_PC_R6M        601116 non-null  object
 5   이용후경과월_할부_무이자      601116 non-null  int64
 6   이용후경과월_할부          601116 non-null  int64
 7   이용개월수_할부_무이자_R12M  601116 non-null  int64
 8   이용개월수_할부_R12M      601116 non-null  int64
 9   카드이용한도금액_B2M       601116 non-null  int64
 10  카드이용한도금액_B1M       601116 non-null  int64
 11  카드이용한도금액           601116 non-null  int64
 12  이용개월수_할부_R6M       601116 non-null  int64
 13  CA한도금액             601116 non-null  int64
 14  이용개월수_할부_무이자_R6M   601116 non-null  int64
 15  이용개월수_할부_R3M       601116 non-null  int64
 16  이용개월수_할부_무이자_R3M   601116 non-null  int64
 17  이용건수_할부_무이자_R3M    601116 non-null  int64
 18  이용건수_할부_R3M        601116 non-null  int64
 19  이용금액_할부_무이자_R6M    601116 non-null  int64
 20  거주시도명              601116 non-null  object
 21  연령                 601116 non-null  object
 22  Life_Stage         601116 non-null  object
 23  캠페인접촉건수_R12M       601116 non-null  object
 24  대표청구서수령지구분코드       601116 non-null  object
 25  청구서수령방법            601116 non-null  object
 26  캠페인접촉일수_R12M       601116 non-null  object
 27  할인건수_R3M           601116 non-null  object
dtypes: int64(15), object(13)
memory usage: 128.4+ MB

In [5]:
all_df_ab2['방문횟수_앱_R6M'] = all_df_ab2['방문횟수_앱_R6M'].factorize()[0]
all_df_ab2['방문일수_PC_R6M'] = all_df_ab2['방문일수_PC_R6M'].factorize()[0]
all_df_ab2['인입횟수_ARS_R6M'] = all_df_ab2['인입횟수_ARS_R6M'].factorize()[0]
all_df_ab2['이용메뉴건수_ARS_R6M'] = all_df_ab2['이용메뉴건수_ARS_R6M'].factorize()[0]
all_df_ab2['방문횟수_PC_R6M'] = all_df_ab2['방문횟수_PC_R6M'].factorize()[0]
all_df_ab2['거주시도명'] = all_df_ab2['거주시도명'].factorize()[0]
all_df_ab2['연령'] = all_df_ab2['연령'].factorize()[0]
all_df_ab2['Life_Stage'] = all_df_ab2['Life_Stage'].factorize()[0]
all_df_ab2['캠페인접촉건수_R12M'] = all_df_ab2['캠페인접촉건수_R12M'].factorize()[0]
all_df_ab2['대표청구서수령지구분코드'] = all_df_ab2['대표청구서수령지구분코드'].factorize()[0]
all_df_ab2['청구서수령방법'] = all_df_ab2['청구서수령방법'].factorize()[0]
all_df_ab2['캠페인접촉일수_R12M'] = all_df_ab2['캠페인접촉일수_R12M'].factorize()[0]
all_df_ab2['할인건수_R3M'] = all_df_ab2['할인건수_R3M'].factorize()[0]
all_df_ab2

,방문횟수_앱_R6M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M,방문일수_PC_R6M,방문횟수_PC_R6M,이용후경과월_할부_무이자,이용후경과월_할부,이용개월수_할부_무이자_R12M,이용개월수_할부_R12M,카드이용한도금액_B2M,...,이용건수_할부_R3M,이용금액_할부_무이자_R6M,거주시도명,연령,Life_Stage,캠페인접촉건수_R12M,대표청구서수령지구분코드,청구서수령방법,캠페인접촉일수_R12M,할인건수_R3M
0,0,0,0,0,0,0,0,9,10,224182,...,7,40359,0,0,0,0,0,0,0,0
1,0,1,1,0,0,0,0,9,9,214877,...,5,29199,1,1,1,1,1,1,1,0
2,0,1,1,0,0,1,1,9,9,193306,...,5,41888,0,0,1,1,1,1,1,0
3,0,1,1,0,0,1,1,4,3,208477,...,1,4535,0,0,0,0,1,1,0,0
4,0,1,1,1,1,1,1,7,7,211000,...,4,40012,2,2,0,1,2,2,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
601111,0,1,1,0,0,12,12,0,0,0,...,0,0,0,4,2,1,0,0,1,0
601112,2,1,1,0,0,12,12,0,0,49990,...,0,0,2,2,3,1,0,0,1,0
601113,0,1,1,0,0,12,12,0,0,30004,...,0,0,8,2,0,1,1,1,1,0
601114,1,1,1,0,0,2,2,3,3,37139,...,0,0,8,2,6,0,3,3,0,0
601115,0,1,1,0,0,12,12,0,0,79148,...,0,0,0,2,3,1,0,0,1,0

In [6]:
drop_columns_ab=['대표청구서수령지구분코드','청구서수령방법',
                 '카드이용한도금액_B1M','카드이용한도금액',
                 '이용개월수_할부_R12M', '이용개월수_할부_R6M','이용개월수_할부_무이자_R6M', '이용개월수_할부_R3M',
                '이용개월수_할부_무이자_R3M',
                '이용후경과월_할부']
all_df_ab3=all_df_ab2.drop(columns=drop_columns_ab)

In [7]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
import statsmodels.api as sm

# vif 표를 출력한 후 vif 계수가 높다고 생각되는 컬럼들을 추가하여 계속 돌려보요요
# vif_X = train_df2.drop(['Transported'], axis=1)
# vif_X = train_df2.drop(['Transported', 'NumberInGroup'], axis=1)
vif_X = all_df_ab3.copy()

# vif를 계산하기 위해 상수항을 추가한다.
vif_X2 = sm.add_constant(vif_X)

vif_X2

,const,방문횟수_앱_R6M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M,방문일수_PC_R6M,방문횟수_PC_R6M,이용후경과월_할부_무이자,이용개월수_할부_무이자_R12M,카드이용한도금액_B2M,CA한도금액,이용건수_할부_무이자_R3M,이용건수_할부_R3M,이용금액_할부_무이자_R6M,거주시도명,연령,Life_Stage,캠페인접촉건수_R12M,캠페인접촉일수_R12M,할인건수_R3M
0,1.0,0,0,0,0,0,0,9,224182,57536,6,7,40359,0,0,0,0,0,0
1,1.0,0,1,1,0,0,0,9,214877,53971,5,5,29199,1,1,1,1,1,0
2,1.0,0,1,1,0,0,1,9,193306,53533,5,5,41888,0,0,1,1,1,0
3,1.0,0,1,1,0,0,1,4,208477,57970,1,1,4535,0,0,0,0,0,0
4,1.0,0,1,1,1,1,1,7,211000,60800,4,4,40012,2,2,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
601111,1.0,0,1,1,0,0,12,0,0,0,0,0,0,0,4,2,1,1,0
601112,1.0,2,1,1,0,0,12,0,49990,17876,0,0,0,2,2,3,1,1,0
601113,1.0,0,1,1,0,0,12,0,30004,13332,0,0,0,8,2,0,1,1,0
601114,1.0,1,1,1,0,0,2,3,37139,17362,0,0,0,8,2,6,0,0,0
601115,1.0,0,1,1,0,0,12,0,79148,30242,0,0,0,0,2,3,1,1,0

In [8]:
# vif를 계산한다.
vif = pd.DataFrame()
vif['변수'] = vif_X2.columns
vif['VIF'] = [variance_inflation_factor(vif_X2.values, i) for i in range(vif_X2.shape[1])]
vif

                   변수        VIF
0               const  75.341560
1          방문횟수_앱_R6M   1.079001
2        인입횟수_ARS_R6M   1.294594
3      이용메뉴건수_ARS_R6M   1.250189
4         방문일수_PC_R6M   4.654514
5         방문횟수_PC_R6M   4.662994
6       이용후경과월_할부_무이자   4.760100
7   이용개월수_할부_무이자_R12M   9.689534
8        카드이용한도금액_B2M   6.098888
9              CA한도금액   6.111620
10    이용건수_할부_무이자_R3M  11.798926
11        이용건수_할부_R3M   9.517844
12    이용금액_할부_무이자_R6M   3.734545
13              거주시도명   1.005786
14                 연령   1.935870
15         Life_Stage   1.946433
16       캠페인접촉건수_R12M   4.591442
17       캠페인접촉일수_R12M   4.588693
18           할인건수_R3M   1.071955

In [9]:
pd.set_option('display.max_rows', None)
vif_sorted = vif.sort_values(by='VIF', ascending=False)
display(vif_sorted)

                   변수        VIF
0               const  75.341560
10    이용건수_할부_무이자_R3M  11.798926
7   이용개월수_할부_무이자_R12M   9.689534
11        이용건수_할부_R3M   9.517844
9              CA한도금액   6.111620
8        카드이용한도금액_B2M   6.098888
6       이용후경과월_할부_무이자   4.760100
5         방문횟수_PC_R6M   4.662994
4         방문일수_PC_R6M   4.654514
16       캠페인접촉건수_R12M   4.591442
17       캠페인접촉일수_R12M   4.588693
12    이용금액_할부_무이자_R6M   3.734545
15         Life_Stage   1.946433
14                 연령   1.935870
2        인입횟수_ARS_R6M   1.294594
3      이용메뉴건수_ARS_R6M   1.250189
1          방문횟수_앱_R6M   1.079001
18           할인건수_R3M   1.071955
13              거주시도명   1.005786

### C, D, not CD

In [7]:
train_cd = pd.read_csv(r'train_C,D,notCD (변수선택)(2).csv')
test_cd = pd.read_csv(r'test_C,D,notCD (변수선택)(2).csv')

In [8]:
all_df_cd = pd.concat([train_cd, test_cd], axis=0, ignore_index=True)
all_df_cd

,ID,기준년월,_1순위카드이용금액,연령,이용금액_R3M_신용체크,이용금액_일시불_R12M,이용금액대,청구금액_R6M,청구금액_R3M,청구금액_B0
0,TRAIN_000000,201807,3681,40대,196,20667,01.100만원+,88693,46588,12226
1,TRAIN_000002,201807,24493,30대,23988,55656,01.100만원+,165221,85931,21866
2,TRAIN_000003,201807,5933,40대,3904,10753,01.100만원+,127371,61518,16356
3,TRAIN_000008,201807,68078,30대,124967,360859,01.100만원+,94241,62715,20512
4,TRAIN_000010,201807,18796,40대,21001,34884,01.100만원+,35723,30449,22512
...,...,...,...,...,...,...,...,...,...,...
1077943,TEST_99995,201812,0,60대,0,0,09.미사용,0,0,0
1077944,TEST_99996,201812,1231,30대,3110,2631,05.10만원-,2237,1256,359
1077945,TEST_99997,201812,0,30대,0,0,09.미사용,0,0,0
1077946,TEST_99998,201812,63592,30대,173263,423882,01.100만원+,108420,48141,21273
1077947,TEST_99999,201812,-574,30대,3016,-885,05.10만원-,105,56,18

In [9]:
all_df_cd2=all_df_cd.copy()
all_df_cd2.drop(columns=['ID', '기준년월'], inplace=True)
all_df_cd2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1077948 entries, 0 to 1077947
Data columns (total 8 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   _1순위카드이용금액     1077948 non-null  int64
 1   연령             1077948 non-null  object
 2   이용금액_R3M_신용체크  1077948 non-null  int64
 3   이용금액_일시불_R12M  1077948 non-null  int64
 4   이용금액대          1077948 non-null  object
 5   청구금액_R6M       1077948 non-null  int64
 6   청구금액_R3M       1077948 non-null  int64
 7   청구금액_B0        1077948 non-null  int64
dtypes: int64(6), object(2)
memory usage: 65.8+ MB

In [10]:
amount_map = {
    '01.100만원+': 100,
    '02.50만원+': 50,
    '03.30만원+': 30,
    '04.10만원+': 10,
    '05.10만원-': 5,
    '09.미사용': 0
}

# 수치형 컬럼 생성
all_df_cd2['이용금액대'] = all_df_cd['이용금액대'].map(amount_map)

In [11]:
all_df_cd2['연령'] = all_df_cd2['연령'].factorize()[0]
all_df_cd2

,_1순위카드이용금액,연령,이용금액_R3M_신용체크,이용금액_일시불_R12M,이용금액대,청구금액_R6M,청구금액_R3M,청구금액_B0
0,3681,0,196,20667,100,88693,46588,12226
1,24493,1,23988,55656,100,165221,85931,21866
2,5933,0,3904,10753,100,127371,61518,16356
3,68078,1,124967,360859,100,94241,62715,20512
4,18796,0,21001,34884,100,35723,30449,22512
...,...,...,...,...,...,...,...,...
1077943,0,3,0,0,0,0,0,0
1077944,1231,1,3110,2631,5,2237,1256,359
1077945,0,1,0,0,0,0,0,0
1077946,63592,1,173263,423882,100,108420,48141,21273
1077947,-574,1,3016,-885,5,105,56,18

In [12]:
drop_columns_cd=['청구금액_R3M','청구금액_B0']
all_df_cd3=all_df_cd2.drop(columns=drop_columns_cd)

In [13]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
import statsmodels.api as sm

# vif 표를 출력한 후 vif 계수가 높다고 생각되는 컬럼들을 추가하여 계속 돌려보요요
# vif_X = train_df2.drop(['Transported'], axis=1)
# vif_X = train_df2.drop(['Transported', 'NumberInGroup'], axis=1)
vif_X3 = all_df_cd3.copy()

# vif를 계산하기 위해 상수항을 추가한다.
vif_X4 = sm.add_constant(vif_X3)

vif_X4

         const  _1순위카드이용금액  연령  이용금액_R3M_신용체크  이용금액_일시불_R12M  이용금액대  청구금액_R6M
0          1.0        3681   0            196          20667    100     88693
1          1.0       24493   1          23988          55656    100    165221
2          1.0        5933   0           3904          10753    100    127371
3          1.0       68078   1         124967         360859    100     94241
4          1.0       18796   0          21001          34884    100     35723
...        ...         ...  ..            ...            ...    ...       ...
1077943    1.0           0   3              0              0      0         0
1077944    1.0        1231   1           3110           2631      5      2237
1077945    1.0           0   1              0              0      0         0
1077946    1.0       63592   1         173263         423882    100    108420
1077947    1.0        -574   1           3016           -885      5       105

[1077948 rows x 7 columns]

In [14]:
# vif를 계산한다.
vif2 = pd.DataFrame()
vif2['변수'] = vif_X4.columns
vif2['VIF'] = [variance_inflation_factor(vif_X4.values, i) for i in range(vif_X4.shape[1])]
vif2

              변수        VIF
0          const   3.849602
1     _1순위카드이용금액  10.103818
2             연령   1.022423
3  이용금액_R3M_신용체크   4.126583
4  이용금액_일시불_R12M   5.477429
5          이용금액대   3.628665
6       청구금액_R6M   2.459257

In [15]:
pd.set_option('display.max_rows', None)
vif_sorted2 = vif2.sort_values(by='VIF', ascending=False)
display(vif_sorted2)

              변수        VIF
1     _1순위카드이용금액  10.103818
4  이용금액_일시불_R12M   5.477429
3  이용금액_R3M_신용체크   4.126583
0          const   3.849602
5          이용금액대   3.628665
6       청구금액_R6M   2.459257
2             연령   1.022423

---

### 변수 추출

In [2]:
train_ab = pd.read_csv(r'train_A,B (변수선택).csv')
test_ab = pd.read_csv(r'test_A,B (변수선택).csv')

In [3]:
train_cd = pd.read_csv(r'train_C,D,notCD (변수선택)(2).csv')
test_cd = pd.read_csv(r'test_C,D,notCD (변수선택)(2).csv')

In [19]:
drop_columns_train_ab=['ID', '기준년월','대표청구서수령지구분코드','청구서수령방법',
                 '카드이용한도금액_B1M','카드이용한도금액',
                 '이용개월수_할부_R12M', '이용개월수_할부_R6M','이용개월수_할부_무이자_R6M', '이용개월수_할부_R3M',
                '이용개월수_할부_무이자_R3M', '이용후경과월_할부']
drop_columns_test_ab=['대표청구서수령지구분코드','청구서수령방법',
                 '카드이용한도금액_B1M','카드이용한도금액',
                 '이용개월수_할부_R12M', '이용개월수_할부_R6M','이용개월수_할부_무이자_R6M', '이용개월수_할부_R3M',
                '이용개월수_할부_무이자_R3M',
                '이용후경과월_할부']
train_ab2=train_ab.drop(columns=drop_columns_train_ab)
test_ab2=test_ab.drop(columns=drop_columns_test_ab)

In [4]:
drop_columns_train_cd=['ID', '기준년월','청구금액_R3M','청구금액_B0']
drop_columns_test_cd=['청구금액_R3M','청구금액_B0']
train_cd2=train_cd.drop(columns=drop_columns_train_cd)
test_cd2=test_cd.drop(columns=drop_columns_test_cd)

In [18]:
# 대표값을 딕셔너리로 정의
amount_map = {
    '01.100만원+': 100,   # 최소 기준값
    '02.50만원+': 50,
    '03.30만원+': 30,
    '04.10만원+': 10,
    '05.10만원-': 5,      # 10만원 이하이므로 5로 가정
    '09.미사용': 0        # 미사용은 0원
}

# 수치형 컬럼 생성
train_cd2['이용금액대'] = train_cd2['이용금액대'].map(amount_map)
test_cd2['이용금액대'] = test_cd2['이용금액대'].map(amount_map)

In [20]:
train_ab2.to_csv('model3_train_AB.csv', index=False, encoding='utf-8-sig')
test_ab2.to_csv('model3_test_AB.csv', index=False, encoding='utf-8-sig')

In [19]:
train_cd2.to_csv('model3_train_CD(3).csv', index=False, encoding='utf-8-sig')
test_cd2.to_csv('model3_test_CD(3).csv', index=False, encoding='utf-8-sig')