In [26]:
# 기본
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 경고 뜨지 않게 설정
import warnings
warnings.filterwarnings('ignore')

# 그래프 설정
sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False

# 데이터 전처리 알고리즘
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# 학습용과 검증용으로 나누는 함수
from sklearn.model_selection import train_test_split

# 교차 검증
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

# 평가함수
# 분류용
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

# 회귀용
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

# 모델의 최적의 하이퍼 파라미터를 찾기 위한 도구
from sklearn.model_selection import GridSearchCV

# 머신러닝 알고리즘 - 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import VotingClassifier

# 머신러닝 알고리즘 - 회귀
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from sklearn.ensemble import VotingRegressor

# 학습 모델 저장을 위한 라이브러리
import pickle

In [27]:
# 학습이 완료된 모델을 저장할 파일 이름
best_model_path = 'model/best_model_final12_pca.dat'

In [28]:
with open(best_model_path, 'rb') as fp :
    model6 = pickle.load(fp)
    scalerX = pickle.load(fp)
    scaler_columns = pickle.load(fp)
    le = pickle.load(fp)
    
display(model6)
display(scalerX)
display(scaler_columns)
display(le)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=-1,
              num_parallel_tree=None, ...)

StandardScaler()

['p1',
 'p2',
 'p3',
 'p4',
 'p5',
 'p6',
 'p7',
 'p8',
 'p9',
 'p10',
 'p11',
 'p12',
 'p13',
 'p14',
 'p15',
 'p16',
 'p17',
 'p18',
 'p19',
 'p20']

LabelEncoder()

### Target

In [29]:
target1=pd.read_parquet(r'data/train/1.회원정보/201807_train_.parquet')
target2=pd.read_parquet(r'data/train/1.회원정보/201808_train_.parquet')
target3=pd.read_parquet(r'data/train/1.회원정보/201809_train_.parquet')
target4=pd.read_parquet(r'data/train/1.회원정보/201810_train_.parquet')
target5=pd.read_parquet(r'data/train/1.회원정보/201811_train_.parquet')
target6=pd.read_parquet(r'data/train/1.회원정보/201812_train_.parquet')

In [30]:
tg_df = pd.concat([
    target1['Segment'],
    target2['Segment'],
    target3['Segment'],
    target4['Segment'],
    target5['Segment'],
    target6['Segment']
])

tg_df = tg_df.reset_index(drop=True).to_frame(name='Segment')
tg_df

        Segment
0             D
1             E
2             C
3             D
4             E
...         ...
2399995       E
2399996       D
2399997       C
2399998       E
2399999       E

[2400000 rows x 1 columns]

In [34]:
# 예측할 데이터를 읽어온다.
df1 = pd.read_csv('(C_D_NotCD)_pca(20)_test.csv')
df1 = df1.drop(columns=['ID'])
df1

,p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20
0,-13705.067440,46467.691559,15942.555179,50207.425732,13279.118384,-10540.445197,8275.998167,597.220989,-2948.674740,-439.575976,1930.734990,1706.048258,-965.838040,-161.714809,-719.020089,-2860.625905,3313.634852,342.230181,-284.058508,-1063.562006
1,-157243.879719,-13302.476700,-30608.699050,-10141.276718,-20191.567610,16734.803593,3865.040703,2766.081509,-7436.949339,15593.166090,-7382.057993,-12124.200787,11666.408502,-4085.345752,752.390808,-1908.040291,-2157.231466,-2163.578964,157.956699,178.894712
2,-48997.752561,-17050.828103,-8785.969908,12658.477978,976.577391,-4781.244178,-1387.027484,3497.772702,-3101.396425,-10387.737288,5289.071879,3833.353734,-924.614911,6633.882026,1840.229396,-4320.036898,2559.579926,2611.515095,1951.500122,-453.318890
3,52617.221072,-117970.778109,-63093.266659,-13703.021001,-525.569384,-20709.360313,-11409.284360,16661.488453,4419.949193,-1665.345793,-3731.820322,-9062.662800,1465.081008,-557.481777,-979.536980,-1589.199659,-1228.275578,1990.620854,3028.806924,-720.985493
4,-150893.648894,23186.461190,-25302.261145,-980.885632,-19613.383003,27205.851461,8992.013284,-103.473319,-6977.553648,-11877.372912,-1605.514633,-15599.675321,732.953370,4740.377962,648.517284,-539.828000,-1710.122138,-865.854859,-827.977316,-66.660295
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96493,5534.292187,-48302.147655,-35833.803086,20868.002514,-16374.674953,-5379.702512,-11563.581200,-3282.599440,2630.263551,1120.416128,-1928.996030,2287.983091,1015.485091,160.905425,5216.652475,3256.013247,-3489.050837,1456.987510,541.779349,-382.434722
96494,-32783.504355,-53443.942457,-33865.260054,9599.980027,16651.123902,-15976.790692,-13476.342166,1921.854194,-4305.693411,5777.082963,-2579.876587,-5417.860671,3484.478509,-2302.378322,-1166.886929,-226.575257,1158.781200,-789.949760,-2876.429032,2098.222234
96495,390074.729741,96464.046501,-105134.555049,-88208.920785,-2426.837122,19983.301997,13348.602388,41972.099226,-16046.998083,4965.756830,9466.084412,9229.586083,1084.252045,-2342.334199,12283.910664,-11720.708318,-2909.645085,1386.512242,1992.611980,-131.153143
96496,-46298.872570,13607.202059,118027.253642,-1223.211427,-13979.589030,-10674.375726,27371.224836,9007.675594,12317.703831,8117.270221,-112.691461,1389.377297,-382.730890,-2926.906637,3525.806139,-4855.369976,-508.454855,3470.659567,-894.316036,-765.165143
96497,280723.132512,-161698.898857,-142736.969338,-43064.312408,-75343.017197,38329.113651,10618.640129,-9400.235482,12479.288455,3852.132888,-1361.196455,-21484.319654,4216.558776,-182.169296,-3338.510872,4572.614387,528.180119,-1267.450181,-2988.717889,-3242.599772

In [35]:
X_test = df1
X_test = X_test[scaler_columns]

In [36]:
X_test

,p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20
0,-13705.067440,46467.691559,15942.555179,50207.425732,13279.118384,-10540.445197,8275.998167,597.220989,-2948.674740,-439.575976,1930.734990,1706.048258,-965.838040,-161.714809,-719.020089,-2860.625905,3313.634852,342.230181,-284.058508,-1063.562006
1,-157243.879719,-13302.476700,-30608.699050,-10141.276718,-20191.567610,16734.803593,3865.040703,2766.081509,-7436.949339,15593.166090,-7382.057993,-12124.200787,11666.408502,-4085.345752,752.390808,-1908.040291,-2157.231466,-2163.578964,157.956699,178.894712
2,-48997.752561,-17050.828103,-8785.969908,12658.477978,976.577391,-4781.244178,-1387.027484,3497.772702,-3101.396425,-10387.737288,5289.071879,3833.353734,-924.614911,6633.882026,1840.229396,-4320.036898,2559.579926,2611.515095,1951.500122,-453.318890
3,52617.221072,-117970.778109,-63093.266659,-13703.021001,-525.569384,-20709.360313,-11409.284360,16661.488453,4419.949193,-1665.345793,-3731.820322,-9062.662800,1465.081008,-557.481777,-979.536980,-1589.199659,-1228.275578,1990.620854,3028.806924,-720.985493
4,-150893.648894,23186.461190,-25302.261145,-980.885632,-19613.383003,27205.851461,8992.013284,-103.473319,-6977.553648,-11877.372912,-1605.514633,-15599.675321,732.953370,4740.377962,648.517284,-539.828000,-1710.122138,-865.854859,-827.977316,-66.660295
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96493,5534.292187,-48302.147655,-35833.803086,20868.002514,-16374.674953,-5379.702512,-11563.581200,-3282.599440,2630.263551,1120.416128,-1928.996030,2287.983091,1015.485091,160.905425,5216.652475,3256.013247,-3489.050837,1456.987510,541.779349,-382.434722
96494,-32783.504355,-53443.942457,-33865.260054,9599.980027,16651.123902,-15976.790692,-13476.342166,1921.854194,-4305.693411,5777.082963,-2579.876587,-5417.860671,3484.478509,-2302.378322,-1166.886929,-226.575257,1158.781200,-789.949760,-2876.429032,2098.222234
96495,390074.729741,96464.046501,-105134.555049,-88208.920785,-2426.837122,19983.301997,13348.602388,41972.099226,-16046.998083,4965.756830,9466.084412,9229.586083,1084.252045,-2342.334199,12283.910664,-11720.708318,-2909.645085,1386.512242,1992.611980,-131.153143
96496,-46298.872570,13607.202059,118027.253642,-1223.211427,-13979.589030,-10674.375726,27371.224836,9007.675594,12317.703831,8117.270221,-112.691461,1389.377297,-382.730890,-2926.906637,3525.806139,-4855.369976,-508.454855,3470.659567,-894.316036,-765.165143
96497,280723.132512,-161698.898857,-142736.969338,-43064.312408,-75343.017197,38329.113651,10618.640129,-9400.235482,12479.288455,3852.132888,-1361.196455,-21484.319654,4216.558776,-182.169296,-3338.510872,4572.614387,528.180119,-1267.450181,-2988.717889,-3242.599772

In [37]:
# 데이터 표준화
scaled_data = scalerX.transform(X_test)
scaled_data

array([[-0.13839763,  0.57402699,  0.23766419, ...,  0.14650554,
        -0.13156021, -0.93197993],
       [-1.11924318, -0.13960679, -0.49432293, ..., -0.96546934,
         0.08343646,  0.15900586],
       [-0.37956357, -0.18436072, -0.15117522, ...,  1.15352071,
         0.95581789, -0.39613304],
       ...,
       [ 2.62075588,  1.17096503, -1.66619183, ...,  0.60991491,
         0.97581474, -0.11324331],
       [-0.36112128,  0.18168486,  1.84287732, ...,  1.53477364,
        -0.42839013, -0.66996136],
       [ 1.87352225, -1.91140536, -2.25746447, ..., -0.5678043 ,
        -1.44710943, -2.8453659 ]])

In [38]:
# 입력데이터를 test_X 변수에 담아준다.
X_text2 = scaled_data

In [39]:
# 예측한다.
y_pred = model6.predict(X_text2)
y_pred_labels = le.inverse_transform(y_pred)
y_pred_labels

array(['D', 'D', 'D', ..., 'C', 'C', 'C'], dtype=object)

In [40]:
# 결과를 붙힌다음 저장한다.
# 예측할 데이터를 다시 불러온다.
result_df = pd.read_csv('(C_D_NotCD)_pca(20)_test.csv')
result_df['Segment'] = y_pred_labels

In [43]:
result_df2 = result_df[['ID', 'Segment']]

In [44]:
result_df2['Segment'].value_counts()

Segment
D        74432
C        21990
notCD       76
Name: count, dtype: int64

In [45]:
most_common_by_id = result_df2.groupby('ID')['Segment'] \
    .agg(lambda x: x.mode().iloc[0]) \
    .reset_index()

# 컬럼명 확인
most_common_by_id.columns = ['ID', 'Segment']

In [46]:
most_common_by_id

               ID Segment
0      TEST_00002       D
1      TEST_00010       D
2      TEST_00012       D
3      TEST_00016       D
4      TEST_00032       D
...           ...     ...
16078  TEST_99957       D
16079  TEST_99961       D
16080  TEST_99982       C
16081  TEST_99994       C
16082  TEST_99998       C

[16083 rows x 2 columns]

In [47]:
most_common_by_id['Segment'].value_counts()

Segment
D        12283
C         3799
notCD        1
Name: count, dtype: int64

In [50]:
most_common_by_id2 = most_common_by_id[most_common_by_id['Segment'] == 'notCD']

In [51]:
most_common_by_id2

               ID Segment
11941  TEST_74584   notCD

In [52]:
most_common_by_id.to_csv('data/model3_C,D,notCD.csv', index=False, encoding='utf-8-sig')
print('저장완료')

저장완료

In [53]:
most_common_by_id2.to_csv('data/model3_notCD.csv', index=False, encoding='utf-8-sig')
print('저장완료')

저장완료

In [55]:
df2 = pd.read_csv('model3_test_AB.csv')

In [56]:
df2

,ID,기준년월,이용후경과월_할부_무이자,이용개월수_할부_무이자_R12M,카드이용한도금액_B2M,CA한도금액,이용건수_할부_무이자_R3M,이용건수_할부_R3M,이용금액_할부_무이자_R6M,방문횟수_앱_R6M,거주시도명,연령,Life_Stage,인입횟수_ARS_R6M,캠페인접촉건수_R12M,이용메뉴건수_ARS_R6M,캠페인접촉일수_R12M,방문일수_PC_R6M,방문횟수_PC_R6M,할인건수_R3M
0,TEST_00000,201807,12,0,50006,18131,0,0,0,1회 이상,경기,40대,자녀성장(1),1회 이상,1회 이상,1회 이상,1일 이상,1회 이상,1회 이상,1회 이상
1,TEST_00001,201807,0,9,50003,16819,6,7,16654,1회 이상,인천,60대,자녀독립기,1회 이상,5회 이상,1회 이상,5일 이상,1회 이상,1회 이상,1회 이상
2,TEST_00002,201807,3,5,100056,30505,0,2,13260,1회 이상,경기,40대,자녀성장(1),1회 이상,10회 이상,1회 이상,10일 이상,1회 이상,1회 이상,1회 이상
3,TEST_00003,201807,2,1,19693,6402,1,2,-685,1회 이상,인천,40대,자녀성장(1),1회 이상,15회 이상,1회 이상,15일 이상,1회 이상,1회 이상,1회 이상
4,TEST_00004,201807,0,6,3924,0,3,4,9332,1회 이상,경기,40대,자녀성장(1),1회 이상,1회 이상,1회 이상,1일 이상,1회 이상,1회 이상,1회 이상
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,TEST_99995,201812,12,0,0,0,0,0,0,1회 이상,경기,60대,노년생활,1회 이상,1회 이상,1회 이상,1일 이상,1회 이상,1회 이상,1회 이상
599996,TEST_99996,201812,12,0,49990,17876,0,0,0,10회 이상,서울,30대,자녀출산기,1회 이상,1회 이상,1회 이상,1일 이상,1회 이상,1회 이상,1회 이상
599997,TEST_99997,201812,12,0,30004,13332,0,0,0,1회 이상,경남,30대,자녀성장(1),1회 이상,1회 이상,1회 이상,1일 이상,1회 이상,1회 이상,1회 이상
599998,TEST_99998,201812,2,3,37139,17362,0,0,0,40회 이상,경남,30대,가족구축기,1회 이상,5회 이상,1회 이상,5일 이상,1회 이상,1회 이상,1회 이상
599999,TEST_99999,201812,12,0,79148,30242,0,0,0,1회 이상,경기,30대,자녀출산기,1회 이상,1회 이상,1회 이상,1일 이상,1회 이상,1회 이상,1회 이상

In [68]:
# 1. 'Not_E'인 ID만 필터링
filtered_ids = most_common_by_id[most_common_by_id['Segment'] == 'not CD']['ID']

# 2. df2에서 해당 ID만 골라오기
final_cd_df = df2[df2['ID'].isin(filtered_)]ids

In [69]:
filtered_ids

6666     TEST_41053
9495     TEST_59250
13160    TEST_81971
Name: ID, dtype: object

In [70]:
final_cd_df

,ID,기준년월,이용후경과월_할부_무이자,이용개월수_할부_무이자_R12M,카드이용한도금액_B2M,CA한도금액,이용건수_할부_무이자_R3M,이용건수_할부_R3M,이용금액_할부_무이자_R6M,방문횟수_앱_R6M,거주시도명,연령,Life_Stage,인입횟수_ARS_R6M,캠페인접촉건수_R12M,이용메뉴건수_ARS_R6M,캠페인접촉일수_R12M,방문일수_PC_R6M,방문횟수_PC_R6M,할인건수_R3M
41053,TEST_41053,201807,0,9,192519,57200,6,6,37430,1회 이상,부산,40대,자녀성장(1),1회 이상,1회 이상,1회 이상,1일 이상,10회 이상,20회 이상,1회 이상
59250,TEST_59250,201807,0,9,194466,53032,6,6,45447,1회 이상,부산,50대,자녀성장(2),1회 이상,1회 이상,1회 이상,1일 이상,1회 이상,1회 이상,1회 이상
81971,TEST_81971,201807,1,6,196315,55288,2,3,22975,1회 이상,경기,50대,자녀성장(2),1회 이상,1회 이상,1회 이상,1일 이상,1회 이상,1회 이상,1회 이상
141053,TEST_41053,201808,0,9,190926,54741,6,6,36834,1회 이상,부산,40대,자녀성장(1),1회 이상,1회 이상,1회 이상,1일 이상,10회 이상,20회 이상,1회 이상
159250,TEST_59250,201808,0,9,190715,54209,6,6,44845,1회 이상,부산,50대,자녀성장(2),1회 이상,1회 이상,1회 이상,1일 이상,1회 이상,1회 이상,1회 이상
181971,TEST_81971,201808,2,6,194662,58343,1,2,23263,1회 이상,경기,50대,자녀성장(2),1회 이상,1회 이상,1회 이상,1일 이상,1회 이상,1회 이상,1회 이상
241053,TEST_41053,201809,0,9,191456,58001,6,6,38275,1회 이상,부산,40대,자녀성장(1),1회 이상,1회 이상,1회 이상,1일 이상,10회 이상,20회 이상,1회 이상
259250,TEST_59250,201809,0,9,190933,56151,6,6,45019,1회 이상,부산,50대,자녀성장(2),1회 이상,1회 이상,1회 이상,1일 이상,1회 이상,1회 이상,1회 이상
281971,TEST_81971,201809,2,6,199345,57917,3,3,23134,1회 이상,경기,50대,자녀성장(2),1회 이상,1회 이상,1회 이상,1일 이상,1회 이상,1회 이상,1회 이상
341053,TEST_41053,201810,0,9,194313,61602,6,6,37613,1회 이상,부산,40대,자녀성장(1),1회 이상,1회 이상,1회 이상,1일 이상,10회 이상,10회 이상,1회 이상
359250,TEST_59250,201810,0,9,198335,54330,6,6,46448,1회 이상,부산,50대,자녀성장(2),1회 이상,1회 이상,1회 이상,1일 이상,1회 이상,1회 이상,1회 이상
381971,TEST_81971,201810,2,6,203409,60487,3,3,11134,1회 이상,경기,50대,자녀성장(2),1회 이상,1회 이상,1회 이상,1일 이상,1회 이상,1회 이상,1회 이상
441053,TEST_41053,201811,0,9,226442,65655,6,6,36462,1회 이상,부산,40대,자녀성장(1),1회 이상,1회 이상,1회 이상,1일 이상,10회 이상,10회 이상,1회 이상
459250,TEST_59250,201811,0,9,190898,61912,6,6,46588,1회 이상,부산,50대,자녀성장(2),1회 이상,1회 이상,1회 이상,1일 이상,1회 이상,1회 이상,1회 이상
481971,TEST_81971,201811,1,7,201627,58150,3,3,17059,1회 이상,경기,50대,자녀성장(2),1회 이상,1회 이상,1회 이상,1일 이상,1회 이상,1회 이상,1회 이상
541053,TEST_41053,201812,1,9,202667,63699,6,6,37316,1회 이상,부산,40대,자녀성장(1),1회 이상,1회 이상,1회 이상,1일 이상,20회 이상,20회 이상,1회 이상
559250,TEST_59250,201812,0,9,213163,58586,6,6,44597,1회 이상,부산,50대,자녀성장(2),1회 이상,1회 이상,1회 이상,1일 이상,1회 이상,1회 이상,1회 이상
581971,TEST_81971,201812,1,7,181254,56645,3,3,17956,1회 이상,경기,50대,자녀성장(2),1회 이상,1회 이상,1회 이상,1일 이상,1회 이상,1회 이상,1회 이상

In [72]:
final_cd_df.to_csv('data/test_model3_notCD.csv', index=False, encoding='utf-8-sig')