In [22]:
# 기본
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 경고 뜨지 않게 설정
import warnings
warnings.filterwarnings('ignore')

# 그래프 설정
sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False

# 데이터 전처리 알고리즘
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# 학습용과 검증용으로 나누는 함수
from sklearn.model_selection import train_test_split

# 교차 검증
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

# 평가함수
# 분류용
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

# 회귀용
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

# 모델의 최적의 하이퍼 파라미터를 찾기 위한 도구
from sklearn.model_selection import GridSearchCV

# 머신러닝 알고리즘 - 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import VotingClassifier

# 머신러닝 알고리즘 - 회귀
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from sklearn.ensemble import VotingRegressor

# 학습 모델 저장을 위한 라이브러리
import pickle

In [25]:
# 학습이 완료된 모델을 저장할 파일 이름
best_model_path = 'model/best_model_C,D.dat'

In [33]:
with open(best_model_path, 'rb') as fp :
    model6 = pickle.load(fp)
    scalerX = pickle.load(fp)
    scaler_columns = pickle.load(fp)
    Encoder1 = pickle.load(fp)
    le = pickle.load(fp)
    
display(model6)
display(scalerX)
display(scaler_columns)
display(Encoder1)
display(le)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=-1,
              num_parallel_tree=None, ...)

StandardScaler()

['_1순위카드이용금액',
 '연령',
 '이용금액_R3M_신용체크',
 '이용카드수_신용체크',
 '소지카드수_유효_신용',
 '이용가능여부_해외겸용_본인',
 '수신거부여부_TM',
 '이용금액_일시불_R12M',
 '이용금액대',
 '청구금액_R6M',
 '평잔_일시불_3M']

LabelEncoder()

LabelEncoder()

### Target

In [34]:
target1=pd.read_parquet(r'data/train/1.회원정보/201807_train_.parquet')
target2=pd.read_parquet(r'data/train/1.회원정보/201808_train_.parquet')
target3=pd.read_parquet(r'data/train/1.회원정보/201809_train_.parquet')
target4=pd.read_parquet(r'data/train/1.회원정보/201810_train_.parquet')
target5=pd.read_parquet(r'data/train/1.회원정보/201811_train_.parquet')
target6=pd.read_parquet(r'data/train/1.회원정보/201812_train_.parquet')

In [35]:
tg_df = pd.concat([
    target1['Segment'],
    target2['Segment'],
    target3['Segment'],
    target4['Segment'],
    target5['Segment'],
    target6['Segment']
])

tg_df = tg_df.reset_index(drop=True).to_frame(name='Segment')
tg_df

        Segment
0             D
1             E
2             C
3             D
4             E
...         ...
2399995       E
2399996       D
2399997       C
2399998       E
2399999       E

[2400000 rows x 1 columns]

In [36]:
# 예측할 데이터를 읽어온다.
df1 = pd.read_csv('data/test_model3_notE.csv')
df1 = df1.drop(columns=['ID','기준년월'])
df1

,청구금액_R6M,이용금액_일시불_R12M,_1순위카드이용금액,이용금액대,연령,이용금액_R3M_신용체크,이용카드수_신용체크,소지카드수_유효_신용,이용가능여부_해외겸용_본인,수신거부여부_TM,평잔_일시불_3M
0,71867,73003,27071,100,40대,40758,2,2,0,0,5606
1,12797,29326,7544,10,40대,45764,2,1,1,0,751
2,63042,86805,24425,50,40대,37849,2,1,0,0,47158
3,77903,207417,42636,100,30대,51440,2,2,1,0,15431
4,11525,21910,3885,5,30대,54632,2,1,1,1,2284
...,...,...,...,...,...,...,...,...,...,...,...
96493,66775,136892,38644,100,40대,61148,4,2,1,1,14460
96494,58282,117578,25961,100,40대,30318,1,1,1,0,5505
96495,129230,447150,70955,100,70대이상,94440,1,1,1,0,26511
96496,150417,33505,29020,100,40대,31697,1,1,1,0,2810
96497,108420,423882,63592,100,30대,173263,6,3,1,1,17039

In [37]:
X_test = df1.drop('Segment', axis=1, errors='ignore')
X_test = X_test[scaler_columns]

In [38]:
X_test

,_1순위카드이용금액,연령,이용금액_R3M_신용체크,이용카드수_신용체크,소지카드수_유효_신용,이용가능여부_해외겸용_본인,수신거부여부_TM,이용금액_일시불_R12M,이용금액대,청구금액_R6M,평잔_일시불_3M
0,27071,40대,40758,2,2,0,0,73003,100,71867,5606
1,7544,40대,45764,2,1,1,0,29326,10,12797,751
2,24425,40대,37849,2,1,0,0,86805,50,63042,47158
3,42636,30대,51440,2,2,1,0,207417,100,77903,15431
4,3885,30대,54632,2,1,1,1,21910,5,11525,2284
...,...,...,...,...,...,...,...,...,...,...,...
96493,38644,40대,61148,4,2,1,1,136892,100,66775,14460
96494,25961,40대,30318,1,1,1,0,117578,100,58282,5505
96495,70955,70대이상,94440,1,1,1,0,447150,100,129230,26511
96496,29020,40대,31697,1,1,1,0,33505,100,150417,2810
96497,63592,30대,173263,6,3,1,1,423882,100,108420,17039

In [39]:
# 예측할 데이터 변환
X_test['연령'] = Encoder1.transform(X_test['연령'])

In [40]:
# 데이터 표준화
scaled_data = scalerX.transform(X_test)
scaled_data

array([[ 0.51245181, -0.07571706,  0.37669971, ...,  1.30397978,
         0.23253563, -0.12044842],
       [-0.55983785, -0.07571706,  0.53970626, ..., -0.94095402,
        -0.66003666, -0.60632892],
       [ 0.36715154, -0.07571706,  0.28197617, ...,  0.05679434,
         0.0991862 ,  4.03800817],
       ...,
       [ 2.92226178,  2.45338101,  2.12470563, ...,  1.30397978,
         1.09931444,  1.97168999],
       [ 0.6194776 , -0.07571706,  0.0816533 , ...,  1.30397978,
         1.41945883, -0.40026755],
       [ 2.51793604, -0.91874975,  4.69135872, ...,  1.30397978,
         0.78486667,  1.02374763]])

In [41]:
# 입력데이터를 test_X 변수에 담아준다.
X_text2 = scaled_data

In [42]:
# 예측한다.
y_pred = model6.predict(X_text2)
y_pred_labels = le.inverse_transform(y_pred)
y_pred_labels

array(['D', 'D', 'D', ..., 'C', 'D', 'C'], dtype=object)

In [45]:
# 결과를 붙힌다음 저장한다.
# 예측할 데이터를 다시 불러온다.
result_df = pd.read_csv('data/test_model3_notE.csv')
result_df['Segment'] = y_pred_labels

In [46]:
result_df2 = result_df[['ID', 'Segment']]

In [47]:
result_df2['Segment'].value_counts()

Segment
D         75814
C         20622
not CD       62
Name: count, dtype: int64

In [48]:
most_common_by_id = result_df2.groupby('ID')['Segment'] \
    .agg(lambda x: x.mode().iloc[0]) \
    .reset_index()

# 컬럼명 확인
most_common_by_id.columns = ['ID', 'Segment']

In [49]:
most_common_by_id

               ID Segment
0      TEST_00002       D
1      TEST_00010       D
2      TEST_00012       D
3      TEST_00016       D
4      TEST_00032       D
...           ...     ...
16078  TEST_99957       D
16079  TEST_99961       D
16080  TEST_99982       C
16081  TEST_99994       D
16082  TEST_99998       C

[16083 rows x 2 columns]

In [50]:
most_common_by_id['Segment'].value_counts()

Segment
D         12540
C          3540
not CD        3
Name: count, dtype: int64

In [51]:
most_common_by_id2 = most_common_by_id[most_common_by_id['Segment'] == 'not CD']

In [58]:
most_common_by_id2

               ID Segment
6666   TEST_41053  not CD
9495   TEST_59250  not CD
13160  TEST_81971  not CD

In [52]:
most_common_by_id.to_csv('data/model3_C,D,notCD.csv', index=False, encoding='utf-8-sig')
print('저장완료')

저장완료

In [53]:
most_common_by_id2.to_csv('data/model3_notCD.csv', index=False, encoding='utf-8-sig')
print('저장완료')

저장완료

In [54]:
df2 = pd.read_csv('model3_test_AB.csv')

In [55]:
df2

,ID,기준년월,이용후경과월_할부_무이자,이용개월수_할부_무이자_R12M,카드이용한도금액_B2M,CA한도금액,이용건수_할부_무이자_R3M,이용건수_할부_R3M,이용금액_할부_무이자_R6M,방문횟수_앱_R6M,거주시도명,연령,Life_Stage,인입횟수_ARS_R6M,캠페인접촉건수_R12M,이용메뉴건수_ARS_R6M,캠페인접촉일수_R12M,방문일수_PC_R6M,방문횟수_PC_R6M,할인건수_R3M
0,TEST_00000,201807,12,0,50006,18131,0,0,0,1회 이상,경기,40대,자녀성장(1),1회 이상,1회 이상,1회 이상,1일 이상,1회 이상,1회 이상,1회 이상
1,TEST_00001,201807,0,9,50003,16819,6,7,16654,1회 이상,인천,60대,자녀독립기,1회 이상,5회 이상,1회 이상,5일 이상,1회 이상,1회 이상,1회 이상
2,TEST_00002,201807,3,5,100056,30505,0,2,13260,1회 이상,경기,40대,자녀성장(1),1회 이상,10회 이상,1회 이상,10일 이상,1회 이상,1회 이상,1회 이상
3,TEST_00003,201807,2,1,19693,6402,1,2,-685,1회 이상,인천,40대,자녀성장(1),1회 이상,15회 이상,1회 이상,15일 이상,1회 이상,1회 이상,1회 이상
4,TEST_00004,201807,0,6,3924,0,3,4,9332,1회 이상,경기,40대,자녀성장(1),1회 이상,1회 이상,1회 이상,1일 이상,1회 이상,1회 이상,1회 이상
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,TEST_99995,201812,12,0,0,0,0,0,0,1회 이상,경기,60대,노년생활,1회 이상,1회 이상,1회 이상,1일 이상,1회 이상,1회 이상,1회 이상
599996,TEST_99996,201812,12,0,49990,17876,0,0,0,10회 이상,서울,30대,자녀출산기,1회 이상,1회 이상,1회 이상,1일 이상,1회 이상,1회 이상,1회 이상
599997,TEST_99997,201812,12,0,30004,13332,0,0,0,1회 이상,경남,30대,자녀성장(1),1회 이상,1회 이상,1회 이상,1일 이상,1회 이상,1회 이상,1회 이상
599998,TEST_99998,201812,2,3,37139,17362,0,0,0,40회 이상,경남,30대,가족구축기,1회 이상,5회 이상,1회 이상,5일 이상,1회 이상,1회 이상,1회 이상
599999,TEST_99999,201812,12,0,79148,30242,0,0,0,1회 이상,경기,30대,자녀출산기,1회 이상,1회 이상,1회 이상,1일 이상,1회 이상,1회 이상,1회 이상

In [68]:
# 1. 'Not_E'인 ID만 필터링
filtered_ids = most_common_by_id[most_common_by_id['Segment'] == 'not CD']['ID']

# 2. df2에서 해당 ID만 골라오기
final_cd_df = df2[df2['ID'].isin(filtered_ids)]

In [69]:
filtered_ids

6666     TEST_41053
9495     TEST_59250
13160    TEST_81971
Name: ID, dtype: object

In [70]:
final_cd_df

,ID,기준년월,이용후경과월_할부_무이자,이용개월수_할부_무이자_R12M,카드이용한도금액_B2M,CA한도금액,이용건수_할부_무이자_R3M,이용건수_할부_R3M,이용금액_할부_무이자_R6M,방문횟수_앱_R6M,거주시도명,연령,Life_Stage,인입횟수_ARS_R6M,캠페인접촉건수_R12M,이용메뉴건수_ARS_R6M,캠페인접촉일수_R12M,방문일수_PC_R6M,방문횟수_PC_R6M,할인건수_R3M
41053,TEST_41053,201807,0,9,192519,57200,6,6,37430,1회 이상,부산,40대,자녀성장(1),1회 이상,1회 이상,1회 이상,1일 이상,10회 이상,20회 이상,1회 이상
59250,TEST_59250,201807,0,9,194466,53032,6,6,45447,1회 이상,부산,50대,자녀성장(2),1회 이상,1회 이상,1회 이상,1일 이상,1회 이상,1회 이상,1회 이상
81971,TEST_81971,201807,1,6,196315,55288,2,3,22975,1회 이상,경기,50대,자녀성장(2),1회 이상,1회 이상,1회 이상,1일 이상,1회 이상,1회 이상,1회 이상
141053,TEST_41053,201808,0,9,190926,54741,6,6,36834,1회 이상,부산,40대,자녀성장(1),1회 이상,1회 이상,1회 이상,1일 이상,10회 이상,20회 이상,1회 이상
159250,TEST_59250,201808,0,9,190715,54209,6,6,44845,1회 이상,부산,50대,자녀성장(2),1회 이상,1회 이상,1회 이상,1일 이상,1회 이상,1회 이상,1회 이상
181971,TEST_81971,201808,2,6,194662,58343,1,2,23263,1회 이상,경기,50대,자녀성장(2),1회 이상,1회 이상,1회 이상,1일 이상,1회 이상,1회 이상,1회 이상
241053,TEST_41053,201809,0,9,191456,58001,6,6,38275,1회 이상,부산,40대,자녀성장(1),1회 이상,1회 이상,1회 이상,1일 이상,10회 이상,20회 이상,1회 이상
259250,TEST_59250,201809,0,9,190933,56151,6,6,45019,1회 이상,부산,50대,자녀성장(2),1회 이상,1회 이상,1회 이상,1일 이상,1회 이상,1회 이상,1회 이상
281971,TEST_81971,201809,2,6,199345,57917,3,3,23134,1회 이상,경기,50대,자녀성장(2),1회 이상,1회 이상,1회 이상,1일 이상,1회 이상,1회 이상,1회 이상
341053,TEST_41053,201810,0,9,194313,61602,6,6,37613,1회 이상,부산,40대,자녀성장(1),1회 이상,1회 이상,1회 이상,1일 이상,10회 이상,10회 이상,1회 이상
359250,TEST_59250,201810,0,9,198335,54330,6,6,46448,1회 이상,부산,50대,자녀성장(2),1회 이상,1회 이상,1회 이상,1일 이상,1회 이상,1회 이상,1회 이상
381971,TEST_81971,201810,2,6,203409,60487,3,3,11134,1회 이상,경기,50대,자녀성장(2),1회 이상,1회 이상,1회 이상,1일 이상,1회 이상,1회 이상,1회 이상
441053,TEST_41053,201811,0,9,226442,65655,6,6,36462,1회 이상,부산,40대,자녀성장(1),1회 이상,1회 이상,1회 이상,1일 이상,10회 이상,10회 이상,1회 이상
459250,TEST_59250,201811,0,9,190898,61912,6,6,46588,1회 이상,부산,50대,자녀성장(2),1회 이상,1회 이상,1회 이상,1일 이상,1회 이상,1회 이상,1회 이상
481971,TEST_81971,201811,1,7,201627,58150,3,3,17059,1회 이상,경기,50대,자녀성장(2),1회 이상,1회 이상,1회 이상,1일 이상,1회 이상,1회 이상,1회 이상
541053,TEST_41053,201812,1,9,202667,63699,6,6,37316,1회 이상,부산,40대,자녀성장(1),1회 이상,1회 이상,1회 이상,1일 이상,20회 이상,20회 이상,1회 이상
559250,TEST_59250,201812,0,9,213163,58586,6,6,44597,1회 이상,부산,50대,자녀성장(2),1회 이상,1회 이상,1회 이상,1일 이상,1회 이상,1회 이상,1회 이상
581971,TEST_81971,201812,1,7,181254,56645,3,3,17956,1회 이상,경기,50대,자녀성장(2),1회 이상,1회 이상,1회 이상,1일 이상,1회 이상,1회 이상,1회 이상

In [72]:
final_cd_df.to_csv('data/test_model3_notCD.csv', index=False, encoding='utf-8-sig')