In [1]:
# 기본
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 경고 뜨지 않게 설정
import warnings
warnings.filterwarnings('ignore')

# 그래프 설정
sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False

# 데이터 전처리 알고리즘
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# 학습용과 검증용으로 나누는 함수
from sklearn.model_selection import train_test_split

# 교차 검증
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

# 평가함수
# 분류용
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

# 회귀용
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

# 모델의 최적의 하이퍼 파라미터를 찾기 위한 도구
from sklearn.model_selection import GridSearchCV

# 머신러닝 알고리즘 - 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import VotingClassifier

# 머신러닝 알고리즘 - 회귀
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from sklearn.ensemble import VotingRegressor

# 학습 모델 저장을 위한 라이브러리
import pickle

In [40]:
# 학습이 완료된 모델을 저장할 파일 이름
best_model_path = 'model/best_model_final13.dat'

In [41]:
with open(best_model_path, 'rb') as fp :
    model6 = pickle.load(fp)
    scalerX = pickle.load(fp)
    scaler_columns = pickle.load(fp)
    Encoder1 = pickle.load(fp)
    Encoder2 = pickle.load(fp)
    Encoder3 = pickle.load(fp)
    Encoder4 = pickle.load(fp)
    Encoder5 = pickle.load(fp)
    Encoder6 = pickle.load(fp)
    le = pickle.load(fp)
    
display(model6)
display(scalerX)
display(Encoder1)
display(Encoder2)
display(Encoder3)
display(Encoder4)
display(Encoder5)
display(Encoder6)
display(le)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=-1,
              num_parallel_tree=None, ...)

StandardScaler()

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

### Target

In [42]:
target1=pd.read_parquet(r'data/train/1.회원정보/201807_train_.parquet')
target2=pd.read_parquet(r'data/train/1.회원정보/201808_train_.parquet')
target3=pd.read_parquet(r'data/train/1.회원정보/201809_train_.parquet')
target4=pd.read_parquet(r'data/train/1.회원정보/201810_train_.parquet')
target5=pd.read_parquet(r'data/train/1.회원정보/201811_train_.parquet')
target6=pd.read_parquet(r'data/train/1.회원정보/201812_train_.parquet')

In [43]:
tg_df = pd.concat([
    target1['Segment'],
    target2['Segment'],
    target3['Segment'],
    target4['Segment'],
    target5['Segment'],
    target6['Segment']
])

tg_df = tg_df.reset_index(drop=True).to_frame(name='Segment')
tg_df

        Segment
0             D
1             E
2             C
3             D
4             E
...         ...
2399995       E
2399996       D
2399997       C
2399998       E
2399999       E

[2400000 rows x 1 columns]

In [44]:
# 예측할 데이터를 읽어온다.
df1 = pd.read_csv('(E_NotE)_test.csv')
df1

,이용금액대,할인건수_R3M,방문횟수_앱_R6M,방문일수_PC_R6M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M,정상청구원금_B5M,이용금액_R3M_신용체크,이용개월수_신용_R12M,연속유실적개월수_기본_24M_카드,...,_2순위쇼핑업종_이용금액,이용카드수_신용체크,_3순위쇼핑업종_이용금액,정상입금원금_B0M,_3순위업종_이용금액,청구서발송여부_B0,이용후경과월_신용,_2순위업종_이용금액,이용카드수_신용,_1순위카드이용건수
0,02.50만원+,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,3919,21458,10,5,...,854,2,643,3680,1880,1,0,2713,2,51
1,02.50만원+,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,5723,18681,9,8,...,1154,2,1033,8726,1278,1,0,1321,1,40
2,01.100만원+,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,11267,40758,12,24,...,1178,2,1094,11297,2680,1,1,7271,2,154
3,04.10만원+,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,0,5255,9,5,...,804,1,634,1375,605,1,0,2043,1,105
4,03.30만원+,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1347,16148,12,20,...,774,3,760,3951,1054,1,0,1364,2,52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,09.미사용,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,0,0,0,0,...,0,0,0,0,0,0,12,0,0,-2
599996,05.10만원-,1회 이상,10회 이상,1회 이상,1회 이상,1회 이상,992,3110,10,8,...,0,1,0,205,0,1,0,0,1,4
599997,09.미사용,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,0,0,0,0,...,0,0,0,0,0,0,12,0,0,6
599998,01.100만원+,1회 이상,40회 이상,1회 이상,1회 이상,1회 이상,27335,173263,12,24,...,2208,6,1965,0,4612,1,0,16296,4,185
599999,05.10만원-,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,25,3016,12,24,...,0,2,0,20,0,1,2,0,2,0

In [45]:
X_test = df1.drop('Segment', axis=1, errors='ignore')
X_test = X_test[scaler_columns]

In [46]:
X_test

,이용금액_R3M_신용체크,이용카드수_신용체크,이용카드수_신용,_1순위카드이용건수,청구금액_R6M,청구서발송여부_B0,할인건수_R3M,이용금액_오프라인_R6M,이용건수_오프라인_B0M,_2순위쇼핑업종_이용금액,...,이용후경과월_신용,정상청구원금_B5M,연속유실적개월수_기본_24M_카드,이용개월수_전체_R6M,정상입금원금_B0M,이용금액대,방문횟수_앱_R6M,방문일수_PC_R6M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M
0,21458,2,2,51,22151,1,1회 이상,24747,27,854,...,0,3919,5,5,3680,02.50만원+,1회 이상,1회 이상,1회 이상,1회 이상
1,18681,2,1,40,32878,1,1회 이상,7896,8,1154,...,0,5723,8,6,8726,02.50만원+,1회 이상,1회 이상,1회 이상,1회 이상
2,40758,2,2,154,71867,1,1회 이상,90530,50,1178,...,1,11267,24,6,11297,01.100만원+,1회 이상,1회 이상,1회 이상,1회 이상
3,5255,1,1,105,4986,1,1회 이상,4683,16,804,...,0,0,5,4,1375,04.10만원+,1회 이상,1회 이상,1회 이상,1회 이상
4,16148,3,2,52,10758,1,1회 이상,9920,10,774,...,0,1347,20,6,3951,03.30만원+,1회 이상,1회 이상,1회 이상,1회 이상
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,0,0,0,-2,0,0,1회 이상,0,0,0,...,12,0,0,0,0,09.미사용,1회 이상,1회 이상,1회 이상,1회 이상
599996,3110,1,1,4,2237,1,1회 이상,2331,5,0,...,0,992,8,6,205,05.10만원-,10회 이상,1회 이상,1회 이상,1회 이상
599997,0,0,0,6,0,0,1회 이상,0,0,0,...,12,0,0,0,0,09.미사용,1회 이상,1회 이상,1회 이상,1회 이상
599998,173263,6,4,185,108420,1,1회 이상,89973,66,2208,...,0,27335,24,6,0,01.100만원+,40회 이상,1회 이상,1회 이상,1회 이상
599999,3016,2,2,0,105,1,1회 이상,53,0,0,...,2,25,24,6,20,05.10만원-,1회 이상,1회 이상,1회 이상,1회 이상

In [47]:
# 예측할 데이터 변환
X_test['할인건수_R3M'] = Encoder1.transform(X_test['할인건수_R3M'])
X_test['이용금액대'] = Encoder2.transform(X_test['이용금액대'])
X_test['방문횟수_앱_R6M'] = Encoder3.transform(X_test['방문횟수_앱_R6M'])
X_test['방문일수_PC_R6M'] = Encoder4.transform(X_test['방문일수_PC_R6M'])
X_test['인입횟수_ARS_R6M'] = Encoder5.transform(X_test['인입횟수_ARS_R6M'])
X_test['이용메뉴건수_ARS_R6M'] = Encoder6.transform(X_test['이용메뉴건수_ARS_R6M'])

In [48]:
# 데이터 표준화
scaled_data = scalerX.transform(X_test)
scaled_data

array([[ 0.19460288,  0.66637157,  0.91831146, ...,  0.0641234 ,
         0.17548303,  0.08322662],
       [ 0.07525317,  0.66637157, -0.19290226, ...,  0.0641234 ,
         0.17548303,  0.08322662],
       [ 1.02407691,  0.66637157,  0.91831146, ...,  0.0641234 ,
         0.17548303,  0.08322662],
       ...,
       [-0.72761753, -1.33380024, -1.30411597, ...,  0.0641234 ,
         0.17548303,  0.08322662],
       [ 6.71886742,  4.6667152 ,  3.14073888, ...,  0.0641234 ,
         0.17548303,  0.08322662],
       [-0.59799609,  0.66637157,  0.91831146, ...,  0.0641234 ,
         0.17548303,  0.08322662]])

In [49]:
# 입력데이터를 test_X 변수에 담아준다.
X_text2 = scaled_data

In [50]:
# 예측한다.
y_pred = model6.predict(X_text2)
y_pred_labels = le.inverse_transform(y_pred)
y_pred_labels

array(['E', 'E', 'Not_E', ..., 'E', 'Not_E', 'E'], dtype=object)

In [54]:
# 결과를 붙힌다음 저장한다.
# 예측할 데이터를 다시 불러온다.
result_df = pd.read_csv('test_merged.csv')
result_df['Segment'] = y_pred_labels

In [55]:
result_df2 = result_df[['ID', 'Segment']]

In [56]:
result_df2['Segment'].value_counts()

Segment
E        496271
Not_E    103729
Name: count, dtype: int64

In [78]:
most_common_by_id = result_df2.groupby('ID')['Segment'] \
    .agg(lambda x: x.mode().iloc[0]) \
    .reset_index()

# 컬럼명 확인
most_common_by_id.columns = ['ID', 'Segment']

In [58]:
most_common_by_id

               ID Segment
0      TEST_00000       E
1      TEST_00001       E
2      TEST_00002   Not_E
3      TEST_00003       E
4      TEST_00004       E
...           ...     ...
99995  TEST_99995       E
99996  TEST_99996       E
99997  TEST_99997       E
99998  TEST_99998   Not_E
99999  TEST_99999       E

[100000 rows x 2 columns]

In [71]:
most_common_by_id['Segment'].value_counts()

Segment
E        83917
Not_E    16083
Name: count, dtype: int64

In [60]:
most_common_by_id2 = most_common_by_id[most_common_by_id['Segment'] == 'Not_E']

In [61]:
most_common_by_id.to_csv('data/model3_E,notE.csv', index=False, encoding='utf-8-sig')
print('저장완료')

저장완료

In [62]:
most_common_by_id2.to_csv('data/model3_notE.csv', index=False, encoding='utf-8-sig')
print('저장완료')

저장완료

In [63]:
df2 = pd.read_csv('model3_test_CD(5).csv')

In [64]:
df2

,ID,기준년월,청구금액_R6M,이용금액_일시불_R12M,_1순위카드이용금액,이용금액대,연령,이용금액_R3M_신용체크,이용카드수_신용체크,소지카드수_유효_신용,이용가능여부_해외겸용_본인,수신거부여부_TM,평잔_일시불_3M
0,TEST_00000,201807,22151,49063,13852,50,40대,21458,2,2,1,1,3841
1,TEST_00001,201807,32878,7771,11065,50,60대,18681,2,1,1,0,844
2,TEST_00002,201807,71867,73003,27071,100,40대,40758,2,2,0,0,5606
3,TEST_00003,201807,4986,7421,4827,10,40대,5255,1,1,1,0,1510
4,TEST_00004,201807,10758,10493,8011,30,40대,16148,3,1,1,1,1373
...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,TEST_99995,201812,0,0,0,0,60대,0,0,0,0,0,0
599996,TEST_99996,201812,2237,2631,1231,5,30대,3110,1,1,0,0,237
599997,TEST_99997,201812,0,0,0,0,30대,0,0,1,0,0,0
599998,TEST_99998,201812,108420,423882,63592,100,30대,173263,6,3,1,1,17039
599999,TEST_99999,201812,105,-885,-574,5,30대,3016,2,1,1,0,9

In [65]:
# 1. 'Not_E'인 ID만 필터링
filtered_ids = most_common_by_id[most_common_by_id['Segment'] == 'Not_E']['ID']

# 2. df2에서 해당 ID만 골라오기
final_cd_df = df2[df2['ID'].isin(filtered_ids)]

In [66]:
final_cd_df

,ID,기준년월,청구금액_R6M,이용금액_일시불_R12M,_1순위카드이용금액,이용금액대,연령,이용금액_R3M_신용체크,이용카드수_신용체크,소지카드수_유효_신용,이용가능여부_해외겸용_본인,수신거부여부_TM,평잔_일시불_3M
2,TEST_00002,201807,71867,73003,27071,100,40대,40758,2,2,0,0,5606
10,TEST_00010,201807,12797,29326,7544,10,40대,45764,2,1,1,0,751
12,TEST_00012,201807,63042,86805,24425,50,40대,37849,2,1,0,0,47158
16,TEST_00016,201807,77903,207417,42636,100,30대,51440,2,2,1,0,15431
32,TEST_00032,201807,11525,21910,3885,5,30대,54632,2,1,1,1,2284
...,...,...,...,...,...,...,...,...,...,...,...,...,...
599957,TEST_99957,201812,66775,136892,38644,100,40대,61148,4,2,1,1,14460
599961,TEST_99961,201812,58282,117578,25961,100,40대,30318,1,1,1,0,5505
599982,TEST_99982,201812,129230,447150,70955,100,70대이상,94440,1,1,1,0,26511
599994,TEST_99994,201812,150417,33505,29020,100,40대,31697,1,1,1,0,2810
599998,TEST_99998,201812,108420,423882,63592,100,30대,173263,6,3,1,1,17039

In [67]:
final_cd_df.to_csv('data/test_model3_notE.csv', index=False, encoding='utf-8-sig')

In [79]:
most_common_by_id.loc[most_common_by_id['Segment'] == 'Not_E', 'Segment'] = 'B'

In [80]:
most_common_by_id

               ID Segment
0      TEST_00000       E
1      TEST_00001       E
2      TEST_00002       B
3      TEST_00003       E
4      TEST_00004       E
...           ...     ...
99995  TEST_99995       E
99996  TEST_99996       E
99997  TEST_99997       E
99998  TEST_99998       B
99999  TEST_99999       E

[100000 rows x 2 columns]

In [81]:
most_common_by_id['Segment'].value_counts()

Segment
E    83917
B    16083
Name: count, dtype: int64

In [82]:
most_common_by_id.to_csv('data/prac02.csv', index=False, encoding='utf-8-sig')
print('저장완료')

저장완료