In [1]:
# 기본
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 경고 뜨지 않게 설정
import warnings
warnings.filterwarnings('ignore')

# 그래프 설정
sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False

# 데이터 전처리 알고리즘
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# 학습용과 검증용으로 나누는 함수
from sklearn.model_selection import train_test_split

# 교차 검증
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

# 평가함수
# 분류용
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

# 회귀용
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

# 모델의 최적의 하이퍼 파라미터를 찾기 위한 도구
from sklearn.model_selection import GridSearchCV

# 머신러닝 알고리즘 - 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import VotingClassifier

# 머신러닝 알고리즘 - 회귀
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from sklearn.ensemble import VotingRegressor

# 학습 모델 저장을 위한 라이브러리
import pickle

In [2]:
# 학습이 완료된 모델을 저장할 파일 이름
best_model_path = 'model/best_model_final7.dat'
# 예측 결과를 저장할 파일 이름
prediction_path = 'model/final_prediction7.csv'

In [3]:
with open(best_model_path, 'rb') as fp :
    best_model = pickle.load(fp)
    scalerX = pickle.load(fp)
    Encoder2 = pickle.load(fp)
    Encoder3 = pickle.load(fp)
    Encoder4 = pickle.load(fp)
    Encoder5 = pickle.load(fp)
    Encoder6 = pickle.load(fp)
    Encoder7 = pickle.load(fp)
    Encoder8 = pickle.load(fp)
    Encoder9 = pickle.load(fp)
    Encoder10 = pickle.load(fp)
    Encoder11 = pickle.load(fp)
    Encoder12 = pickle.load(fp)
    Encoder13 = pickle.load(fp)
    Encoder14 = pickle.load(fp)
    SegmentEncoder = pickle.load(fp)

display(best_model)
display(scalerX)
display(Encoder2)
display(Encoder3)
display(Encoder4)
display(Encoder5)
display(Encoder6)
display(Encoder7)
display(Encoder8)
display(Encoder9)
display(Encoder10)
display(Encoder11)
display(Encoder12)
display(Encoder13)
display(Encoder14)
display(SegmentEncoder)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=-1,
              num_parallel_tree=None, ...)

StandardScaler()

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

### Target

In [5]:
target1=pd.read_parquet(r'data/train/1.회원정보/201807_train_.parquet')
target2=pd.read_parquet(r'data/train/1.회원정보/201808_train_.parquet')
target3=pd.read_parquet(r'data/train/1.회원정보/201809_train_.parquet')
target4=pd.read_parquet(r'data/train/1.회원정보/201810_train_.parquet')
target5=pd.read_parquet(r'data/train/1.회원정보/201811_train_.parquet')
target6=pd.read_parquet(r'data/train/1.회원정보/201812_train_.parquet')

In [6]:
tg_df = pd.concat([
    target1['Segment'],
    target2['Segment'],
    target3['Segment'],
    target4['Segment'],
    target5['Segment'],
    target6['Segment']
])

tg_df = tg_df.reset_index(drop=True).to_frame(name='Segment')
tg_df

        Segment
0             D
1             E
2             C
3             D
4             E
...         ...
2399995       E
2399996       D
2399997       C
2399998       E
2399999       E

[2400000 rows x 1 columns]

In [7]:
# 예측할 데이터를 읽어온다.
df1 = pd.read_csv('test_VIF3.csv')
df1

,이용금액_R3M_신용체크,소지카드수_이용가능_신용,Life_Stage,RV전환가능여부,자발한도감액횟수_R12M,한도증액횟수_R12M,카드론동의여부,한도심사요청건수,최대이용금액_할부_R12M,이용금액_일시불_R12M,...,연체입금원금_B0M,이용금액대,혜택수혜금액,할인건수_R3M,대표청구지고객주소구분코드,대표결제방법코드,월중평잔_일시불,방문횟수_PC_R6M,이용메뉴건수_ARS_R6M,인입횟수_ARS_R6M
0,21458,2,자녀성장(1),Z,0회,0회,N,0회,0,49063,...,2814,02.50만원+,56,1회 이상,미확인,자동이체,5187,1회 이상,1회 이상,1회 이상
1,18681,1,자녀독립기,N,0회,0회,Y,0회,6547,7771,...,918,02.50만원+,0,1회 이상,미확인,자동이체,865,1회 이상,1회 이상,1회 이상
2,40758,2,자녀성장(1),Z,0회,1회이상,Y,0회,16178,73003,...,222,01.100만원+,50,1회 이상,미확인,자동이체,5591,1회 이상,1회 이상,1회 이상
3,5255,1,자녀성장(1),Z,0회,0회,Y,0회,2628,7421,...,0,04.10만원+,1,1회 이상,주거지,자동이체,1545,1회 이상,1회 이상,1회 이상
4,16148,1,자녀성장(1),Z,0회,0회,Y,0회,4082,10493,...,0,03.30만원+,0,1회 이상,주거지,자동이체,1462,1회 이상,1회 이상,1회 이상
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,0,0,노년생활,NaN,0회,0회,Y,0회,0,0,...,0,09.미사용,0,1회 이상,회사,자동이체,0,1회 이상,1회 이상,1회 이상
599996,3110,1,자녀출산기,Z,0회,0회,Y,0회,0,2631,...,0,05.10만원-,49,1회 이상,주거지,자동이체,256,1회 이상,1회 이상,1회 이상
599997,0,1,자녀성장(1),Z,0회,0회,Y,0회,0,0,...,0,09.미사용,0,1회 이상,미확인,자동이체,0,1회 이상,1회 이상,1회 이상
599998,173263,3,가족구축기,Z,0회,0회,Y,0회,9183,423882,...,16746,01.100만원+,0,1회 이상,미확인,자동이체,14005,1회 이상,1회 이상,1회 이상
599999,3016,1,자녀출산기,Z,0회,0회,Y,0회,0,-885,...,0,05.10만원-,0,1회 이상,주거지,자동이체,10,1회 이상,1회 이상,1회 이상

In [8]:
# 예측할 데이터 변환
df1['RV전환가능여부'] = Encoder2.transform(df1['RV전환가능여부'])
df1['자발한도감액횟수_R12M'] = Encoder3.transform(df1['자발한도감액횟수_R12M'])
df1['한도증액횟수_R12M'] = Encoder4.transform(df1['한도증액횟수_R12M'])
df1['카드론동의여부'] = Encoder5.transform(df1['카드론동의여부'])
df1['한도심사요청건수'] = Encoder6.transform(df1['한도심사요청건수'])
df1['이용금액대'] = Encoder7.transform(df1['이용금액대'])
df1['할인건수_R3M'] = Encoder8.transform(df1['할인건수_R3M'])
df1['대표결제방법코드'] = Encoder9.transform(df1['대표결제방법코드'])
df1['방문횟수_PC_R6M'] = Encoder10.transform(df1['방문횟수_PC_R6M'])
df1['이용메뉴건수_ARS_R6M'] = Encoder11.transform(df1['이용메뉴건수_ARS_R6M'])
df1['인입횟수_ARS_R6M'] = Encoder12.transform(df1['인입횟수_ARS_R6M'])
df1['대표청구지고객주소구분코드'] = Encoder13.transform(df1['대표청구지고객주소구분코드'])
df1['Life_Stage'] = Encoder14.transform(df1['Life_Stage'])

In [9]:
# 데이터 표준화
scaled_data = scalerX.transform(df1)
scaled_data

array([[ 0.19460288,  1.36626236,  0.22559285, ..., -0.09507879,
         0.08322662,  0.17548303],
       [ 0.07525317, -0.24605525, -0.33130048, ..., -0.09507879,
         0.08322662,  0.17548303],
       [ 1.02407691,  1.36626236,  0.22559285, ..., -0.09507879,
         0.08322662,  0.17548303],
       ...,
       [-0.72761753, -0.24605525,  0.22559285, ..., -0.09507879,
         0.08322662,  0.17548303],
       [ 6.71886742,  2.97857997, -2.00198046, ..., -0.09507879,
         0.08322662,  0.17548303],
       [-0.59799609, -0.24605525,  1.3393795 , ..., -0.09507879,
         0.08322662,  0.17548303]])

In [10]:
# 입력데이터를 test_X 변수에 담아준다.
test_X = scaled_data

In [11]:
# 예측한다.
y_pred = best_model.predict(test_X)
y_pred_labels = SegmentEncoder.inverse_transform(y_pred)
y_pred_labels

array(['E', 'E', 'D', ..., 'E', 'C', 'E'], dtype=object)

In [12]:
# 결과를 붙힌다음 저장한다.
# 예측할 데이터를 다시 불러온다.
result_df = pd.read_csv('test_merged.csv')
result_df['Segment'] = y_pred_labels

In [ ]:
result_df.to_csv(prediction_path, index=False, encoding='utf-8-sig')
print('저장완료')

In [34]:
# 조건으로 필터링 먼저
filtered_df = result_df[result_df['기준년월'] == 201812]

# 원하는 컬럼 선택
result_df2 = filtered_df[['ID', 'Segment']]

In [13]:
result_df2 = result_df[['ID', 'Segment']]

In [14]:
result_df2['Segment'].value_counts()

Segment
E    502051
D     74481
C     23426
A        36
B         6
Name: count, dtype: int64

In [36]:
result_df3 = result_df2[['ID', 'Segment']]
result_df3

                ID Segment
500000  TEST_00000       E
500001  TEST_00001       E
500002  TEST_00002       D
500003  TEST_00003       E
500004  TEST_00004       E
...            ...     ...
599995  TEST_99995       E
599996  TEST_99996       E
599997  TEST_99997       E
599998  TEST_99998       C
599999  TEST_99999       E

[100000 rows x 2 columns]

In [37]:
result_df3['Segment'].value_counts()

Segment
E    83852
D    12170
C     3976
A        1
B        1
Name: count, dtype: int64

In [38]:
result_df3.to_csv('data/result06.csv', index=False, encoding='utf-8-sig')
print('저장완료')

저장완료

In [15]:
most_common_by_id = result_df2.groupby('ID')['Segment'] \
    .agg(lambda x: x.mode().iloc[0]) \
    .reset_index()

# 컬럼명 확인
most_common_by_id.columns = ['ID', 'Segment']

In [15]:
most_common_by_id

               ID Segment
0      TEST_00000       E
1      TEST_00001       E
2      TEST_00002       D
3      TEST_00003       E
4      TEST_00004       E
...           ...     ...
99995  TEST_99995       E
99996  TEST_99996       E
99997  TEST_99997       E
99998  TEST_99998       C
99999  TEST_99999       E

[100000 rows x 2 columns]

In [16]:
most_common_by_id['Segment'].value_counts()

Segment
E    83193
D    12764
C     4039
A        3
B        1
Name: count, dtype: int64

In [18]:
most_common_by_id.to_csv('data/result09.csv', index=False, encoding='utf-8-sig')
print('저장완료')

저장완료