In [18]:
# 기본
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 경고 뜨지 않게 설정
import warnings
warnings.filterwarnings('ignore')

# 그래프 설정
sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False

# 데이터 전처리 알고리즘
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# 학습용과 검증용으로 나누는 함수
from sklearn.model_selection import train_test_split

# 교차 검증
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

# 평가함수
# 분류용
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

# 회귀용
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

# 모델의 최적의 하이퍼 파라미터를 찾기 위한 도구
from sklearn.model_selection import GridSearchCV

# 머신러닝 알고리즘 - 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import VotingClassifier

# 머신러닝 알고리즘 - 회귀
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from sklearn.ensemble import VotingRegressor

# 학습 모델 저장을 위한 라이브러리
import pickle

In [19]:
# 학습이 완료된 모델을 저장할 파일 이름
best_model_path = 'model/best_model_final.dat'
# 예측 결과를 저장할 파일 이름
prediction_path = 'model/final_prediction.csv'

In [32]:
with open(best_model_path, 'rb') as fp :
    best_model = pickle.load(fp)
    scalerX = pickle.load(fp)
    SegmentEncoder = pickle.load(fp)

display(best_model)
display(scalerX)
display(SegmentEncoder)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=-1,
              num_parallel_tree=None, ...)

StandardScaler()

LabelEncoder()

In [33]:
# 예측할 데이터를 읽어온다.
df1 = pd.read_parquet('pca_test.parquet')
df1

,p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,...,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25
0,5449.770391,-15457.519040,7975.048602,-2971.418102,-1137.004767,4011.962178,11551.144025,3357.707117,-2924.619991,-1328.630772,...,-3675.470317,89.699954,192.708076,-2603.045310,6486.179111,5040.282733,884.032817,-776.952494,2111.313036,-694.188774
1,-39956.605754,26232.031298,1163.543109,-8719.802046,-6359.839502,-9991.102021,-4302.131559,15137.268711,10291.412366,815.171481,...,-2610.468074,1837.496243,2076.203376,2799.656589,-765.383540,2007.854072,1813.109968,-817.880168,2123.054119,213.050147
2,91343.368173,20400.129674,49117.164568,18297.225678,-3701.289740,445.182612,-8089.748597,9430.604081,-8090.458230,-63.631268,...,1316.920665,569.088380,-2300.244976,-2180.985710,1976.296387,1498.115258,617.151610,557.424181,281.863780,741.645539
3,-60622.721464,-2779.211139,172.147096,-1520.579234,494.335648,-2245.292748,-2498.491928,4213.196662,2446.223072,-925.403801,...,253.566125,-410.776261,611.909126,677.146880,1175.953033,339.431785,63.668976,-470.056671,-770.600264,-332.992309
4,-48203.789429,188.499776,8676.875460,-8345.019526,-4152.234195,-8421.964779,-2943.931762,4537.336519,1748.248578,-1903.155041,...,-1117.081463,114.225258,538.235135,1567.426466,490.377157,422.267112,1492.421103,482.156591,1349.365467,38.372575
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,-75126.065175,-3705.200634,-3607.179077,706.459174,88.174569,-1576.755827,-1673.193119,66.734157,-311.373311,-693.622316,...,115.492325,108.838596,-99.179096,52.185987,25.174890,-525.887342,-346.753069,-283.930403,81.819950,-374.758094
599996,-69393.140789,-2960.239476,-1778.824783,-236.728825,-975.862235,-3279.293119,-1335.075258,1572.949261,733.136012,-850.853994,...,871.562358,-175.810517,1104.853614,-301.709977,-972.853633,-1086.022765,239.215755,-739.975975,154.691256,-982.463430
599997,-75112.821114,-3689.619067,-3601.622684,707.283464,73.604369,-1557.581357,-1663.292209,80.980196,-310.201058,-691.082182,...,138.351906,107.394462,-24.579710,64.067763,53.626928,-627.955001,-311.882147,-294.117050,93.183060,-326.612659
599998,429765.434690,-147776.679200,-45333.927642,-79709.429139,-51300.598740,-19337.740212,4039.117750,2184.738303,42456.455268,14162.848870,...,-1217.003942,16497.104569,-3638.910661,1245.666898,1028.243274,-1718.329770,3274.497209,1430.706916,-5689.597895,-9427.709388
599999,-75893.920986,-2809.803648,-2116.575575,-2290.488750,-1896.693339,-8176.913601,-2188.368175,1493.328056,-882.728957,-2995.477899,...,398.332192,98.077493,211.783711,128.589831,-389.280642,-674.624629,416.068503,6.186952,120.258678,212.610634

In [34]:
# 데이터 표준화
scaled_data = scalerX.transform(df1)
scaled_data

array([[ 5.45284873e-02, -4.67495726e-01,  4.40625770e-01, ...,
        -5.19731611e-01,  1.53816865e+00, -5.07740403e-01],
       [-3.96937074e-01,  7.95002598e-01,  6.43392812e-02, ...,
        -5.47120444e-01,  1.54672086e+00,  1.55818175e-01],
       [ 9.08549544e-01,  6.18393209e-01,  2.71343057e+00, ...,
         3.73234365e-01,  2.05598003e-01,  5.42435193e-01],
       ...,
       [-7.46487552e-01, -1.11124552e-01, -1.98901717e-01, ...,
        -1.96617731e-01,  6.81629863e-02, -2.38893599e-01],
       [ 4.27340534e+00, -4.47456025e+00, -2.50431019e+00, ...,
         9.57635895e-01, -4.14401407e+00, -6.89547618e+00],
       [-7.54253855e-01, -8.44808135e-02, -1.16863588e-01, ...,
         4.34595543e-03,  8.78848630e-02,  1.55496713e-01]])

In [35]:
# 입력데이터를 test_X 변수에 담아준다.
test_X = scaled_data

In [37]:
# 예측한다.
y_pred = best_model.predict(test_X)
y_pred_labels = SegmentEncoder.inverse_transform(y_pred)
y_pred_labels

array(['E', 'E', 'D', ..., 'E', 'C', 'E'], dtype=object)

In [38]:
# 결과를 붙힌다음 저장한다.
# 예측할 데이터를 다시 불러온다.
result_df = pd.read_csv('test_merged.csv')
result_df['Segment'] = y_pred_labels
result_df.to_csv(prediction_path, index=False, encoding='utf-8-sig')
print('저장완료')

저장완료

In [57]:
# 조건으로 필터링 먼저
filtered_df = result_df[result_df['기준년월'] == 201812]

# 원하는 컬럼 선택
result_df2 = filtered_df[['ID', '기준년월', 'Segment']]

In [58]:
result_df2['Segment'].value_counts()

Segment
E    82800
D    12719
C     4480
A        1
Name: count, dtype: int64

In [59]:
result_df3 = result_df2[['ID', 'Segment']]

In [60]:
result_df3.to_csv('data/result04.csv', index=False, encoding='utf-8-sig')
print('저장완료')

저장완료

In [42]:
most_common_by_id = result_df2.groupby('ID')['Segment'] \
    .agg(lambda x: x.mode().iloc[0]) \
    .reset_index()

# 컬럼명 확인
most_common_by_id.columns = ['ID', 'Segment']

In [43]:
most_common_by_id

               ID Segment
0      TEST_00000       E
1      TEST_00001       E
2      TEST_00002       D
3      TEST_00003       E
4      TEST_00004       E
...           ...     ...
99995  TEST_99995       E
99996  TEST_99996       E
99997  TEST_99997       E
99998  TEST_99998       C
99999  TEST_99999       E

[100000 rows x 2 columns]

In [48]:
most_common_by_id['Segment'].value_counts()

Segment
E    82545
D    13037
C     4416
A        2
Name: count, dtype: int64

In [44]:
most_common_by_id.to_csv('data/result01.csv', index=False, encoding='utf-8-sig')
print('저장완료')

저장완료