In [1]:
# 기본
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 경고 뜨지 않게 설정
import warnings
warnings.filterwarnings('ignore')

# 그래프 설정
sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False

# 데이터 전처리 알고리즘
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# 학습용과 검증용으로 나누는 함수
from sklearn.model_selection import train_test_split

# 교차 검증
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

# 평가함수
# 분류용
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

# 회귀용
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

# 모델의 최적의 하이퍼 파라미터를 찾기 위한 도구
from sklearn.model_selection import GridSearchCV

# 머신러닝 알고리즘 - 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import VotingClassifier

# 머신러닝 알고리즘 - 회귀
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from sklearn.ensemble import VotingRegressor

# 학습 모델 저장을 위한 라이브러리
import pickle

In [2]:
# 학습이 완료된 모델을 저장할 파일 이름
best_model_path = 'model/best_model_final14.dat'

In [3]:
with open(best_model_path, 'rb') as fp :
    model6 = pickle.load(fp)
    scalerX = pickle.load(fp)
    scaler_columns = pickle.load(fp)
    Encoder1 = pickle.load(fp)
    Encoder2 = pickle.load(fp)
    Encoder3 = pickle.load(fp)
    Encoder4 = pickle.load(fp)
    Encoder5 = pickle.load(fp)
    Encoder6 = pickle.load(fp)
    Encoder7 = pickle.load(fp)
    Encoder8 = pickle.load(fp)
    Encoder9 = pickle.load(fp)
    le = pickle.load(fp)
    
display(model6)
display(scalerX)
display(scaler_columns)
display(Encoder1)
display(Encoder2)
display(Encoder3)
display(Encoder4)
display(Encoder5)
display(Encoder6)
display(Encoder7)
display(Encoder8)
display(Encoder9)
display(le)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=-1,
              num_parallel_tree=None, ...)

StandardScaler()

['카드이용한도금액_B2M',
 '카드이용한도금액_B1M',
 '카드이용한도금액',
 'CA한도금액',
 '_1순위카드이용금액',
 '연령',
 'Life_Stage',
 '거주시도명',
 '연회비발생카드수_B0M',
 '이용금액_할부_무이자_R12M',
 '이용금액_일시불_R12M',
 '쇼핑_도소매_이용금액',
 '최대이용금액_일시불_R12M',
 '이용금액_할부_R12M',
 '할부금액_무이자_3M_R12M',
 '이용금액_오프라인_R6M',
 '할부금액_3M_R12M',
 '이용금액_오프라인_B0M',
 '이용금액_오프라인_R3M',
 '_2순위쇼핑업종_이용금액',
 '_1순위업종_이용금액',
 '_3순위업종_이용금액',
 '정상청구원금_B5M',
 '정상입금원금_B5M',
 '정상입금원금_B2M',
 '정상입금원금_B0M',
 '정상청구원금_B2M',
 '정상청구원금_B0M',
 '청구금액_R6M',
 '청구금액_R3M',
 '청구금액_B0',
 '포인트_마일리지_환산_B0M',
 '마일_적립포인트_R3M',
 '할인건수_R3M',
 '평잔_일시불_해외_6M',
 '방문횟수_앱_R6M',
 '방문횟수_PC_R6M',
 '방문일수_PC_R6M',
 '인입횟수_ARS_R6M']

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

### Target

In [4]:
target1=pd.read_parquet(r'data/train/1.회원정보/201807_train_.parquet')
target2=pd.read_parquet(r'data/train/1.회원정보/201808_train_.parquet')
target3=pd.read_parquet(r'data/train/1.회원정보/201809_train_.parquet')
target4=pd.read_parquet(r'data/train/1.회원정보/201810_train_.parquet')
target5=pd.read_parquet(r'data/train/1.회원정보/201811_train_.parquet')
target6=pd.read_parquet(r'data/train/1.회원정보/201812_train_.parquet')

In [5]:
tg_df = pd.concat([
    target1['Segment'],
    target2['Segment'],
    target3['Segment'],
    target4['Segment'],
    target5['Segment'],
    target6['Segment']
])

tg_df = tg_df.reset_index(drop=True).to_frame(name='Segment')
tg_df

        Segment
0             D
1             E
2             C
3             D
4             E
...         ...
2399995       E
2399996       D
2399997       C
2399998       E
2399999       E

[2400000 rows x 1 columns]

In [6]:
# 예측할 데이터를 읽어온다.
df1 = pd.read_parquet('data/Seleted(A_B_notAB)_delecteE_all_test.parquet')
df1

,기준년월,ID,카드이용한도금액_B2M,카드이용한도금액_B1M,카드이용한도금액,CA한도금액,_1순위카드이용금액,연령,Life_Stage,거주시도명,...,청구금액_R3M,청구금액_B0,포인트_마일리지_환산_B0M,마일_적립포인트_R3M,할인건수_R3M,평잔_일시불_해외_6M,방문횟수_앱_R6M,방문횟수_PC_R6M,방문일수_PC_R6M,인입횟수_ARS_R6M
0,201807,TEST_00000,50006,49999,50902,18131,13852,40대,자녀성장(1),경기,...,11441,4931,148,2532,1회 이상,384,1회 이상,1회 이상,1회 이상,1회 이상
1,201807,TEST_00001,50003,50000,50080,16819,11065,60대,자녀독립기,인천,...,20522,10152,0,0,1회 이상,0,1회 이상,1회 이상,1회 이상,1회 이상
2,201807,TEST_00002,100056,100053,100045,30505,27071,40대,자녀성장(1),경기,...,50508,13223,0,0,1회 이상,0,1회 이상,1회 이상,1회 이상,1회 이상
3,201807,TEST_00003,19693,21035,18508,6402,4827,40대,자녀성장(1),인천,...,4604,2112,0,0,1회 이상,0,1회 이상,1회 이상,1회 이상,1회 이상
4,201807,TEST_00004,3924,4291,4033,0,8011,40대,자녀성장(1),경기,...,6788,4406,0,0,1회 이상,0,1회 이상,1회 이상,1회 이상,1회 이상
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,201812,TEST_99995,0,0,0,0,0,60대,노년생활,경기,...,0,0,0,0,1회 이상,0,1회 이상,1회 이상,1회 이상,1회 이상
599996,201812,TEST_99996,49990,50008,49025,17876,1231,30대,자녀출산기,서울,...,1256,359,0,0,1회 이상,0,10회 이상,1회 이상,1회 이상,1회 이상
599997,201812,TEST_99997,30004,30011,29996,13332,0,30대,자녀성장(1),경남,...,0,0,0,0,1회 이상,0,1회 이상,1회 이상,1회 이상,1회 이상
599998,201812,TEST_99998,37139,37999,42610,17362,63592,30대,가족구축기,경남,...,48141,21273,0,0,1회 이상,240,40회 이상,1회 이상,1회 이상,1회 이상
599999,201812,TEST_99999,79148,78043,86444,30242,-574,30대,자녀출산기,경기,...,56,18,0,0,1회 이상,0,1회 이상,1회 이상,1회 이상,1회 이상

In [7]:
notE = pd.read_csv('model3_E,notE(2).csv')
notE

               ID Segment
0      TEST_00000       E
1      TEST_00001       E
2      TEST_00002       E
3      TEST_00003       E
4      TEST_00004       E
...           ...     ...
99995  TEST_99995       E
99996  TEST_99996       E
99997  TEST_99997       E
99998  TEST_99998   Not_E
99999  TEST_99999       E

[100000 rows x 2 columns]

In [8]:
# 1. 'Not_E'인 ID만 필터링
filtered_ids1 = notE[notE['Segment'] == 'Not_E']['ID']

# 2. df2에서 해당 ID만 골라오기
Xtest_df = df1[df1['ID'].isin(filtered_ids1)]

In [9]:
X_test = Xtest_df.drop(columns=['기준년월','ID'])
X_test = X_test[scaler_columns]

In [10]:
X_test

,카드이용한도금액_B2M,카드이용한도금액_B1M,카드이용한도금액,CA한도금액,_1순위카드이용금액,연령,Life_Stage,거주시도명,연회비발생카드수_B0M,이용금액_할부_무이자_R12M,...,청구금액_R3M,청구금액_B0,포인트_마일리지_환산_B0M,마일_적립포인트_R3M,할인건수_R3M,평잔_일시불_해외_6M,방문횟수_앱_R6M,방문횟수_PC_R6M,방문일수_PC_R6M,인입횟수_ARS_R6M
10,30003,30007,50274,25451,7544,40대,자녀성장(1),서울,0개,0,...,6847,0,0,0,1회 이상,0,1회 이상,1회 이상,1회 이상,1회 이상
16,21749,21313,19300,10392,42636,30대,자녀출산기,경기,0개,3784,...,41328,12194,227,3663,1회 이상,545,1회 이상,1회 이상,1회 이상,1회 이상
32,62407,65139,49727,18118,3885,30대,자녀출산기,부산,0개,0,...,4259,769,0,0,1회 이상,0,1회 이상,1회 이상,1회 이상,1회 이상
34,210408,200875,199757,57471,28028,50대,자녀성장(2),경기,0개,4330,...,56962,15282,103,2127,1회 이상,0,1회 이상,1회 이상,1회 이상,1회 이상
37,38625,38160,43647,14970,49528,60대,노년생활,대전,0개,14555,...,26337,12512,0,0,1회 이상,0,1회 이상,1회 이상,1회 이상,10회 이상
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599947,194680,170672,180204,49064,41465,40대,자녀성장(1),대구,0개,8901,...,38929,10998,0,0,30회 이상,267,60회 이상,1회 이상,1회 이상,1회 이상
599957,50010,50015,52373,19032,38644,40대,자녀성장(1),대전,0개,2213,...,28638,14349,0,0,1회 이상,0,40회 이상,40회 이상,30회 이상,1회 이상
599961,37379,36138,45661,18298,25961,40대,자녀성장(2),경기,0개,0,...,26095,7195,0,0,1회 이상,0,1회 이상,1회 이상,1회 이상,1회 이상
599982,197112,197044,199981,58290,70955,70대이상,노년생활,경기,0개,0,...,65023,11710,229,2501,1회 이상,1497,1회 이상,1회 이상,1회 이상,1회 이상
599998,37139,37999,42610,17362,63592,30대,가족구축기,경남,0개,12509,...,48141,21273,0,0,1회 이상,240,40회 이상,1회 이상,1회 이상,1회 이상

In [11]:
# 예측할 데이터 변환
X_test['연령'] = Encoder1.transform(X_test['연령'])
X_test['Life_Stage'] = Encoder2.transform(X_test['Life_Stage'])
X_test['거주시도명'] = Encoder3.transform(X_test['거주시도명'])
X_test['연회비발생카드수_B0M'] = Encoder4.transform(X_test['연회비발생카드수_B0M'])
X_test['할인건수_R3M'] = Encoder5.transform(X_test['할인건수_R3M'])
X_test['방문횟수_앱_R6M'] = Encoder6.transform(X_test['방문횟수_앱_R6M'])
X_test['방문횟수_PC_R6M'] = Encoder7.transform(X_test['방문횟수_PC_R6M'])
X_test['방문일수_PC_R6M'] = Encoder8.transform(X_test['방문일수_PC_R6M'])
X_test['인입횟수_ARS_R6M'] = Encoder9.transform(X_test['인입횟수_ARS_R6M'])

In [12]:
# 데이터 표준화
scaled_data = scalerX.transform(X_test)
scaled_data

array([[-0.64758329, -0.64511234, -0.24589802, ..., -0.11592244,
         0.07677258,  0.22083044],
       [-0.81036947, -0.81612622, -0.846779  , ..., -0.11592244,
         0.07677258,  0.22083044],
       [-0.00850852,  0.04594584, -0.25650956, ..., -0.11592244,
         0.07677258,  0.22083044],
       ...,
       [-0.50211312, -0.52451352, -0.33538804, ..., -0.11592244,
         0.07677258,  0.22083044],
       [ 2.64815634,  2.64056125,  2.65834712, ..., -0.11592244,
         0.07677258,  0.22083044],
       [-0.50684642, -0.48790703, -0.394576  , ..., -0.11592244,
         0.07677258,  0.22083044]])

In [13]:
# 입력데이터를 test_X 변수에 담아준다.
X_text2 = scaled_data

In [14]:
# 예측한다.
y_pred = model6.predict(X_text2)
y_pred_labels = le.inverse_transform(y_pred)
y_pred_labels

array(['notAB', 'notAB', 'notAB', ..., 'notAB', 'notAB', 'notAB'],
      dtype=object)

In [15]:
# 결과를 붙힌다음 저장한다.
# 예측할 데이터를 다시 불러온다.
result_df = Xtest_df
result_df['Segment'] = y_pred_labels

In [16]:
result_df2 = result_df[['ID', 'Segment']]

In [17]:
result_df2['Segment'].value_counts()

Segment
notAB    100119
A            94
B             5
Name: count, dtype: int64

In [18]:
most_common_by_id = result_df2.groupby('ID')['Segment'] \
    .agg(lambda x: x.mode().iloc[0]) \
    .reset_index()

# 컬럼명 확인
most_common_by_id.columns = ['ID', 'Segment']

In [19]:
most_common_by_id

               ID Segment
0      TEST_00010   notAB
1      TEST_00016   notAB
2      TEST_00032   notAB
3      TEST_00034   notAB
4      TEST_00037   notAB
...           ...     ...
16698  TEST_99947   notAB
16699  TEST_99957   notAB
16700  TEST_99961   notAB
16701  TEST_99982   notAB
16702  TEST_99998   notAB

[16703 rows x 2 columns]

In [20]:
most_common_by_id['Segment'].value_counts()

Segment
notAB    16688
A           14
B            1
Name: count, dtype: int64

In [21]:
most_common_by_id2 = most_common_by_id[most_common_by_id['Segment'] == 'notAB']

In [22]:
most_common_by_id2

               ID Segment
0      TEST_00010   notAB
1      TEST_00016   notAB
2      TEST_00032   notAB
3      TEST_00034   notAB
4      TEST_00037   notAB
...           ...     ...
16698  TEST_99947   notAB
16699  TEST_99957   notAB
16700  TEST_99961   notAB
16701  TEST_99982   notAB
16702  TEST_99998   notAB

[16688 rows x 2 columns]

In [23]:
most_common_by_id.to_csv('data/model3_A,B,notAB(2).csv', index=False, encoding='utf-8-sig')
print('저장완료')

저장완료

In [24]:
most_common_by_id2.to_csv('data/model3_notAB(2).csv', index=False, encoding='utf-8-sig')
print('저장완료')

저장완료

In [60]:
df2 = pd.read_csv('(C_D)_VIF_test(2).csv')

In [43]:
df2

,이용금액_R3M_신용체크,_1순위카드이용금액,이용카드수_신용체크,Life_Stage,이용개월수_신용_R12M,이용금액_일시불_R6M,이용후경과월_신판,이용건수_신용_R12M,이용후경과월_신용,이용금액_오프라인_B0M,...,정상입금원금_B2M,이용개월수_전체_R6M,청구금액_R6M,청구서발송여부_B0,할인건수_R3M,할인건수_B0M,방문횟수_앱_R6M,방문횟수_PC_R6M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M
0,21458,13852,2,자녀성장(1),10,26595,0,150,0,9877,...,1172,5,22151,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
1,18681,11065,2,자녀독립기,9,-7578,0,28,0,4006,...,4509,6,32878,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
2,40758,27071,2,자녀성장(1),12,48483,1,650,1,11298,...,11366,6,71867,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
3,5255,4827,1,자녀성장(1),9,403,0,361,0,976,...,875,4,4986,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
4,16148,8011,3,자녀성장(1),12,1238,0,227,0,4017,...,1618,6,10758,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,0,0,0,노년생활,0,0,12,0,12,0,...,0,0,0,0,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
599996,3110,1231,1,자녀출산기,10,3,0,7,0,407,...,252,6,2237,1,1회 이상,1회 이상,10회 이상,1회 이상,1회 이상,1회 이상
599997,0,0,0,자녀성장(1),0,0,12,0,12,0,...,0,0,0,0,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
599998,173263,63592,6,가족구축기,12,133431,0,933,0,15388,...,2751,6,108420,1,1회 이상,1회 이상,40회 이상,1회 이상,1회 이상,1회 이상
599999,3016,-574,2,자녀출산기,12,-4731,2,40,2,8,...,18,6,105,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상

In [45]:
# 1. 'Not_E'인 ID만 필터링
filtered_ids = most_common_by_id[most_common_by_id['Segment'] == 'notAB']['ID']

# 2. df2에서 해당 ID만 골라오기
final_abnotab_df = df2[df2['ID'].isin(filtered_ids)]

KeyError: 'ID'

In [39]:
filtered_ids

0        TEST_00002
1        TEST_00010
2        TEST_00012
3        TEST_00016
4        TEST_00032
            ...
16078    TEST_99957
16079    TEST_99961
16080    TEST_99982
16081    TEST_99994
16082    TEST_99998
Name: ID, Length: 16083, dtype: object

In [40]:
final_abnotab_df

               ID Segment
2      TEST_00002   notAB
10     TEST_00010   notAB
12     TEST_00012   notAB
16     TEST_00016   notAB
32     TEST_00032   notAB
...           ...     ...
99957  TEST_99957   notAB
99961  TEST_99961   notAB
99982  TEST_99982   notAB
99994  TEST_99994   notAB
99998  TEST_99998   notAB

[16068 rows x 2 columns]

In [41]:
final_abnotab_df.to_csv('data/test_model3_notAB.csv', index=False, encoding='utf-8-sig')