In [ ]:
# 기본
import pandas as pd  # 데이터프레임 처리
import numpy as np  # 수치 계산
import matplotlib.pyplot as plt  # 데이터 시각화
import seaborn as sns  # 고급 시각화

# 경고 뜨지 않게 설정
import warnings  # 경고 무시 설정
warnings.filterwarnings('ignore')


# 데이터 전처리 알고리즘
from sklearn.preprocessing import LabelEncoder  # 범주형 → 숫자형
from sklearn.preprocessing import StandardScaler  # 데이터 정규화

# 학습용과 검증용으로 나누는 함수
from sklearn.model_selection import train_test_split  # 데이터 분할

# 교차 검증
from sklearn.model_selection import cross_val_score  # 교차검증 점수
from sklearn.model_selection import cross_validate  # 교차검증 상세결과
from sklearn.model_selection import KFold  # K겹 검증
from sklearn.model_selection import StratifiedKFold  # 라벨 비율 유지한 K겹

# 평가함수
# 분류용
from sklearn.metrics import accuracy_score  # 정확도
from sklearn.metrics import precision_score  # 정밀도
from sklearn.metrics import recall_score  # 재현율
from sklearn.metrics import f1_score  # F1 점수
from sklearn.metrics import roc_auc_score  # ROC AUC

# 회귀용
from sklearn.metrics import r2_score  # R² 결정계수
from sklearn.metrics import mean_squared_error  # 평균제곱오차

# 모델의 최적의 하이퍼 파라미터를 찾기 위한 도구
from sklearn.model_selection import GridSearchCV  # 그리드서치

# 머신러닝 알고리즘 - 분류
from sklearn.neighbors import KNeighborsClassifier  # K-최근접 이웃
from sklearn.linear_model import LogisticRegression  # 로지스틱 회귀
from sklearn.svm import SVC  # 서포트 벡터 머신
from sklearn.tree import DecisionTreeClassifier  # 결정 트리
from sklearn.ensemble import RandomForestClassifier  # 랜덤 포레스트
from sklearn.ensemble import AdaBoostClassifier  # 아다부스트
from sklearn.ensemble import GradientBoostingClassifier  # 그래디언트 부스팅
from lightgbm import LGBMClassifier  # LightGBM 분류기
from xgboost import XGBClassifier  # XGBoost 분류기
from sklearn.ensemble import VotingClassifier  # 투표 기반 앙상블

# 머신러닝 알고리즘 - 회귀
from sklearn.neighbors import KNeighborsRegressor  # K-최근접 회귀
from sklearn.linear_model import LinearRegression  # 선형 회귀
from sklearn.linear_model import Ridge  # 릿지 회귀
from sklearn.linear_model import Lasso  # 라쏘 회귀
from sklearn.linear_model import ElasticNet  # 엘라스틱넷 회귀
from sklearn.svm import SVR  # 서포트 벡터 회귀
from sklearn.tree import DecisionTreeRegressor  # 결정 트리 회귀
from sklearn.ensemble import RandomForestRegressor  # 랜덤 포레스트 회귀
from sklearn.ensemble import AdaBoostRegressor  # 아다부스트 회귀
from sklearn.ensemble import GradientBoostingRegressor  # 그래디언트 부스팅 회귀
from lightgbm import LGBMRegressor  # LightGBM 회귀
from xgboost import XGBRegressor  # XGBoost 회귀
from sklearn.ensemble import VotingRegressor  # 투표 기반 회귀 앙상블

# 차원 축소
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

# 학습 모델 저장을 위한 라이브러리
import pickle

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

### 데이터 준비

In [ ]:
# parquet 파일 데이터를 읽어온다.
train_df = pd.read_parquet('/content/drive/MyDrive/공유문서함/all_df07.parquet')

In [ ]:
train_df

,index,기준년월,ID,소지카드수_이용가능_신용,소지카드수_유효_신용,이용가능여부_해외겸용_본인,보유여부_해외겸용_본인,수신거부여부_TM,수신거부여부_메일,수신거부여부_DM,...,월중평잔_일시불_B0M,월중평잔_일시불,평잔_일시불_3M,잔액_일시불_B0M,잔액_일시불_B1M,잔액_일시불_B2M,인입횟수_ARS_R6M,Segment,고객군,Cluster
0,0,201807,TRAIN_000000,1,1,0,0,0,0,0,...,1084,1503,1791,998,736,1083,10회 이상,D,일반 고객,3
1,1,201807,TRAIN_000001,1,1,0,0,0,0,0,...,4090,4447,3761,2565,6795,1424,1회 이상,E,일반 고객,3
2,2,201807,TRAIN_000002,1,1,1,1,0,0,0,...,5006,5540,6796,5312,5150,6143,1회 이상,C,일반 고객,3
3,3,201807,TRAIN_000003,2,2,1,1,0,0,0,...,487,606,772,730,462,708,10회 이상,D,일반 고객,3
4,4,201807,TRAIN_000004,1,1,1,1,0,0,0,...,0,0,0,0,0,0,1회 이상,E,비활성 고객,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
399995,399995,201807,TRAIN_399995,1,1,1,1,0,0,0,...,0,0,0,0,0,0,1회 이상,E,비활성 고객,1
399996,399996,201807,TRAIN_399996,1,1,1,1,0,0,0,...,10598,11321,11554,6374,12113,6533,1회 이상,D,활동적 일반 고객,0
399997,399997,201807,TRAIN_399997,1,1,1,1,1,1,1,...,1831,2144,2407,2168,845,1743,1회 이상,C,일반 고객,3
399998,399998,201807,TRAIN_399998,1,1,0,0,1,1,1,...,0,0,0,0,0,0,1회 이상,E,비활성 고객,1
399999,399999,201807,TRAIN_399999,1,1,0,0,1,1,1,...,637,736,1388,1110,0,896,1회 이상,E,일반 고객,3

### 데이터 인코딩

In [ ]:
# 컬럼들을 리스트에 담아 확인한다
column_list = train_df.columns.tolist()
column_list

['index',
 '기준년월',
 'ID',
 '소지카드수_이용가능_신용',
 '소지카드수_유효_신용',
 '이용가능여부_해외겸용_본인',
 '보유여부_해외겸용_본인',
 '수신거부여부_TM',
 '수신거부여부_메일',
 '수신거부여부_DM',
 '이용금액_R3M_신용체크',
 '이용금액_R3M_신용',
 '_1순위카드이용금액',
 '이용카드수_신용체크',
 '_2순위카드이용금액',
 '_1순위카드이용건수',
 '_2순위카드이용건수',
 '이용카드수_신용',
 '상향가능한도금액',
 '상향가능CA한도금액',
 '정상청구원금_B5M',
 '정상청구원금_B0M',
 '정상청구원금_B2M',
 '이용금액_일시불_R12M',
 '이용금액_일시불_B0M',
 '이용금액_오프라인_B0M',
 '이용금액_일시불_R6M',
 '이용금액_일시불_R3M',
 '정상입금원금_B5M',
 '정상입금원금_B0M',
 '이용금액_오프라인_R3M',
 '이용금액_오프라인_R6M',
 '정상입금원금_B2M',
 '_3순위업종_이용금액',
 '_2순위업종_이용금액',
 '이용건수_신용_R12M',
 '_2순위쇼핑업종_이용금액',
 '최대이용금액_일시불_R12M',
 '이용건수_신판_R12M',
 '이용건수_일시불_R12M',
 '_1순위업종_이용금액',
 '_3순위쇼핑업종_이용금액',
 '이용가맹점수',
 '이용건수_오프라인_B0M',
 '이용건수_오프라인_R6M',
 '이용건수_오프라인_R3M',
 '쇼핑_도소매_이용금액',
 '이용건수_신용_R6M',
 '이용건수_신용_B0M',
 '이용건수_신용_R3M',
 '이용건수_신판_R6M',
 '이용건수_신판_B0M',
 '이용건수_신판_R3M',
 '이용건수_일시불_R6M',
 '이용건수_일시불_B0M',
 '이용건수_일시불_R3M',
 '_1순위교통업종_이용금액',
 '연체입금원금_B0M',
 '쇼핑_마트_이용금액',
 '쇼핑_슈퍼마켓_이용금액',
 '교통_주유이용금액',
 '이용금액_온라인_B0M',
 '연체입금원금_B5M',
 '연체입금원금_B2M',
 '이용금액_페이_온라인_B0M',
 '_1순위쇼핑업종_이용금액',
 '연속유실적개월수_기본_24M_카드',
 '이용금액대',
 '청구금액_R6M',
 '청구금액_R3M',
 '청구금액_B0',
 '할인건수_R3M',
 '월중평잔_일시불_B0M',
 '월중평잔_일시불',
 '평잔_일시불_3M',
 '잔액_일시불_B0M',
 '잔액_일시불_B1M',
 '잔액_일시불_B2M',
 '인입횟수_ARS_R6M',
 'Segment',
 '고객군',
 'Cluster']

In [ ]:
# 분산이 0인 컬럼을 제거
train_df = train_df.drop(['소지카드수_이용가능_신용', '소지카드수_유효_신용'], axis=1)

In [ ]:
train_df = train_df.drop(['index', 'ID','기준년월','고객군'], axis=1)

In [ ]:
# Segment 인코딩
train_df['Segment'] = train_df['Segment'].factorize()[0]

In [ ]:
### 인코딩한다
train_df['이용금액대'] = train_df['이용금액대'].factorize()[0]
train_df['상향가능한도금액'] = train_df['상향가능한도금액'].factorize()[0]
train_df['상향가능CA한도금액'] = train_df['상향가능CA한도금액'].factorize()[0]
train_df['보유여부_해외겸용_본인'] = train_df['보유여부_해외겸용_본인'].factorize()[0]
train_df['이용가능여부_해외겸용_본인'] = train_df['이용가능여부_해외겸용_본인'].factorize()[0]
train_df['할인건수_R3M'] = train_df['할인건수_R3M'].factorize()[0]
train_df['인입횟수_ARS_R6M'] = train_df['인입횟수_ARS_R6M'].factorize()[0]
train_df['수신거부여부_TM'] = train_df['수신거부여부_TM'].factorize()[0]
train_df['수신거부여부_메일'] = train_df['수신거부여부_메일'].factorize()[0]
train_df['수신거부여부_DM'] = train_df['수신거부여부_DM'].factorize()[0]

In [ ]:
train_df['상향가능CA한도금액'].value_counts()

상향가능CA한도금액
0    182143
1    114065
2     83381
3     20312
4        99
Name: count, dtype: int64

In [ ]:
#변수들 간의 관계 확인
corr_matrix = train_df.corr(method='spearman')

In [ ]:
# 절댓값 기준 상관계수 정렬
corr_unstacked = corr_matrix.abs().unstack()
corr_filtered = corr_unstacked[corr_unstacked < 1].sort_values(ascending=False)

# 상위 N개 20개출력
print(corr_filtered.head(60))

이용건수_일시불_B0M   이용건수_신판_B0M      0.999510
이용건수_신판_B0M    이용건수_일시불_B0M     0.999510
이용건수_신용_B0M    이용건수_신판_B0M      0.999140
이용건수_신판_B0M    이용건수_신용_B0M      0.999140
이용건수_신판_R6M    이용건수_신용_R6M      0.998959
이용건수_신용_R6M    이용건수_신판_R6M      0.998959
이용건수_신용_R3M    이용건수_신판_R3M      0.998935
이용건수_신판_R3M    이용건수_신용_R3M      0.998935
이용건수_일시불_B0M   이용건수_신용_B0M      0.998496
이용건수_신용_B0M    이용건수_일시불_B0M     0.998496
이용건수_신용_R12M   이용건수_신판_R12M     0.998466
이용건수_신판_R12M   이용건수_신용_R12M     0.998466
이용건수_일시불_R3M   이용건수_신판_R3M      0.998065
이용건수_신판_R3M    이용건수_일시불_R3M     0.998065
이용건수_신판_R6M    이용건수_일시불_R6M     0.996917
이용건수_일시불_R6M   이용건수_신판_R6M      0.996917
이용건수_일시불_R3M   이용건수_신용_R3M      0.996767
이용건수_신용_R3M    이용건수_일시불_R3M     0.996767
이용건수_신용_R6M    이용건수_일시불_R6M     0.995556
이용건수_일시불_R6M   이용건수_신용_R6M      0.995556
이용건수_일시불_R12M  이용건수_신판_R12M     0.995275
이용건수_신판_R12M   이용건수_일시불_R12M    0.995275
이용건수_일시불_R12M  이용건수_신용_R12M     0.993507
이용건수_신용_R12M   이용건수_일시불_R12M    0.993507
월중평잔_일시불_B0M   월중평잔_일시불         0.986672
월중평잔_일시불       월중평잔_일시불_B0M     0.986672
잔액_일시불_B0M     월중평잔_일시불_B0M     0.979671
월중평잔_일시불_B0M   잔액_일시불_B0M       0.979671
_2순위카드이용금액     _2순위카드이용건수       0.978087
_2순위카드이용건수     _2순위카드이용금액       0.978087
이용건수_오프라인_R6M  이용건수_오프라인_R3M    0.973463
이용건수_오프라인_R3M  이용건수_오프라인_R6M    0.973463
월중평잔_일시불       평잔_일시불_3M        0.971622
평잔_일시불_3M      월중평잔_일시불         0.971622
월중평잔_일시불       잔액_일시불_B0M       0.969155
잔액_일시불_B0M     월중평잔_일시불         0.969155
청구금액_R3M       청구금액_R6M         0.964396
청구금액_R6M       청구금액_R3M         0.964396
잔액_일시불_B1M     월중평잔_일시불         0.963706
월중평잔_일시불       잔액_일시불_B1M       0.963706
월중평잔_일시불_B0M   평잔_일시불_3M        0.961987
평잔_일시불_3M      월중평잔_일시불_B0M     0.961987
이용금액_오프라인_R6M  이용금액_오프라인_R3M    0.961906
이용금액_오프라인_R3M  이용금액_오프라인_R6M    0.961906
청구금액_B0        청구금액_R3M         0.960554
청구금액_R3M       청구금액_B0          0.960554
이용금액_R3M_신용    _1순위카드이용금액       0.957164
_1순위카드이용금액     이용금액_R3M_신용      0.957164
잔액_일시불_B1M     월중평잔_일시불_B0M     0.956484
월중평잔_일시불_B0M   잔액_일시불_B1M       0.956484
이용금액_R3M_신용    이용금액_R3M_신용체크    0.954749
이용금액_R3M_신용체크  이용금액_R3M_신용      0.954749
이용건수_신용_B0M    이용건수_신용_R3M      0.950571
이용건수_신용_R3M    이용건수_신용_B0M      0.950571
이용건수_신용_B0M    이용건수_신판_R3M      0.950530
이용건수_신판_R3M    이용건수_신용_B0M      0.950530
이용건수_신판_B0M    이용건수_신판_R3M      0.949831
이용건수_신판_R3M    이용건수_신판_B0M      0.949831
이용건수_일시불_R3M   이용건수_신용_B0M      0.949183
이용건수_신용_B0M    이용건수_일시불_R3M     0.949183
dtype: float64

이용건수_신판_R12M
월중평잔_일시불_B0M
_2순위카드이용금액
이용건수_오프라인_R6M
청구금액_R6M
이용금액_오프라인_R3M
'이용카드수_신용체크'
_2순위쇼핑업종_이용금액

In [ ]:
numerical_cols = ['이용금액_R3M_신용체크', '_1순위카드이용금액', '이용카드수_신용체크', '_2순위카드이용금액', '_1순위카드이용건수',
'정상청구원금_B5M','정상청구원금_B0M', '정상청구원금_B2M', '이용금액_일시불_R12M',
       '정상입금원금_B5M',
       '정상입금원금_B0M', '이용금액_오프라인_R3M', '정상입금원금_B2M',
       '_3순위업종_이용금액', '이용건수_신용_R12M',
       '_3순위쇼핑업종_이용금액', '이용가맹점수','이용건수_오프라인_R6M','쇼핑_도소매_이용금액', '_1순위교통업종_이용금액',
       '연체입금원금_B0M', '쇼핑_마트_이용금액', '쇼핑_슈퍼마켓_이용금액', '교통_주유이용금액', '이용금액_온라인_B0M',
       '연체입금원금_B5M', '연체입금원금_B2M', '이용금액_페이_온라인_B0M', '_1순위쇼핑업종_이용금액',
       '연속유실적개월수_기본_24M_카드','청구금액_R6M','월중평잔_일시불_B0M']

In [ ]:
#변수들 간의 관계 확인
corr_matrix2 = train_df[numerical_cols].corr(method='spearman')
# 절댓값 기준 상관계수 정렬
corr_unstacked2 = corr_matrix2.abs().unstack()
corr_filtered = corr_unstacked2[corr_unstacked2 < 1].sort_values(ascending=False)

# 상위 N개 20개출력
print(corr_filtered.head(60))

_1순위카드이용금액     이용금액_오프라인_R3M    0.945063
이용금액_오프라인_R3M  _1순위카드이용금액       0.945063
이용가맹점수         이용건수_오프라인_R6M    0.928439
이용건수_오프라인_R6M  이용가맹점수           0.928439
이용금액_R3M_신용체크  _1순위카드이용금액       0.917556
_1순위카드이용금액     이용금액_R3M_신용체크    0.917556
청구금액_R6M       정상청구원금_B2M       0.916368
정상청구원금_B2M     청구금액_R6M         0.916368
이용금액_오프라인_R3M  이용건수_오프라인_R6M    0.908569
이용건수_오프라인_R6M  이용금액_오프라인_R3M    0.908569
월중평잔_일시불_B0M   이용금액_오프라인_R3M    0.906086
이용금액_오프라인_R3M  월중평잔_일시불_B0M     0.906086
_1순위카드이용건수     이용가맹점수           0.902821
이용가맹점수         _1순위카드이용건수       0.902821
_3순위업종_이용금액    이용가맹점수           0.898435
이용가맹점수         _3순위업종_이용금액      0.898435
이용건수_오프라인_R6M  이용금액_일시불_R12M    0.894618
이용금액_일시불_R12M  이용건수_오프라인_R6M    0.894618
_3순위업종_이용금액    이용건수_오프라인_R6M    0.894379
이용건수_오프라인_R6M  _3순위업종_이용금액      0.894379
정상청구원금_B2M     정상청구원금_B0M       0.891601
정상청구원금_B0M     정상청구원금_B2M       0.891601
정상청구원금_B5M     정상청구원금_B2M       0.889220
정상청구원금_B2M     정상청구원금_B5M       0.889220
청구금액_R6M       정상청구원금_B0M       0.889189
정상청구원금_B0M     청구금액_R6M         0.889189
_1순위카드이용금액     월중평잔_일시불_B0M     0.889184
월중평잔_일시불_B0M   _1순위카드이용금액       0.889184
_3순위업종_이용금액    이용금액_오프라인_R3M    0.888794
이용금액_오프라인_R3M  _3순위업종_이용금액      0.888794
정상청구원금_B5M     청구금액_R6M         0.886057
청구금액_R6M       정상청구원금_B5M       0.886057
               이용금액_일시불_R12M    0.882591
이용금액_일시불_R12M  청구금액_R6M         0.882591
               _1순위카드이용금액       0.882076
_1순위카드이용금액     이용금액_일시불_R12M    0.882076
이용건수_오프라인_R6M  월중평잔_일시불_B0M     0.881809
월중평잔_일시불_B0M   이용건수_오프라인_R6M    0.881809
_1순위카드이용건수     이용건수_오프라인_R6M    0.881756
이용건수_오프라인_R6M  _1순위카드이용건수       0.881756
이용금액_오프라인_R3M  이용금액_R3M_신용체크    0.879535
이용금액_R3M_신용체크  이용금액_오프라인_R3M    0.879535
이용금액_일시불_R12M  이용금액_오프라인_R3M    0.879165
이용금액_오프라인_R3M  이용금액_일시불_R12M    0.879165
정상청구원금_B0M     _1순위카드이용금액       0.878502
_1순위카드이용금액     정상청구원금_B0M       0.878502
이용가맹점수         이용금액_오프라인_R3M    0.874204
이용금액_오프라인_R3M  이용가맹점수           0.874204
이용금액_일시불_R12M  월중평잔_일시불_B0M     0.871771
월중평잔_일시불_B0M   이용금액_일시불_R12M    0.871771
정상입금원금_B2M     정상입금원금_B0M       0.868235
정상입금원금_B0M     정상입금원금_B2M       0.868235
_1순위카드이용금액     _3순위업종_이용금액      0.866796
_3순위업종_이용금액    _1순위카드이용금액       0.866796
이용건수_오프라인_R6M  _1순위카드이용금액       0.863756
_1순위카드이용금액     이용건수_오프라인_R6M    0.863756
_3순위쇼핑업종_이용금액  이용가맹점수           0.860019
이용가맹점수         _3순위쇼핑업종_이용금액    0.860019
_3순위업종_이용금액    월중평잔_일시불_B0M     0.858798
월중평잔_일시불_B0M   _3순위업종_이용금액      0.858798
dtype: float64

이용건수_신용_R12M
_3순위업종_이용금액
_1순위카드이용금액
이용금액_R3M_신용체크

In [ ]:
categorical_cols = ['이용금액대',
'이용가능여부_해외겸용_본인',
'보유여부_해외겸용_본인',
'상향가능한도금액',
'상향가능CA한도금액',
'할인건수_R3M',
'인입횟수_ARS_R6M',
'수신거부여부_TM',
'수신거부여부_메일',
'수신거부여부_DM',
'Cluster']

In [ ]:
#변수들 간의 관계 확인
corr_matrix3 = train_df[categorical_cols].corr(method='spearman')
# 절댓값 기준 상관계수 정렬
corr_unstacked3 = corr_matrix3.abs().unstack()
corr_filtered2 = corr_unstacked3[corr_unstacked3 < 1].sort_values(ascending=False)

# 상위 N개 20개출력
print(corr_filtered2.head(60))

수신거부여부_메일       수신거부여부_DM         0.937424
수신거부여부_DM       수신거부여부_메일         0.937424
이용가능여부_해외겸용_본인  보유여부_해외겸용_본인      0.915628
보유여부_해외겸용_본인    이용가능여부_해외겸용_본인    0.915628
상향가능한도금액        상향가능CA한도금액        0.856276
상향가능CA한도금액      상향가능한도금액          0.856276
수신거부여부_DM       수신거부여부_TM         0.841035
수신거부여부_TM       수신거부여부_DM         0.841035
수신거부여부_메일       수신거부여부_TM         0.786292
수신거부여부_TM       수신거부여부_메일         0.786292
이용금액대           Cluster           0.262011
Cluster         이용금액대             0.262011
할인건수_R3M        이용금액대             0.184475
이용금액대           할인건수_R3M          0.184475
Cluster         할인건수_R3M          0.105580
할인건수_R3M        Cluster           0.105580
상향가능CA한도금액      인입횟수_ARS_R6M      0.097078
인입횟수_ARS_R6M    상향가능CA한도금액        0.097078
                상향가능한도금액          0.096578
상향가능한도금액        인입횟수_ARS_R6M      0.096578
이용금액대           인입횟수_ARS_R6M      0.092123
인입횟수_ARS_R6M    이용금액대             0.092123
수신거부여부_TM       상향가능CA한도금액        0.070269
상향가능CA한도금액      수신거부여부_TM         0.070269
Cluster         이용가능여부_해외겸용_본인    0.069281
이용가능여부_해외겸용_본인  Cluster           0.069281
이용금액대           보유여부_해외겸용_본인      0.068476
보유여부_해외겸용_본인    이용금액대             0.068476
수신거부여부_TM       할인건수_R3M          0.067342
할인건수_R3M        수신거부여부_TM         0.067342
이용가능여부_해외겸용_본인  할인건수_R3M          0.066514
할인건수_R3M        이용가능여부_해외겸용_본인    0.066514
                수신거부여부_DM         0.064968
수신거부여부_DM       할인건수_R3M          0.064968
수신거부여부_TM       상향가능한도금액          0.063951
상향가능한도금액        수신거부여부_TM         0.063951
상향가능CA한도금액      수신거부여부_DM         0.063475
수신거부여부_DM       상향가능CA한도금액        0.063475
수신거부여부_메일       할인건수_R3M          0.061915
할인건수_R3M        수신거부여부_메일         0.061915
상향가능CA한도금액      수신거부여부_메일         0.059956
수신거부여부_메일       상향가능CA한도금액        0.059956
상향가능한도금액        수신거부여부_DM         0.058208
수신거부여부_DM       상향가능한도금액          0.058208
상향가능한도금액        이용금액대             0.057260
이용금액대           상향가능한도금액          0.057260
상향가능한도금액        수신거부여부_메일         0.054794
수신거부여부_메일       상향가능한도금액          0.054794
할인건수_R3M        상향가능CA한도금액        0.054525
상향가능CA한도금액      할인건수_R3M          0.054525
보유여부_해외겸용_본인    할인건수_R3M          0.048313
할인건수_R3M        보유여부_해외겸용_본인      0.048313
Cluster         보유여부_해외겸용_본인      0.045704
보유여부_해외겸용_본인    Cluster           0.045704
                상향가능한도금액          0.044634
상향가능한도금액        보유여부_해외겸용_본인      0.044634
이용가능여부_해외겸용_본인  인입횟수_ARS_R6M      0.044161
인입횟수_ARS_R6M    이용가능여부_해외겸용_본인    0.044161
수신거부여부_메일       이용가능여부_해외겸용_본인    0.044030
이용가능여부_해외겸용_본인  수신거부여부_메일         0.044030
dtype: float64

### VIF 검사

In [ ]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
import statsmodels.api as sm

In [ ]:
X_cols = numerical_cols + categorical_cols

In [ ]:
categorical_cols = ['이용금액대',
'이용가능여부_해외겸용_본인',
'상향가능한도금액',
'상향가능CA한도금액',
'할인건수_R3M',
'인입횟수_ARS_R6M',
'수신거부여부_TM',
'수신거부여부_메일',
'Cluster']

In [ ]:
numerical_cols = ['이용카드수_신용체크', '_2순위카드이용금액',
       '정상입금원금_B0M', '이용금액_오프라인_R3M',
       '이용건수_신용_R12M','쇼핑_도소매_이용금액',
       '연체입금원금_B0M', '쇼핑_마트_이용금액', '쇼핑_슈퍼마켓_이용금액',
       '연체입금원금_B5M', '연체입금원금_B2M', '이용금액_페이_온라인_B0M', '_1순위쇼핑업종_이용금액',
       '연속유실적개월수_기본_24M_카드','청구금액_R6M','월중평잔_일시불_B0M']

In [ ]:
# 독립변수만 가져온다.
vif_X = train_df[X_cols]

# vif를 계산하기 위해 사용할 상수항을 추가한다.
vif_X2 = sm.add_constant(vif_X)

# vif를 계산한다
vif = pd.DataFrame()
vif['변수'] = vif_X2.columns
vif['VIF'] = [variance_inflation_factor(vif_X2.values, i) for i in range(vif_X2.shape[1])]
vif

                    변수        VIF
0                const  56.374160
1           이용카드수_신용체크   2.430798
2           _2순위카드이용금액   2.559751
3           정상입금원금_B0M   4.656399
4        이용금액_오프라인_R3M   4.722972
5         이용건수_신용_R12M   2.963189
6          쇼핑_도소매_이용금액   3.581820
7           연체입금원금_B0M   3.668574
8           쇼핑_마트_이용금액   2.219072
9         쇼핑_슈퍼마켓_이용금액   3.167940
10          연체입금원금_B5M   3.153890
11          연체입금원금_B2M   4.305144
12     이용금액_페이_온라인_B0M   3.777037
13       _1순위쇼핑업종_이용금액   3.579445
14  연속유실적개월수_기본_24M_카드   1.668619
15            청구금액_R6M   3.749820
16        월중평잔_일시불_B0M   2.165564
17               이용금액대   1.681889
18      이용가능여부_해외겸용_본인   1.106127
19            상향가능한도금액   2.090509
20          상향가능CA한도금액   2.126139
21            할인건수_R3M   1.406205
22        인입횟수_ARS_R6M   1.117436
23           수신거부여부_TM   2.637202
24           수신거부여부_메일   2.629788
25             Cluster   1.197105

정상청구원금_B0M	82.377599
정상청구원금_B2M	83.512255
_1순위카드이용건수	26.427446
수신거부여부_DM	10.795657
_1순위카드이용금액	25.843505
정상입금원금_B5M	23.613975
_1순위교통업종_이용금액	22.400460
교통_주유이용금액	19.060732
이용금액_온라인_B0M	12.719146
이용가맹점수	13.379539
정상입금원금_B2M	10.104169
_3순위쇼핑업종_이용금액	10.920207
이용금액_R3M_신용체크	9.354008
이용금액_일시불_R12M	8.305189
정상청구원금_B5M	7.549244
보유여부_해외겸용_본인	6.553122
이용건수_오프라인_R6M	7.176792
_3순위업종_이용금액	5.576560

In [ ]:
all_df = train_df[X_cols]

In [ ]:
all_df.to_parquet('/content/drive/MyDrive/공유문서함/all_df07VIF끝.parquet')

- 버린 컬럼 중에서 다시 쓸만한 걸 찾는다


- 혼동행렬을 확인하고 왜 틀렸는지

자주 틀린 세그먼트에 대해서 어떤 컬럼과 상관이 높은지 찾는다
PCA늘려서 해본다.