In [1]:
# 기본
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 경고 뜨지 않게 설정
import warnings
warnings.filterwarnings('ignore')

# 그래프 설정
sns.set()

# 데이터 전처리 알고리즘
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# 학습용과 검증용으로 나누는 함수
from sklearn.model_selection import train_test_split

# 교차 검증
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

# 평가함수
# 분류용
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

# 회귀용
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

# 모델의 최적의 하이퍼 파라미터를 찾기 위한 도구
from sklearn.model_selection import GridSearchCV

# 머신러닝 알고리즘 - 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import VotingClassifier

# 머신러닝 알고리즘 - 회귀
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from sklearn.ensemble import VotingRegressor

# 학습 모델 저장을 위한 라이브러리
import pickle

In [2]:
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
fonts-nanum is already the newest version (20200506-1).
0 upgraded, 0 newly installed, 0 to remove and 35 not upgraded.
/usr/share/fonts: caching, new cache contents: 0 fonts, 1 dirs
/usr/share/fonts/truetype: caching, new cache contents: 0 fonts, 3 dirs
/usr/share/fonts/truetype/humor-sans: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/liberation: caching, new cache contents: 16 fonts, 0 dirs
/usr/share/fonts/truetype/nanum: caching, new cache contents: 12 fonts, 0 dirs
/usr/local/share/fonts: caching, new cache contents: 0 fonts, 0 dirs
/root/.local/share/fonts: skipping, no such directory
/root/.fonts: skipping, no such directory
/usr/share/fonts/truetype: skipping, looped directory detected
/usr/share/fonts/truetype/humor-sans: skipping, looped directory detected
/usr/share/fonts/truetype/liberation: skipping, looped directory detected
/usr/share/fonts/truetype/nanum: skipping, looped directory detected
/var/cache/fontconfig: cleaning cache directory
/root/.cache/fontconfig: not cleaning non-existent cache directory
/root/.fontconfig: not cleaning non-existent cache directory
fc-cache: succeeded

In [3]:
plt.rcParams['font.family'] = 'NanumBarunGothic'
plt.rcParams['axes.unicode_minus'] = False

### 프로젝트 셋팅

In [4]:
# 학습이 완료된 모델 파일 이름
best_model_path1 = '/content/drive/MyDrive/model/best_model2_ab.dat'
best_model_path2 = '/content/drive/MyDrive/model/best_model4_cde.dat'
# 예측 결과를 저장할 파일 이름
prediction_path = '/content/drive/MyDrive/model/card_segment_prediction.csv'

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

### 저장한 모델 객체 등을 복원한다.

In [6]:
# 모델 불러오기

# ab모델
with open(best_model_path1, "rb") as f:
    인입횟수_ARS_R6M인코더_ab = pickle.load(f)
    방문횟수_앱_R6M인코더_ab = pickle.load(f)
    방문횟수_PC_R6M인코더_ab = pickle.load(f)
    방문일수_PC_R6M인코더_ab = pickle.load(f)
    거주시도명인코더_ab = pickle.load(f)
    RV전환가능여부인코더_ab = pickle.load(f)
    연령인코더_ab = pickle.load(f)
    Life_Stage인코더_ab = pickle.load(f)
    캠페인접촉건수_R12M인코더_ab = pickle.load(f)
    이용메뉴건수_ARS_R6M인코더_ab = pickle.load(f)
    대표청구서수령지구분코드인코더_ab = pickle.load(f)
    청구서수령방법인코더_ab = pickle.load(f)
    캠페인접촉일수_R12M인코더_ab = pickle.load(f)
    할인건수_R3M인코더_ab = pickle.load(f)

    model_ab = pickle.load(f)
    scaler_ab = pickle.load(f)

# cd모델
with open(best_model_path2, "rb") as f:
    인입횟수_ARS_R6M인코더_cde = pickle.load(f)
    방문횟수_앱_R6M인코더_cde = pickle.load(f)
    방문횟수_PC_R6M인코더_cde = pickle.load(f)
    방문일수_PC_R6M인코더_cde = pickle.load(f)
    이용금액대인코더_cde = pickle.load(f)
    le_cde = pickle.load(f)  # LabelEncoder

    model_cde = pickle.load(f)
    scaler_cde = pickle.load(f)

In [7]:
display(model_ab)
display(model_cde)
display(scaler_ab)
display(scaler_cde)

LGBMClassifier(device='gpu', n_estimators=250, verbose=-1)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=-1,
              num_parallel_tree=None, objective='multi:softprob', ...)

StandardScaler()

StandardScaler()

### 예측할 데이터를 준비한다.
- 모든 준비가 완료되면 입력데이터는 test_X 라는 변수에 담아주도록 한다.

In [8]:
# 예측할 데이터를 읽어온다.
df1 = pd.read_parquet('/content/drive/MyDrive/abcde/ab_cde_test.parquet')

In [9]:
# A/B 모델이 사용한 피처
ab_features = [
'이용후경과월_할부_무이자', '이용후경과월_할부',
       '이용개월수_할부_무이자_R12M', '이용개월수_할부_R12M', '카드이용한도금액_B2M', '카드이용한도금액_B1M',
       '카드이용한도금액', '이용개월수_할부_R6M', 'CA한도금액', '이용개월수_할부_무이자_R6M',
       '이용개월수_할부_R3M', '이용개월수_할부_무이자_R3M', '이용건수_할부_무이자_R3M', '이용건수_할부_R3M',
       '이용금액_할부_무이자_R6M', '방문횟수_앱_R6M', '거주시도명', 'RV전환가능여부', '연령',
       'Life_Stage', '인입횟수_ARS_R6M', '캠페인접촉건수_R12M', '이용메뉴건수_ARS_R6M',
       '대표청구서수령지구분코드', '청구서수령방법', '캠페인접촉일수_R12M', '방문일수_PC_R6M', '방문횟수_PC_R6M',
       '할인건수_R3M']

# C/D/E 모델이 사용한 피처
cde_features = [
'이용금액_R3M_신용체크', '청구금액_R6M', '이용금액_일시불_R12M',
       '이용금액_R3M_신용', '청구금액_R3M', '청구금액_B0', '이용금액_일시불_B0M', '이용금액_오프라인_B0M',
       '_1순위카드이용금액', '이용금액_일시불_R6M', '이용금액_일시불_R3M', '이용금액_오프라인_R3M',
       '이용금액_오프라인_R6M', '_3순위업종_이용금액', '_2순위업종_이용금액', '이용건수_신용_R12M',
       '이용건수_신판_R12M', '_2순위쇼핑업종_이용금액', '최대이용금액_일시불_R12M', '이용건수_일시불_R12M',
       '_3순위쇼핑업종_이용금액', '_1순위업종_이용금액', '이용건수_오프라인_B0M', '이용건수_오프라인_R3M',
       '이용건수_오프라인_R6M', '쇼핑_도소매_이용금액', '이용건수_신용_R6M', '이용건수_신용_B0M',
       '이용건수_신용_R3M', '이용건수_신판_R6M', '이용건수_신판_B0M', '이용건수_신판_R3M',
       '이용건수_일시불_R6M', '이용건수_일시불_B0M', '이용건수_일시불_R3M', '_1순위교통업종_이용금액',
       '이용카드수_신용체크', '_2순위카드이용금액', '정상청구원금_B5M', '쇼핑_마트_이용금액', '쇼핑_슈퍼마켓_이용금액',
       '_1순위카드이용건수', '교통_주유이용금액', '_2순위카드이용건수', '이용금액_온라인_B0M', '이용카드수_신용',
       '이용금액_페이_온라인_B0M', '이용금액대', '인입횟수_ARS_R6M', '방문횟수_앱_R6M', '방문횟수_PC_R6M',
       '방문일수_PC_R6M', '연체입금원금_B5M', '연체입금원금_B2M', '입회일자_신용']

In [10]:
ab_df = df1[ab_features]
cde_df = df1[cde_features]

In [11]:
# 예측 데이터 변환 ab

ab_df['인입횟수_ARS_R6M'] = 인입횟수_ARS_R6M인코더_ab.transform(ab_df['인입횟수_ARS_R6M'])
ab_df['방문횟수_앱_R6M'] = 방문횟수_앱_R6M인코더_ab.transform(ab_df['방문횟수_앱_R6M'])
ab_df['방문횟수_PC_R6M'] = 방문횟수_PC_R6M인코더_ab.transform(ab_df['방문횟수_PC_R6M'])
ab_df['방문일수_PC_R6M'] = 방문일수_PC_R6M인코더_ab.transform(ab_df['방문일수_PC_R6M'])
ab_df['거주시도명'] = 거주시도명인코더_ab.transform(ab_df['거주시도명'])
ab_df['RV전환가능여부'] = RV전환가능여부인코더_ab.transform(ab_df['RV전환가능여부'])
ab_df['연령'] = 연령인코더_ab.transform(ab_df['연령'])
ab_df['Life_Stage'] = Life_Stage인코더_ab.transform(ab_df['Life_Stage'])
ab_df['캠페인접촉건수_R12M'] = 캠페인접촉건수_R12M인코더_ab.transform(ab_df['캠페인접촉건수_R12M'])
ab_df['이용메뉴건수_ARS_R6M'] = 이용메뉴건수_ARS_R6M인코더_ab.transform(ab_df['이용메뉴건수_ARS_R6M'])
ab_df['대표청구서수령지구분코드'] = 대표청구서수령지구분코드인코더_ab.transform(ab_df['대표청구서수령지구분코드'])
ab_df['청구서수령방법'] = 청구서수령방법인코더_ab.transform(ab_df['청구서수령방법'])
ab_df['캠페인접촉일수_R12M'] = 캠페인접촉일수_R12M인코더_ab.transform(ab_df['캠페인접촉일수_R12M'])
ab_df['할인건수_R3M'] = 할인건수_R3M인코더_ab.transform(ab_df['할인건수_R3M'])

# 예측 데이터 변환 cde
cde_df['이용금액대'] = 이용금액대인코더_cde.transform(cde_df['이용금액대'])
cde_df['인입횟수_ARS_R6M'] = 인입횟수_ARS_R6M인코더_cde.transform(cde_df['인입횟수_ARS_R6M'])
cde_df['방문횟수_앱_R6M'] = 방문횟수_앱_R6M인코더_cde.transform(cde_df['방문횟수_앱_R6M'])
cde_df['방문횟수_PC_R6M'] = 방문횟수_PC_R6M인코더_cde.transform(cde_df['방문횟수_PC_R6M'])
cde_df['방문일수_PC_R6M'] = 방문일수_PC_R6M인코더_cde.transform(cde_df['방문일수_PC_R6M'])

In [12]:
cde_df

,이용금액_R3M_신용체크,청구금액_R6M,이용금액_일시불_R12M,이용금액_R3M_신용,청구금액_R3M,청구금액_B0,이용금액_일시불_B0M,이용금액_오프라인_B0M,_1순위카드이용금액,이용금액_일시불_R6M,...,이용카드수_신용,이용금액_페이_온라인_B0M,이용금액대,인입횟수_ARS_R6M,방문횟수_앱_R6M,방문횟수_PC_R6M,방문일수_PC_R6M,연체입금원금_B5M,연체입금원금_B2M,입회일자_신용
0,21458,22151,49063,21458,11441,4931,7650,9877,13852,26595,...,2,1108,1,1,1,1,1,2414,840,20140501
1,18681,32878,7771,10759,20522,10152,367,4006,11065,-7578,...,1,1595,1,1,1,1,1,2959,763,20160201
2,40758,71867,73003,40758,50508,13223,8547,11298,27071,48483,...,2,0,0,1,1,1,1,0,0,20180301
3,5255,4986,7421,5255,4604,2112,1270,976,4827,403,...,1,0,3,1,1,1,1,0,196,20120701
4,16148,10758,10493,14290,6788,4406,709,4017,8011,1238,...,2,0,2,1,1,1,1,0,0,20031201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,0,0,0,0,0,0,0,0,0,0,...,0,0,5,1,1,1,1,0,0,20130301
599996,3110,2237,2631,3110,1256,359,-121,407,1231,3,...,1,0,4,1,0,1,1,689,0,20171001
599997,0,0,0,0,0,0,0,0,0,0,...,0,0,5,1,1,1,1,0,186,20180601
599998,173263,108420,423882,113786,48141,21273,22617,15388,63592,133431,...,4,7716,0,1,4,1,1,12448,9018,20120201
599999,3016,105,-885,3016,56,18,-832,8,-574,-4731,...,2,0,4,1,1,1,1,8,0,20150801

In [13]:
# 데이터 표준화
ab_scaled = scaler_ab.transform(ab_df)
cde_scaled = scaler_cde.transform(cde_df)

### 예측하고 저장한다.

In [14]:
proba_ab = model_ab.predict_proba(ab_scaled)
proba_cde = model_cde.predict_proba(cde_scaled)

In [17]:
print(model_ab.classes_)
print(model_cde.classes_)

[0 1]
[0 1 2]

In [36]:
print(ab_df.shape[0], cde_df.shape[0], df1.shape[0])

600000 600000 600000

In [35]:
# 전체 클래스 순서 (A,B,C,D,E)
classes = ['A', 'B', 'C', 'D', 'E']  # 최종 클래스 순서

# ab 모델 숫자 → 문자 매핑
ab_map = {0:'A', 1:'B'}

# cde 모델 숫자 → 문자 매핑
cde_map = {0:'C', 1:'D', 2:'E'}

# 결과를 담을 배열 초기화
final_proba = np.zeros((df1.shape[0], len(classes)))

In [40]:
df1_12 = df1.query('기준년월 == 201812')
df1_12 = df1_12[['ID','Segment']]

In [41]:
df1_12.to_csv('/content/drive/MyDrive/예측완/ab_cde_2_final_prediction.csv', index=False)

In [290]:
threshold = 0.995  # A/B 확률 기준

final_pred = []  # 최종 결과 담을 리스트

for i in range(df1.shape[0]):
    # A/B 모델의 예측 확률 중 최대값과 해당 클래스
    ab_max_idx = np.argmax(proba_ab[i])
    ab_max_prob = proba_ab[i][ab_max_idx]
    ab_class = ab_map[ab_max_idx]  # 'A' 또는 'B'

    if ab_max_prob >= threshold:
        final_pred.append(ab_class)  # 신뢰 높으면 A/B 사용
    else:
        # 그렇지 않으면 C/D/E 모델의 결과 사용
        cde_max_idx = np.argmax(proba_cde[i])
        cde_class = cde_map[cde_max_idx]
        final_pred.append(cde_class)

In [278]:
ab_weight = 0.255  # 0.1보다는 조금 크게
cde_weight = 0.745

final_proba = np.zeros((df1.shape[0], len(classes)))

for i, cls_num in enumerate(model_ab.classes_):
    cls_str = ab_map[cls_num]
    idx = classes.index(cls_str)
    final_proba[:, idx] = proba_ab[:, i] * ab_weight

for i, cls_num in enumerate(model_cde.classes_):
    cls_str = cde_map[cls_num]
    idx = classes.index(cls_str)
    final_proba[:, idx] = proba_cde[:, i] * cde_weight

predicted_idx = np.argmax(final_proba, axis=1)
final_pred = [classes[i] for i in predicted_idx]

In [291]:
df1['Segment'] = final_pred

In [281]:
df1_12 = df1.query('기준년월 == 201812')
df1_12 = df1_12[['ID','Segment']]

In [292]:
df1_07 = df1.query('기준년월 == 201807')
df1_07 = df1_07[['ID','Segment']]

In [283]:
df1_08 = df1.query('기준년월 == 201808')
df1_09 = df1.query('기준년월 == 201809')
df1_10 = df1.query('기준년월 == 201810')
df1_11 = df1.query('기준년월 == 201811')
df1_08 = df1_08[['ID','Segment']]
df1_09 = df1_09[['ID','Segment']]
df1_10 = df1_10[['ID','Segment']]
df1_11 = df1_11[['ID','Segment']]

In [293]:
df1_07['Segment'].value_counts()

Segment
E    44101
B    36215
A    12273
D     5710
C     1701
Name: count, dtype: int64

In [268]:
df1_12['Segment'].value_counts()

Segment
E    82372
D    13028
C     4598
A        2
Name: count, dtype: int64

In [289]:
df1_07.to_csv('/content/drive/MyDrive/예측완/ab_cde_2_final_prediction7.csv', index=False)

In [253]:
df1_12.to_csv('/content/drive/MyDrive/예측완/ab_cde_2_final_prediction.csv', index=False)

In [254]:
df1_08['Segment'].value_counts()

Segment
E    82846
D    12847
C     4273
B       25
A        9
Name: count, dtype: int64

In [255]:
df1_09['Segment'].value_counts()

Segment
E    82384
D    13251
C     4321
B       25
A       19
Name: count, dtype: int64

In [256]:
df1_10['Segment'].value_counts()

Segment
E    82706
D    12686
C     4545
B       41
A       22
Name: count, dtype: int64

In [257]:
df1_10.to_csv('/content/drive/MyDrive/예측완/ab_cde_2_final_prediction10.csv', index=False)

In [258]:
df1_09.to_csv('/content/drive/MyDrive/예측완/ab_cde_2_final_prediction09.csv', index=False)

In [259]:
df1_08.to_csv('/content/drive/MyDrive/예측완/ab_cde_2_final_prediction08.csv', index=False)

In [260]:
df1_11['Segment'].value_counts()

Segment
E    82284
D    13221
C     4464
B       21
A       10
Name: count, dtype: int64

뭔가 이상함

      [ Input Sample ]
            │
            ▼
┌───────────────┐
│ A/B 여부 판단 │  ← 이진 분류기 (is_ab_model)
└──────┬────────┘
       │
  ┌────▼────┐
  │         │
[Yes]     [No]
  │         │
  ▼         ▼
A/B 모델   C/D/E 모델
  │         │
  ▼         ▼
예측값     예측값