In [3]:
# 기본
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 경고 뜨지 않게 설정
import warnings
warnings.filterwarnings('ignore')

# 그래프 설정
sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False

# 데이터 전처리 알고리즘
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# 학습용과 검증용으로 나누는 함수
from sklearn.model_selection import train_test_split

# 교차 검증
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

# 평가함수
# 분류용
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

# 회귀용
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

# 모델의 최적의 하이퍼 파라미터를 찾기 위한 도구
from sklearn.model_selection import GridSearchCV

# 머신러닝 알고리즘 - 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import VotingClassifier

# 머신러닝 알고리즘 - 회귀
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from sklearn.ensemble import VotingRegressor

# 차원 축소
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

# 군집
from sklearn.cluster import KMeans
from sklearn.cluster import MeanShift
from sklearn.cluster import estimate_bandwidth

# 학습 모델 저장을 위한 라이브러리
import pickle

In [2]:
cols_to_load1 = [
    "ID",
    "_2순위카드이용건수",
    "이용금액_R3M_신용",
    "이용금액_R3M_신용체크",
    "_2순위카드이용금액",
    "_1순위카드이용금액",
]

In [3]:
cols_to_load3 = [
    "ID",
    "최대이용금액_할부_R12M",
    "이용금액_일시불_B0M",
    "이용금액_일시불_R12M",
    "이용금액_일시불_R3M",
    "이용금액_일시불_R6M",
    "_3순위교통업종_이용금액",
    "_3순위업종_이용금액",
    "_1순위업종_이용금액",
    "_2순위업종_이용금액",
    "이용금액_오프라인_B0M",
    "연체입금원금_B0M",
    "연체입금원금_B5M",


]

In [4]:
cols_to_load4 = [
    "ID",
    "혜택수혜금액",
]

In [5]:
cols_to_load5 = [
    "ID",
    "월중평잔_일시불",
]

In [6]:
df11=pd.read_parquet(r'data/train/1.회원정보/201807_train_.parquet', columns=cols_to_load1)
df21=pd.read_parquet(r'data/train/2.신용정보/201807_train_.parquet')
df31=pd.read_parquet(r'data/train/3.승인매출정보/201807_train_.parquet', columns=cols_to_load3)
df41=pd.read_parquet(r'data/train/4.청구입금정보/201807_train_.parquet', columns=cols_to_load4)

In [7]:
df51=pd.read_parquet(r'data/train/5.잔액정보/201807_train_.parquet', columns=cols_to_load5)
df61=pd.read_parquet(r'data/train/6.채널정보/201807_train_.parquet')
df71=pd.read_parquet(r'data/train/7.마케팅정보/201807_train_.parquet')
df81=pd.read_parquet(r'data/train/8.성과정보/201807_train_.parquet')

In [8]:
# 1. 먼저 기준이 되는 df1부터 시작
merged_df = df11.copy()

# 2. ID & 기준년월 기준으로 순차 병합
merged_df = merged_df.merge(df31, on=['ID'], how='inner')
merged_df = merged_df.merge(df41, on=['ID'], how='inner')
merged_df = merged_df.merge(df51, on=['ID'], how='inner')

In [9]:
merged_df

,ID,_2순위카드이용건수,이용금액_R3M_신용,이용금액_R3M_신용체크,_2순위카드이용금액,_1순위카드이용금액,최대이용금액_할부_R12M,이용금액_일시불_B0M,이용금액_일시불_R12M,이용금액_일시불_R3M,이용금액_일시불_R6M,_3순위교통업종_이용금액,_3순위업종_이용금액,_1순위업종_이용금액,_2순위업종_이용금액,이용금액_오프라인_B0M,연체입금원금_B0M,연체입금원금_B5M,혜택수혜금액,월중평잔_일시불
0,TRAIN_000000,0,196,196,0,3681,0,1995,20667,2877,8380,0,672,1928,1408,4043,8104,5752,0,1503
1,TRAIN_000001,0,13475,13475,0,13323,4607,2862,54341,14316,19426,0,1659,2158,2083,3980,826,821,0,4447
2,TRAIN_000002,0,23988,23988,0,24493,15453,5854,55656,15694,35136,0,1362,16924,1539,4524,9364,7014,50,5540
3,TRAIN_000003,0,3904,3904,0,5933,8874,387,10753,-2710,-7031,0,774,2405,2284,3975,10923,11196,2,606
4,TRAIN_000004,0,0,1190,0,0,0,0,-2129,-3383,957,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
399995,TRAIN_399995,0,0,2091,0,0,0,0,0,-1274,0,0,0,0,0,0,0,579,0,0
399996,TRAIN_399996,0,55111,55111,0,51615,4411,12988,207754,49255,99067,251,2313,8756,8612,12312,1910,0,122,11321
399997,TRAIN_399997,0,14172,14172,0,12996,22080,4363,37349,7729,16136,0,1873,3136,2162,9739,856,6360,0,2144
399998,TRAIN_399998,0,0,0,0,0,0,0,0,-441,0,0,0,0,0,0,507,672,0,0
399999,TRAIN_399999,41,22796,22796,11023,10250,12676,3415,22727,6857,14253,0,769,3598,2758,4537,866,2392,0,736

In [10]:
drop_cols = [
    '이용금액_R3M_신용','이용금액_일시불_B0M', '이용금액_일시불_R3M', '이용금액_일시불_R6M',
    '연체입금원금_B5M', '_2순위카드이용건수', '_2순위카드이용금액', '이용금액_오프라인_B0M', '_1순위카드이용금액'
]

merged_df2 = merged_df.drop(columns=drop_cols)

In [11]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
import statsmodels.api as sm

# vif 표를 출력한 후 vif 계수가 높다고 생각되는 컬럼들을 추가하여 계속 돌려보요요
# vif_X = train_df2.drop(['Transported'], axis=1)
# vif_X = train_df2.drop(['Transported', 'NumberInGroup'], axis=1)
vif_X = merged_df2.drop(['ID'], axis=1)

# vif를 계산하기 위해 상수항을 추가한다.
vif_X2 = sm.add_constant(vif_X)

vif_X2

,const,이용금액_R3M_신용체크,최대이용금액_할부_R12M,이용금액_일시불_R12M,_3순위교통업종_이용금액,_3순위업종_이용금액,_1순위업종_이용금액,_2순위업종_이용금액,연체입금원금_B0M,혜택수혜금액,월중평잔_일시불
0,1.0,196,0,20667,0,672,1928,1408,8104,0,1503
1,1.0,13475,4607,54341,0,1659,2158,2083,826,0,4447
2,1.0,23988,15453,55656,0,1362,16924,1539,9364,50,5540
3,1.0,3904,8874,10753,0,774,2405,2284,10923,2,606
4,1.0,1190,0,-2129,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
399995,1.0,2091,0,0,0,0,0,0,0,0,0
399996,1.0,55111,4411,207754,251,2313,8756,8612,1910,122,11321
399997,1.0,14172,22080,37349,0,1873,3136,2162,856,0,2144
399998,1.0,0,0,0,0,0,0,0,507,0,0
399999,1.0,22796,12676,22727,0,769,3598,2758,866,0,736

In [12]:
# vif를 계산한다.
vif = pd.DataFrame()
vif['변수'] = vif_X2.columns
vif['VIF'] = [variance_inflation_factor(vif_X2.values, i) for i in range(vif_X2.shape[1])]
vif

                변수       VIF
0            const  1.786996
1    이용금액_R3M_신용체크  4.991400
2   최대이용금액_할부_R12M  1.367730
3    이용금액_일시불_R12M  4.971564
4    _3순위교통업종_이용금액  1.533906
5      _3순위업종_이용금액  5.557734
6      _1순위업종_이용금액  2.756860
7      _2순위업종_이용금액  5.148981
8       연체입금원금_B0M  1.271750
9           혜택수혜금액  1.883615
10        월중평잔_일시불  2.234466

In [13]:
pd.set_option('display.max_rows', None)
vif_sorted = vif.sort_values(by='VIF', ascending=False)
display(vif_sorted)

                변수       VIF
5      _3순위업종_이용금액  5.557734
7      _2순위업종_이용금액  5.148981
1    이용금액_R3M_신용체크  4.991400
3    이용금액_일시불_R12M  4.971564
6      _1순위업종_이용금액  2.756860
10        월중평잔_일시불  2.234466
9           혜택수혜금액  1.883615
0            const  1.786996
4    _3순위교통업종_이용금액  1.533906
2   최대이용금액_할부_R12M  1.367730
8       연체입금원금_B0M  1.271750

In [14]:
10/0

ZeroDivisionError: division by zero

In [ ]:
# 상관계수 계산
corr = vif_X.corr()

# 상삼각형 마스크 생성 (중복 제거용)
mask = np.triu(np.ones_like(corr, dtype=bool))

# 시각화
plt.figure(figsize=(18, 15))
sns.heatmap(
    corr,
    mask=mask,
    cmap='RdBu_r',
    annot=True,
    fmt=".2f",
    annot_kws={"size": 8},
    linewidths=0.5,
    cbar_kws={"shrink": 0.5}
)

# 축 글씨 회전
plt.xticks(rotation=45, ha='right', fontsize=8)
plt.yticks(rotation=0, fontsize=8)

plt.title("변수 간 상관계수 히트맵", fontsize=14, pad=20)
plt.tight_layout()
plt.show()

---

In [1]:
cols_to_load1=['ID','기준년월','이용금액_R3M_신용체크', '소지카드수_이용가능_신용']
cols_to_load3=['ID','기준년월','최대이용금액_할부_R12M', '이용금액_일시불_R12M', '_3순위업종_이용금액', '이용금액_오프라인_B0M', '연체입금원금_B0M', '이용금액대']
cols_to_load4=['ID','기준년월','혜택수혜금액']
cols_to_load5=['ID','기준년월','월중평잔_일시불']

In [4]:
df11=pd.read_parquet(r'data/train/1.회원정보/201807_train_.parquet', columns=cols_to_load1)
df12=pd.read_parquet(r'data/train/1.회원정보/201808_train_.parquet', columns=cols_to_load1)
df13=pd.read_parquet(r'data/train/1.회원정보/201809_train_.parquet', columns=cols_to_load1)
df14=pd.read_parquet(r'data/train/1.회원정보/201810_train_.parquet', columns=cols_to_load1)
df15=pd.read_parquet(r'data/train/1.회원정보/201811_train_.parquet', columns=cols_to_load1)
df16=pd.read_parquet(r'data/train/1.회원정보/201812_train_.parquet', columns=cols_to_load1)

In [5]:
df31=pd.read_parquet(r'data/train/3.승인매출정보/201807_train_.parquet', columns=cols_to_load3)
df32=pd.read_parquet(r'data/train/3.승인매출정보/201808_train_.parquet', columns=cols_to_load3)
df33=pd.read_parquet(r'data/train/3.승인매출정보/201809_train_.parquet', columns=cols_to_load3)
df34=pd.read_parquet(r'data/train/3.승인매출정보/201810_train_.parquet', columns=cols_to_load3)
df35=pd.read_parquet(r'data/train/3.승인매출정보/201811_train_.parquet', columns=cols_to_load3)
df36=pd.read_parquet(r'data/train/3.승인매출정보/201812_train_.parquet', columns=cols_to_load3)

In [6]:
df41=pd.read_parquet(r'data/train/4.청구입금정보/201807_train_.parquet', columns=cols_to_load4)
df42=pd.read_parquet(r'data/train/4.청구입금정보/201808_train_.parquet', columns=cols_to_load4)
df43=pd.read_parquet(r'data/train/4.청구입금정보/201809_train_.parquet', columns=cols_to_load4)
df44=pd.read_parquet(r'data/train/4.청구입금정보/201810_train_.parquet', columns=cols_to_load4)
df45=pd.read_parquet(r'data/train/4.청구입금정보/201811_train_.parquet', columns=cols_to_load4)
df46=pd.read_parquet(r'data/train/4.청구입금정보/201812_train_.parquet', columns=cols_to_load4)

In [7]:
df51=pd.read_parquet(r'data/train/5.잔액정보/201807_train_.parquet', columns=cols_to_load5)
df52=pd.read_parquet(r'data/train/5.잔액정보/201808_train_.parquet', columns=cols_to_load5)
df53=pd.read_parquet(r'data/train/5.잔액정보/201809_train_.parquet', columns=cols_to_load5)
df54=pd.read_parquet(r'data/train/5.잔액정보/201810_train_.parquet', columns=cols_to_load5)
df55=pd.read_parquet(r'data/train/5.잔액정보/201811_train_.parquet', columns=cols_to_load5)
df56=pd.read_parquet(r'data/train/5.잔액정보/201812_train_.parquet', columns=cols_to_load5)

In [8]:
df_test11=pd.read_parquet(r'data/test/1.회원정보/201807_test_.parquet', columns=cols_to_load1)
df_test12=pd.read_parquet(r'data/test/1.회원정보/201808_test_.parquet', columns=cols_to_load1)
df_test13=pd.read_parquet(r'data/test/1.회원정보/201809_test_.parquet', columns=cols_to_load1)
df_test14=pd.read_parquet(r'data/test/1.회원정보/201810_test_.parquet', columns=cols_to_load1)
df_test15=pd.read_parquet(r'data/test/1.회원정보/201811_test_.parquet', columns=cols_to_load1)
df_test16=pd.read_parquet(r'data/test/1.회원정보/201812_test_.parquet', columns=cols_to_load1)

In [9]:
df_test31=pd.read_parquet(r'data/test/3.승인매출정보/201807_test_.parquet', columns=cols_to_load3)
df_test32=pd.read_parquet(r'data/test/3.승인매출정보/201808_test_.parquet', columns=cols_to_load3)
df_test33=pd.read_parquet(r'data/test/3.승인매출정보/201809_test_.parquet', columns=cols_to_load3)
df_test34=pd.read_parquet(r'data/test/3.승인매출정보/201810_test_.parquet', columns=cols_to_load3)
df_test35=pd.read_parquet(r'data/test/3.승인매출정보/201811_test_.parquet', columns=cols_to_load3)
df_test36=pd.read_parquet(r'data/test/3.승인매출정보/201812_test_.parquet', columns=cols_to_load3)

In [10]:
df_test41=pd.read_parquet(r'data/test/4.청구입금정보/201807_test_.parquet', columns=cols_to_load4)
df_test42=pd.read_parquet(r'data/test/4.청구입금정보/201808_test_.parquet', columns=cols_to_load4)
df_test43=pd.read_parquet(r'data/test/4.청구입금정보/201809_test_.parquet', columns=cols_to_load4)
df_test44=pd.read_parquet(r'data/test/4.청구입금정보/201810_test_.parquet', columns=cols_to_load4)
df_test45=pd.read_parquet(r'data/test/4.청구입금정보/201811_test_.parquet', columns=cols_to_load4)
df_test46=pd.read_parquet(r'data/test/4.청구입금정보/201812_test_.parquet', columns=cols_to_load4)

In [11]:
df_test51=pd.read_parquet(r'data/test/5.잔액정보/201807_test_.parquet', columns=cols_to_load5)
df_test52=pd.read_parquet(r'data/test/5.잔액정보/201808_test_.parquet', columns=cols_to_load5)
df_test53=pd.read_parquet(r'data/test/5.잔액정보/201809_test_.parquet', columns=cols_to_load5)
df_test54=pd.read_parquet(r'data/test/5.잔액정보/201810_test_.parquet', columns=cols_to_load5)
df_test55=pd.read_parquet(r'data/test/5.잔액정보/201811_test_.parquet', columns=cols_to_load5)
df_test56=pd.read_parquet(r'data/test/5.잔액정보/201812_test_.parquet', columns=cols_to_load5)

In [12]:
# 1. 회원정보
train1 = pd.concat([df11, df12, df13, df14, df15, df16], ignore_index=True)

# 2. 승인매출정보
train3 = pd.concat([df31, df32, df33, df34, df35, df36], ignore_index=True)

# 3. 청구입금정보
train4 = pd.concat([df41, df42, df43, df44, df45, df46], ignore_index=True)

# 4. 잔액정보
train5 = pd.concat([df51, df52, df53, df54, df55, df56], ignore_index=True)

In [13]:
# 1. 회원정보
test2_1 = pd.concat([df_test11, df_test12, df_test13, df_test14, df_test15, df_test16], ignore_index=True)

# 2. 승인매출정보
test2_3 = pd.concat([df_test31, df_test32, df_test33, df_test34, df_test35, df_test36], ignore_index=True)

# 3. 청구입금정보
test2_4 = pd.concat([df_test41, df_test42, df_test43, df_test44, df_test45, df_test46], ignore_index=True)

# 4. 잔액정보
test2_5 = pd.concat([df_test51, df_test52, df_test53, df_test54, df_test55, df_test56], ignore_index=True)

In [14]:
# 기준이 되는 데이터프레임부터 시작
VIF_merge_train = train1.copy()

# ID와 기준년월 기준으로 병합
VIF_merge_train = VIF_merge_train.merge(train3, on=['ID', '기준년월'], how='inner')
VIF_merge_train = VIF_merge_train.merge(train4, on=['ID', '기준년월'], how='inner')
VIF_merge_train = VIF_merge_train.merge(train5, on=['ID', '기준년월'], how='inner')

In [15]:
# 기준이 되는 데이터프레임부터 시작
VIF_merge_test = test2_1.copy()

# ID와 기준년월 기준으로 순차 병합
VIF_merge_test = VIF_merge_test.merge(test2_3, on=['ID', '기준년월'], how='inner')
VIF_merge_test = VIF_merge_test.merge(test2_4, on=['ID', '기준년월'], how='inner')
VIF_merge_test = VIF_merge_test.merge(test2_5, on=['ID', '기준년월'], how='inner')

In [16]:
VIF_merge_test=VIF_merge_test.drop(columns=['ID','기준년월'])
VIF_merge_train=VIF_merge_train.drop(columns=['ID', '기준년월'])

In [17]:
VIF_merge_train.to_csv('train_VIF2.csv', index=False, encoding='utf-8-sig')

In [18]:
VIF_merge_test.to_csv('test_VIF2.csv', index=False, encoding='utf-8-sig')