In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import glob

In [4]:
# 경로 지정
path = '/content/drive/MyDrive/파이널 프로젝트/C_D_NotCD/data/'
file_list = glob.glob(path + 'selected(C_D_NotCD)*.csv')

print("파일 리스트 확인:", file_list)

if len(file_list) == 0:
    print("❗ 파일이 없습니다. 경로 또는 패턴을 확인하세요.")
else:
    merged_df = None
    for i, file in enumerate(file_list):
        df = pd.read_csv(file)
        print(f"Loaded: {file.split('/')[-1]} Shape: {df.shape}")

        if merged_df is None:
            merged_df = df
        else:
            merged_df = pd.merge(merged_df, df, on=['기준년월', 'ID'], how='inner')

    print("✅ 최종 병합된 데이터 shape:", merged_df.shape)
    display(merged_df.head())

파일 리스트 확인: ['/content/drive/MyDrive/파이널 프로젝트/C_D_NotCD/data/selected(C_D_NotCD)_1.회원정보.csv', '/content/drive/MyDrive/파이널 프로젝트/C_D_NotCD/data/selected(C_D_NotCD)_2.신용정보.csv', '/content/drive/MyDrive/파이널 프로젝트/C_D_NotCD/data/selected(C_D_NotCD)_3.승인매출정보(1~150).csv', '/content/drive/MyDrive/파이널 프로젝트/C_D_NotCD/data/selected(C_D_NotCD)_3.승인매출정보(151~290).csv', '/content/drive/MyDrive/파이널 프로젝트/C_D_NotCD/data/selected(C_D_NotCD)_4.청구입금정보.csv']
Loaded: selected(C_D_NotCD)_1.회원정보.csv Shape: (477948, 7)
Loaded: selected(C_D_NotCD)_2.신용정보.csv Shape: (477948, 6)
Loaded: selected(C_D_NotCD)_3.승인매출정보(1~150).csv Shape: (477948, 8)
Loaded: selected(C_D_NotCD)_3.승인매출정보(151~290).csv Shape: (477948, 10)
Loaded: selected(C_D_NotCD)_4.청구입금정보.csv Shape: (477948, 5)
✅ 최종 병합된 데이터 shape: (477948, 28)

,기준년월,ID,Group,_1순위카드이용금액,이용금액_R3M_신용체크,이용금액_R3M_신용,거주시도명,카드이용한도금액_B1M,카드이용한도금액_B2M,카드이용한도금액,...,이용금액_오프라인_R3M,_2순위쇼핑업종_이용금액,_3순위업종_이용금액,이용금액_오프라인_B0M,_2순위업종_이용금액,_1순위업종_이용금액,_3순위쇼핑업종_이용금액,청구금액_R6M,청구금액_R3M,청구금액_B0
0,201807,TRAIN_000000,D,3681,196,196,서울,20805,19723,19354,...,4131,0,672,4043,1408,1928,0,88693,46588,12226
1,201807,TRAIN_000002,C,24493,23988,23988,서울,78730,77975,88193,...,12250,1038,1362,4524,1539,16924,924,165221,85931,21866
2,201807,TRAIN_000003,D,5933,3904,3904,부산,20523,19226,19062,...,10408,487,774,3975,2284,2405,0,127371,61518,16356
3,201807,TRAIN_000008,C,68078,124967,121279,서울,199966,208224,199862,...,59760,2590,6245,16045,12427,88663,2162,94241,62715,20512
4,201807,TRAIN_000010,D,18796,21001,21001,전북,100037,100056,100017,...,7066,0,0,2437,4751,8886,0,35723,30449,22512

In [9]:
merged_df.columns

Index(['기준년월', 'ID', 'Group', '_1순위카드이용금액', '이용금액_R3M_신용체크', '이용금액_R3M_신용',
       '거주시도명', '카드이용한도금액_B1M', '카드이용한도금액_B2M', '카드이용한도금액', 'CA한도금액',
       '이용금액_일시불_R12M', '이용금액_일시불_B0M', '이용금액_일시불_R3M', '이용금액_일시불_R6M',
       '최대이용금액_일시불_R12M', '쇼핑_도소매_이용금액', '이용금액_오프라인_R6M', '이용금액_오프라인_R3M',
       '_2순위쇼핑업종_이용금액', '_3순위업종_이용금액', '이용금액_오프라인_B0M', '_2순위업종_이용금액',
       '_1순위업종_이용금액', '_3순위쇼핑업종_이용금액', '청구금액_R6M', '청구금액_R3M', '청구금액_B0'],
      dtype='object')

In [11]:
# 컬럼 제거
selected_df = merged_df.drop(columns=['거주시도명'])

# 컬럼 개수와 shape 확인
print(selected_df.shape)
print(selected_df.columns)

(477948, 27)
Index(['기준년월', 'ID', 'Group', '_1순위카드이용금액', '이용금액_R3M_신용체크', '이용금액_R3M_신용',
       '카드이용한도금액_B1M', '카드이용한도금액_B2M', '카드이용한도금액', 'CA한도금액', '이용금액_일시불_R12M',
       '이용금액_일시불_B0M', '이용금액_일시불_R3M', '이용금액_일시불_R6M', '최대이용금액_일시불_R12M',
       '쇼핑_도소매_이용금액', '이용금액_오프라인_R6M', '이용금액_오프라인_R3M', '_2순위쇼핑업종_이용금액',
       '_3순위업종_이용금액', '이용금액_오프라인_B0M', '_2순위업종_이용금액', '_1순위업종_이용금액',
       '_3순위쇼핑업종_이용금액', '청구금액_R6M', '청구금액_R3M', '청구금액_B0'],
      dtype='object')

In [12]:
# 저장 경로와 파일명
file_path = '/content/drive/MyDrive/파이널 프로젝트/C_D_NotCD/data/Seleted(C_D_NotCD)_delecteE_all_train.parquet'

# parquet 파일로 저장
selected_df.to_parquet(file_path, index=False)

print("✅ parquet 파일로 저장 완료!")

✅ parquet 파일로 저장 완료!

In [ ]:
print(file_list)

[]

# 테스트 데이터 변수 추출

In [ ]:
# 파일 경로 지정
file_path = '/content/drive/MyDrive/파이널 프로젝트/E_NotE/ab_cde_test.parquet'

# parquet 파일 읽기
df = pd.read_parquet(file_path)

# 확인
print(df.shape)
display(df.head())

(600000, 855)

,기준년월,ID,남녀구분코드,연령,회원여부_이용가능,회원여부_이용가능_CA,회원여부_이용가능_카드론,소지여부_신용,소지카드수_유효_신용,소지카드수_이용가능_신용,...,잔액_신판ca최대한도소진율_r3m,변동률_일시불평잔,변동률_RV일시불평잔,변동률_할부평잔,변동률_CA평잔,변동률_RVCA평잔,변동률_카드론평잔,변동률_잔액_B1M,변동률_잔액_일시불_B1M,변동률_잔액_CA_B1M
0,201807,TEST_00000,1,40대,1,1,0,1,2,2,...,0.145300,1.463214,0.999998,0.999998,0.999998,0.999998,0.999998,0.209395,0.231043,0.0
1,201807,TEST_00001,1,60대,1,1,0,1,1,1,...,0.324844,1.315412,0.999998,1.044473,1.991974,0.999998,0.926569,-0.269161,-0.247241,0.0
2,201807,TEST_00002,1,40대,1,1,1,1,2,2,...,0.221608,1.055927,0.999998,1.053083,0.999998,0.999998,0.999998,-0.120290,0.029270,0.0
3,201807,TEST_00003,2,40대,1,1,1,1,1,1,...,0.128337,1.488069,0.999998,1.991630,0.999998,0.999998,0.999998,0.035807,-0.013359,0.0
4,201807,TEST_00004,2,40대,1,0,1,1,1,1,...,0.737263,1.208739,0.999998,1.053743,0.999998,0.999998,0.999998,-0.538740,-0.449378,0.0

In [ ]:
# parquet 파일 경로
file_path = '/content/drive/MyDrive/파이널 프로젝트/E_NotE/ab_cde_test.parquet'

# 불러올 컬럼 리스트
selected_columns = [
    '기준년월','ID', '청구금액_R6M', '청구금액_R3M', '청구금액_B0', '이용금액_일시불_R12M', '_1순위카드이용금액',
    '이용금액_R3M_신용체크', '이용금액_일시불_B0M', '이용금액_일시불_R3M', '이용금액_일시불_R6M', '이용금액_R3M_신용',
    '최대이용금액_일시불_R12M', '이용금액_오프라인_R6M', '쇼핑_도소매_이용금액', '이용금액_오프라인_R3M', '_2순위쇼핑업종_이용금액',
    '_3순위업종_이용금액', '카드이용한도금액_B1M', '카드이용한도금액_B2M', '카드이용한도금액', '이용금액_오프라인_B0M',
    '_2순위업종_이용금액', 'CA한도금액', '_1순위업종_이용금액', '_3순위쇼핑업종_이용금액'
]

# parquet 파일 읽을 때 columns 파라미터 사용
selected_test_df = pd.read_parquet(file_path, columns=selected_columns)

# 확인
print(selected_test_df.shape)
display(selected_test_df.head())

(600000, 26)

,기준년월,ID,청구금액_R6M,청구금액_R3M,청구금액_B0,이용금액_일시불_R12M,_1순위카드이용금액,이용금액_R3M_신용체크,이용금액_일시불_B0M,이용금액_일시불_R3M,...,_2순위쇼핑업종_이용금액,_3순위업종_이용금액,카드이용한도금액_B1M,카드이용한도금액_B2M,카드이용한도금액,이용금액_오프라인_B0M,_2순위업종_이용금액,CA한도금액,_1순위업종_이용금액,_3순위쇼핑업종_이용금액
0,201807,TEST_00000,22151,11441,4931,49063,13852,21458,7650,20503,...,854,1880,49999,50006,50902,9877,2713,18131,4034,643
1,201807,TEST_00001,32878,20522,10152,7771,11065,18681,367,-1832,...,1154,1278,50000,50003,50080,4006,1321,16819,8398,1033
2,201807,TEST_00002,71867,50508,13223,73003,27071,40758,8547,25225,...,1178,2680,100053,100056,100045,11298,7271,30505,7594,1094
3,201807,TEST_00003,4986,4604,2112,7421,4827,5255,1270,2670,...,804,605,21035,19693,18508,976,2043,6402,2835,634
4,201807,TEST_00004,10758,6788,4406,10493,8011,16148,709,2982,...,774,1054,4291,3924,4033,4017,1364,0,3439,760

In [ ]:
# 저장 경로와 파일명
file_path = '/content/drive/MyDrive/파이널 프로젝트/C_D_NotCD/data/Seleted(C_D_NotCD)_all_test.parquet'

# parquet 파일로 저장
selected_test_df.to_parquet(file_path, index=False)

print("✅ parquet 파일로 저장 완료!")

✅ parquet 파일로 저장 완료!

In [ ]:
test_df = pd.read_parquet('/content/drive/MyDrive/파이널 프로젝트/E_NotE/selected(E_NotE)_all_test.parquet')
display(test_df)

,기준년월,ID,이용금액대,할인건수_R3M,방문횟수_앱_R6M,방문횟수_PC_R6M,방문일수_PC_R6M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M,이용금액_오프라인_B0M,...,청구서발송여부_B0,이용개월수_전체_R3M,이용건수_오프라인_R3M,이용후경과월_신용,_2순위업종_이용금액,이용개월수_신용_R6M,정상입금원금_B2M,이용카드수_신용,정상입금원금_B5M,_1순위카드이용건수
0,201807,TEST_00000,02.50만원+,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,9877,...,1,2,48,0,2713,5,1172,2,1504,51
1,201807,TEST_00001,02.50만원+,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,4006,...,1,3,14,0,1321,6,4509,1,2763,40
2,201807,TEST_00002,01.100만원+,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,11298,...,1,3,151,1,7271,6,11366,2,11267,154
3,201807,TEST_00003,04.10만원+,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,976,...,1,3,27,0,2043,5,875,1,0,105
4,201807,TEST_00004,03.30만원+,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,4017,...,1,3,31,0,1364,6,1618,2,1347,52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,201812,TEST_99995,09.미사용,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,0,...,0,0,0,12,0,0,0,0,0,-2
599996,201812,TEST_99996,05.10만원-,1회 이상,10회 이상,1회 이상,1회 이상,1회 이상,1회 이상,407,...,1,3,13,0,0,6,252,1,302,4
599997,201812,TEST_99997,09.미사용,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,0,...,0,0,0,12,0,0,0,0,0,6
599998,201812,TEST_99998,01.100만원+,1회 이상,40회 이상,1회 이상,1회 이상,1회 이상,1회 이상,15388,...,1,3,197,0,16296,6,2751,4,6215,185
599999,201812,TEST_99999,05.10만원-,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,8,...,1,3,4,2,0,6,18,2,16,0