In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import glob

In [3]:
# 경로 지정
path = '/content/drive/MyDrive/파이널 프로젝트/C_D/data/'
file_list = glob.glob(path + 'selected(C_D)*.csv')

print("파일 리스트 확인:", file_list)

if len(file_list) == 0:
    print("❗ 파일이 없습니다. 경로 또는 패턴을 확인하세요.")
else:
    merged_df = None
    for i, file in enumerate(file_list):
        df = pd.read_csv(file)
        print(f"Loaded: {file.split('/')[-1]} Shape: {df.shape}")

        if merged_df is None:
            merged_df = df
        else:
            merged_df = pd.merge(merged_df, df, on=['기준년월', 'ID'], how='inner')

    print("✅ 최종 병합된 데이터 shape:", merged_df.shape)
    display(merged_df.head())

파일 리스트 확인: ['/content/drive/MyDrive/파이널 프로젝트/C_D/data/selected(C_D)_1.회원정보.csv', '/content/drive/MyDrive/파이널 프로젝트/C_D/data/selected(C_D)_3.승인매출정보(1~150).csv', '/content/drive/MyDrive/파이널 프로젝트/C_D/data/selected(C_D)_3.승인매출정보(151~290).csv', '/content/drive/MyDrive/파이널 프로젝트/C_D/data/selected(C_D)_3.승인매출정보(291~406).csv', '/content/drive/MyDrive/파이널 프로젝트/C_D/data/selected(C_D)_4.청구입금정보.csv', '/content/drive/MyDrive/파이널 프로젝트/C_D/data/selected(C_D)_6.채널정보.csv']
Loaded: selected(C_D)_1.회원정보.csv Shape: (476832, 8)
Loaded: selected(C_D)_3.승인매출정보(1~150).csv Shape: (476832, 27)
Loaded: selected(C_D)_3.승인매출정보(151~290).csv Shape: (476832, 11)
Loaded: selected(C_D)_3.승인매출정보(291~406).csv Shape: (476832, 11)
Loaded: selected(C_D)_4.청구입금정보.csv Shape: (476832, 8)
Loaded: selected(C_D)_6.채널정보.csv Shape: (476832, 7)
✅ 최종 병합된 데이터 shape: (476832, 62)

,기준년월,ID,Segment,이용금액_R3M_신용체크,_1순위카드이용금액,이용금액_R3M_신용,이용카드수_신용체크,Life_Stage,이용개월수_신용_R12M,이용개월수_신판_R12M,...,청구금액_R3M,청구금액_B0,청구서발송여부_B0,할인건수_R3M,할인건수_B0M,방문횟수_앱_R6M,방문횟수_PC_R6M,방문일수_PC_R6M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M
0,201807,TRAIN_000000,D,196,3681,196,1,자녀성장(2),12,12,...,46588,12226,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,10회 이상,10회 이상
1,201807,TRAIN_000002,C,23988,24493,23988,1,자녀출산기,9,9,...,85931,21866,1,1회 이상,1회 이상,30회 이상,10회 이상,10회 이상,1회 이상,1회 이상
2,201807,TRAIN_000003,D,3904,5933,3904,1,자녀성장(2),12,12,...,61518,16356,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,10회 이상,10회 이상
3,201807,TRAIN_000008,C,124967,68078,121279,5,자녀출산기,12,12,...,62715,20512,1,10회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
4,201807,TRAIN_000010,D,21001,18796,21001,1,자녀성장(1),12,12,...,30449,22512,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상

In [5]:
# 저장 경로와 파일명
file_path = '/content/drive/MyDrive/파이널 프로젝트/C_D/data/Seleted(C_D_NotCD)_delecteABE_all_train.parquet'

# parquet 파일로 저장
merged_df.to_parquet(file_path, index=False)

print("✅ parquet 파일로 저장 완료!")

✅ parquet 파일로 저장 완료!

In [7]:
merged_df.columns

Index(['기준년월', 'ID', 'Segment', '이용금액_R3M_신용체크', '_1순위카드이용금액', '이용금액_R3M_신용',
       '이용카드수_신용체크', 'Life_Stage', '이용개월수_신용_R12M', '이용개월수_신판_R12M',
       '이용개월수_일시불_R12M', '이용금액_일시불_R6M', '이용금액_일시불_B0M', '이용금액_일시불_R3M',
       '이용금액_일시불_R12M', '이용개월수_신용_R6M', '이용건수_신용_R6M', '이용건수_신용_B0M',
       '이용건수_신판_R6M', '이용건수_신용_R3M', '이용건수_신판_B0M', '이용건수_일시불_R6M',
       '이용건수_신판_R3M', '이용건수_일시불_B0M', '이용개월수_신판_R6M', '이용건수_일시불_R3M',
       '이용개월수_일시불_R6M', '이용후경과월_신판', '이용건수_신용_R12M', '이용건수_신판_R12M',
       '이용건수_일시불_R12M', '이용가맹점수', '이용후경과월_신용', '이용금액_오프라인_B0M',
       '이용금액_오프라인_R3M', '이용건수_오프라인_B0M', '_3순위업종_이용금액', '_3순위쇼핑업종_이용금액',
       '_2순위업종_이용금액', '이용개월수_오프라인_R6M', '이용금액_오프라인_R6M', '_2순위쇼핑업종_이용금액',
       '정상청구원금_B5M', '정상청구원금_B2M', '연속유실적개월수_기본_24M_카드', '정상청구원금_B0M',
       '정상입금원금_B0M', '정상입금원금_B5M', '정상입금원금_B2M', '이용개월수_전체_R6M',
       '이용개월수_전체_R3M', '청구금액_R6M', '청구금액_R3M', '청구금액_B0', '청구서발송여부_B0',
       '할인건수_R3M', '할인건수_B0M', '방문횟수_앱_R6M', '방문횟수_PC_R6M', '방문일수_PC_R6M',
       '인입횟수_ARS_R6M', '이용메뉴건수_ARS_R6M'],
      dtype='object')

# 테스트 데이터 변수 추출

In [6]:
# 파일 경로 지정 '/content/drive/MyDrive/파이널 프로젝트/E_NotE/ab_cde_test.parquet' -> test 전체 데이터
file_path = '/content/drive/MyDrive/파이널 프로젝트/E_NotE/ab_cde_test.parquet'

# parquet 파일 읽기
df = pd.read_parquet(file_path)

# 확인
print(df.shape)
display(df.head())

(600000, 855)

,기준년월,ID,남녀구분코드,연령,회원여부_이용가능,회원여부_이용가능_CA,회원여부_이용가능_카드론,소지여부_신용,소지카드수_유효_신용,소지카드수_이용가능_신용,...,잔액_신판ca최대한도소진율_r3m,변동률_일시불평잔,변동률_RV일시불평잔,변동률_할부평잔,변동률_CA평잔,변동률_RVCA평잔,변동률_카드론평잔,변동률_잔액_B1M,변동률_잔액_일시불_B1M,변동률_잔액_CA_B1M
0,201807,TEST_00000,1,40대,1,1,0,1,2,2,...,0.145300,1.463214,0.999998,0.999998,0.999998,0.999998,0.999998,0.209395,0.231043,0.0
1,201807,TEST_00001,1,60대,1,1,0,1,1,1,...,0.324844,1.315412,0.999998,1.044473,1.991974,0.999998,0.926569,-0.269161,-0.247241,0.0
2,201807,TEST_00002,1,40대,1,1,1,1,2,2,...,0.221608,1.055927,0.999998,1.053083,0.999998,0.999998,0.999998,-0.120290,0.029270,0.0
3,201807,TEST_00003,2,40대,1,1,1,1,1,1,...,0.128337,1.488069,0.999998,1.991630,0.999998,0.999998,0.999998,0.035807,-0.013359,0.0
4,201807,TEST_00004,2,40대,1,0,1,1,1,1,...,0.737263,1.208739,0.999998,1.053743,0.999998,0.999998,0.999998,-0.538740,-0.449378,0.0

In [8]:
# parquet 파일 경로
file_path = '/content/drive/MyDrive/파이널 프로젝트/E_NotE/ab_cde_test.parquet'

# 불러올 컬럼 리스트
selected_columns = [
        '기준년월', 'ID', '이용금액_R3M_신용체크', '_1순위카드이용금액', '이용금액_R3M_신용',
       '이용카드수_신용체크', 'Life_Stage', '이용개월수_신용_R12M', '이용개월수_신판_R12M',
       '이용개월수_일시불_R12M', '이용금액_일시불_R6M', '이용금액_일시불_B0M', '이용금액_일시불_R3M',
       '이용금액_일시불_R12M', '이용개월수_신용_R6M', '이용건수_신용_R6M', '이용건수_신용_B0M',
       '이용건수_신판_R6M', '이용건수_신용_R3M', '이용건수_신판_B0M', '이용건수_일시불_R6M',
       '이용건수_신판_R3M', '이용건수_일시불_B0M', '이용개월수_신판_R6M', '이용건수_일시불_R3M',
       '이용개월수_일시불_R6M', '이용후경과월_신판', '이용건수_신용_R12M', '이용건수_신판_R12M',
       '이용건수_일시불_R12M', '이용가맹점수', '이용후경과월_신용', '이용금액_오프라인_B0M',
       '이용금액_오프라인_R3M', '이용건수_오프라인_B0M', '_3순위업종_이용금액', '_3순위쇼핑업종_이용금액',
       '_2순위업종_이용금액', '이용개월수_오프라인_R6M', '이용금액_오프라인_R6M', '_2순위쇼핑업종_이용금액',
       '정상청구원금_B5M', '정상청구원금_B2M', '연속유실적개월수_기본_24M_카드', '정상청구원금_B0M',
       '정상입금원금_B0M', '정상입금원금_B5M', '정상입금원금_B2M', '이용개월수_전체_R6M',
       '이용개월수_전체_R3M', '청구금액_R6M', '청구금액_R3M', '청구금액_B0', '청구서발송여부_B0',
       '할인건수_R3M', '할인건수_B0M', '방문횟수_앱_R6M', '방문횟수_PC_R6M', '방문일수_PC_R6M',
       '인입횟수_ARS_R6M', '이용메뉴건수_ARS_R6M'
]

# parquet 파일 읽을 때 columns 파라미터 사용
selected_test_df = pd.read_parquet(file_path, columns=selected_columns)

# 확인
print(selected_test_df.shape)
display(selected_test_df.head())

(600000, 61)

,기준년월,ID,이용금액_R3M_신용체크,_1순위카드이용금액,이용금액_R3M_신용,이용카드수_신용체크,Life_Stage,이용개월수_신용_R12M,이용개월수_신판_R12M,이용개월수_일시불_R12M,...,청구금액_R3M,청구금액_B0,청구서발송여부_B0,할인건수_R3M,할인건수_B0M,방문횟수_앱_R6M,방문횟수_PC_R6M,방문일수_PC_R6M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M
0,201807,TEST_00000,21458,13852,21458,2,자녀성장(1),10,10,10,...,11441,4931,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
1,201807,TEST_00001,18681,11065,10759,2,자녀독립기,9,9,9,...,20522,10152,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
2,201807,TEST_00002,40758,27071,40758,2,자녀성장(1),12,12,12,...,50508,13223,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
3,201807,TEST_00003,5255,4827,5255,1,자녀성장(1),9,9,9,...,4604,2112,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
4,201807,TEST_00004,16148,8011,14290,3,자녀성장(1),12,12,12,...,6788,4406,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상

In [9]:
# 저장 경로와 파일명
file_path = '/content/drive/MyDrive/파이널 프로젝트/C_D/data/Seleted(C_D)_delecteABE_all_test.parquet'

# parquet 파일로 저장
selected_test_df.to_parquet(file_path, index=False)

print("✅ parquet 파일로 저장 완료!")

✅ parquet 파일로 저장 완료!