In [1]:
# 기본
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 경고 뜨지 않게 설정
import warnings
warnings.filterwarnings('ignore')

# 그래프 설정
sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False

# 데이터 전처리 알고리즘
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# 학습용과 검증용으로 나누는 함수
from sklearn.model_selection import train_test_split

# 교차 검증
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

# 평가함수
# 분류용
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

# 회귀용
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

# 모델의 최적의 하이퍼 파라미터를 찾기 위한 도구
from sklearn.model_selection import GridSearchCV

# 머신러닝 알고리즘 - 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import VotingClassifier

# 머신러닝 알고리즘 - 회귀
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from sklearn.ensemble import VotingRegressor

# 학습 모델 저장을 위한 라이브러리
import pickle

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
# 학습이 완료된 모델을 저장할 파일 이름
best_model_path = '/content/drive/MyDrive/은서님 파일/best_model_cd_4.dat'

In [4]:
with open(best_model_path, 'rb') as fp :
    best_model = pickle.load(fp)
    scalerX = pickle.load(fp)
    scaler_columns = pickle.load(fp)
    le = pickle.load(fp)
    Encoder1 = pickle.load(fp)
    Encoder2 = pickle.load(fp)
    Encoder3 = pickle.load(fp)
    Encoder4 = pickle.load(fp)
    Encoder5 = pickle.load(fp)
    Encoder6 = pickle.load(fp)
    Encoder7 = pickle.load(fp)
    Encoder8 = pickle.load(fp)

display(best_model)
display(scalerX)
display(scaler_columns)
display(le)
display(Encoder1)
display(Encoder2)
display(Encoder3)
display(Encoder4)
display(Encoder5)
display(Encoder6)
display(Encoder7)
display(Encoder8)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=-1,
              num_parallel_tree=None, predictor='gpu_predictor', ...)

StandardScaler()

['연체입금원금_B5M',
 '연체입금원금_B2M',
 '이용금액_R3M_신용체크',
 '_1순위카드이용금액',
 '이용금액_R3M_신용',
 '이용카드수_신용체크',
 'Life_Stage',
 '이용개월수_신용_R12M',
 '이용개월수_신판_R12M',
 '이용개월수_일시불_R12M',
 '이용금액_일시불_R6M',
 '이용금액_일시불_B0M',
 '이용금액_일시불_R3M',
 '이용금액_일시불_R12M',
 '이용개월수_신용_R6M',
 '이용건수_신용_R6M',
 '이용건수_신용_B0M',
 '이용건수_신판_R6M',
 '이용건수_신용_R3M',
 '이용건수_신판_B0M',
 '이용건수_일시불_R6M',
 '이용건수_신판_R3M',
 '이용건수_일시불_B0M',
 '이용개월수_신판_R6M',
 '이용건수_일시불_R3M',
 '이용개월수_일시불_R6M',
 '이용후경과월_신판',
 '이용건수_신용_R12M',
 '이용건수_신판_R12M',
 '이용건수_일시불_R12M',
 '이용가맹점수',
 '이용후경과월_신용',
 '이용금액_오프라인_B0M',
 '이용금액_오프라인_R3M',
 '이용건수_오프라인_B0M',
 '_3순위업종_이용금액',
 '_3순위쇼핑업종_이용금액',
 '_2순위업종_이용금액',
 '이용개월수_오프라인_R6M',
 '이용금액_오프라인_R6M',
 '_2순위쇼핑업종_이용금액',
 '정상청구원금_B5M',
 '정상청구원금_B2M',
 '연속유실적개월수_기본_24M_카드',
 '정상청구원금_B0M',
 '정상입금원금_B0M',
 '정상입금원금_B5M',
 '정상입금원금_B2M',
 '이용개월수_전체_R6M',
 '이용개월수_전체_R3M',
 '청구금액_R6M',
 '청구금액_R3M',
 '청구금액_B0',
 '청구서발송여부_B0',
 '할인건수_R3M',
 '할인건수_B0M',
 '방문횟수_앱_R6M',
 '방문횟수_PC_R6M',
 '방문일수_PC_R6M',
 '인입횟수_ARS_R6M',
 '이용메뉴건수_ARS_R6M']

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

### Target

In [5]:
tg_df = pd.read_csv('/content/drive/MyDrive/Segment.csv')
tg_df = tg_df['Segment']
tg_df

0          D
1          E
2          C
3          D
4          E
          ..
2399995    E
2399996    D
2399997    C
2399998    E
2399999    E
Name: Segment, Length: 2400000, dtype: object

In [6]:
test_cols =['기준년월','ID','연체입금원금_B5M', '연체입금원금_B2M', '이용금액_R3M_신용체크', '_1순위카드이용금액',
       '이용금액_R3M_신용', '이용카드수_신용체크', 'Life_Stage', '이용개월수_신용_R12M',
       '이용개월수_신판_R12M', '이용개월수_일시불_R12M', '이용금액_일시불_R6M', '이용금액_일시불_B0M',
       '이용금액_일시불_R3M', '이용금액_일시불_R12M', '이용개월수_신용_R6M', '이용건수_신용_R6M',
       '이용건수_신용_B0M', '이용건수_신판_R6M', '이용건수_신용_R3M', '이용건수_신판_B0M',
       '이용건수_일시불_R6M', '이용건수_신판_R3M', '이용건수_일시불_B0M', '이용개월수_신판_R6M',
       '이용건수_일시불_R3M', '이용개월수_일시불_R6M', '이용후경과월_신판', '이용건수_신용_R12M',
       '이용건수_신판_R12M', '이용건수_일시불_R12M', '이용가맹점수', '이용후경과월_신용', '이용금액_오프라인_B0M',
       '이용금액_오프라인_R3M', '이용건수_오프라인_B0M', '_3순위업종_이용금액', '_3순위쇼핑업종_이용금액',
       '_2순위업종_이용금액', '이용개월수_오프라인_R6M', '이용금액_오프라인_R6M', '_2순위쇼핑업종_이용금액',
       '정상청구원금_B5M', '정상청구원금_B2M', '연속유실적개월수_기본_24M_카드', '정상청구원금_B0M',
       '정상입금원금_B0M', '정상입금원금_B5M', '정상입금원금_B2M', '이용개월수_전체_R6M',
       '이용개월수_전체_R3M', '청구금액_R6M', '청구금액_R3M', '청구금액_B0', '청구서발송여부_B0',
       '할인건수_R3M', '할인건수_B0M', '방문횟수_앱_R6M', '방문횟수_PC_R6M', '방문일수_PC_R6M',
       '인입횟수_ARS_R6M', '이용메뉴건수_ARS_R6M']

In [7]:
# 예측할 데이터를 읽어온다.
df1 = pd.read_parquet('/content/drive/MyDrive/abcde/ab_cde_test.parquet')
df1 = df1[test_cols]
df1

,기준년월,ID,연체입금원금_B5M,연체입금원금_B2M,이용금액_R3M_신용체크,_1순위카드이용금액,이용금액_R3M_신용,이용카드수_신용체크,Life_Stage,이용개월수_신용_R12M,...,청구금액_R3M,청구금액_B0,청구서발송여부_B0,할인건수_R3M,할인건수_B0M,방문횟수_앱_R6M,방문횟수_PC_R6M,방문일수_PC_R6M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M
0,201807,TEST_00000,2414,840,21458,13852,21458,2,자녀성장(1),10,...,11441,4931,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
1,201807,TEST_00001,2959,763,18681,11065,10759,2,자녀독립기,9,...,20522,10152,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
2,201807,TEST_00002,0,0,40758,27071,40758,2,자녀성장(1),12,...,50508,13223,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
3,201807,TEST_00003,0,196,5255,4827,5255,1,자녀성장(1),9,...,4604,2112,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
4,201807,TEST_00004,0,0,16148,8011,14290,3,자녀성장(1),12,...,6788,4406,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,201812,TEST_99995,0,0,0,0,0,0,노년생활,0,...,0,0,0,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
599996,201812,TEST_99996,689,0,3110,1231,3110,1,자녀출산기,10,...,1256,359,1,1회 이상,1회 이상,10회 이상,1회 이상,1회 이상,1회 이상,1회 이상
599997,201812,TEST_99997,0,186,0,0,0,0,자녀성장(1),0,...,0,0,0,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
599998,201812,TEST_99998,12448,9018,173263,63592,113786,6,가족구축기,12,...,48141,21273,1,1회 이상,1회 이상,40회 이상,1회 이상,1회 이상,1회 이상,1회 이상
599999,201812,TEST_99999,8,0,3016,-574,3016,2,자녀출산기,12,...,56,18,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상

In [8]:
notE = pd.read_csv('/content/drive/MyDrive/은서님 파일/model3_notE.csv')
notE

               ID Segment
0      TEST_00002   Not_E
1      TEST_00010   Not_E
2      TEST_00012   Not_E
3      TEST_00016   Not_E
4      TEST_00032   Not_E
...           ...     ...
16078  TEST_99957   Not_E
16079  TEST_99961   Not_E
16080  TEST_99982   Not_E
16081  TEST_99994   Not_E
16082  TEST_99998   Not_E

[16083 rows x 2 columns]

In [9]:
# 1. 'Not_E'인 ID만 필터링
filtered_ids1 = notE[notE['Segment'] == 'Not_E']['ID']

# 2. df2에서 해당 ID만 골라오기
df2 = df1[df1['ID'].isin(filtered_ids1)]

In [10]:
df2

,기준년월,ID,연체입금원금_B5M,연체입금원금_B2M,이용금액_R3M_신용체크,_1순위카드이용금액,이용금액_R3M_신용,이용카드수_신용체크,Life_Stage,이용개월수_신용_R12M,...,청구금액_R3M,청구금액_B0,청구서발송여부_B0,할인건수_R3M,할인건수_B0M,방문횟수_앱_R6M,방문횟수_PC_R6M,방문일수_PC_R6M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M
2,201807,TEST_00002,0,0,40758,27071,40758,2,자녀성장(1),12,...,50508,13223,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
10,201807,TEST_00010,1304,1150,45764,7544,7024,2,자녀성장(1),11,...,6847,0,0,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
12,201807,TEST_00012,3924,0,37849,24425,37849,2,자녀성장(2),12,...,33803,7283,1,10회 이상,1회 이상,1회 이상,1회 이상,1회 이상,10회 이상,10회 이상
16,201807,TEST_00016,8191,5958,51440,42636,51440,2,자녀출산기,12,...,41328,12194,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
32,201807,TEST_00032,306,0,54632,3885,4259,2,자녀출산기,12,...,4259,769,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599957,201812,TEST_99957,3411,2557,61148,38644,59950,4,자녀성장(1),12,...,28638,14349,1,1회 이상,1회 이상,40회 이상,40회 이상,30회 이상,1회 이상,1회 이상
599961,201812,TEST_99961,5812,3274,30318,25961,30318,1,자녀성장(2),12,...,26095,7195,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,10회 이상
599982,201812,TEST_99982,6871,2643,94440,70955,94440,1,노년생활,12,...,65023,11710,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
599994,201812,TEST_99994,9708,0,31697,29020,31697,1,자녀성장(2),9,...,98428,28423,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,20회 이상
599998,201812,TEST_99998,12448,9018,173263,63592,113786,6,가족구축기,12,...,48141,21273,1,1회 이상,1회 이상,40회 이상,1회 이상,1회 이상,1회 이상,1회 이상

In [11]:
notAB = pd.read_csv('/content/drive/MyDrive/은서님 파일/model3_notAB.csv')
notAB

               ID Segment
0      TEST_00002   notAB
1      TEST_00010   notAB
2      TEST_00012   notAB
3      TEST_00016   notAB
4      TEST_00032   notAB
...           ...     ...
16063  TEST_99957   notAB
16064  TEST_99961   notAB
16065  TEST_99982   notAB
16066  TEST_99994   notAB
16067  TEST_99998   notAB

[16068 rows x 2 columns]

In [12]:
# 1. 'Not_E'인 ID만 필터링
filtered_ids2 = notAB[notAB['Segment'] == 'notAB']['ID']

# 2. df2에서 해당 ID만 골라오기
Xtest_df = df2[df2['ID'].isin(filtered_ids2)]

In [13]:
Xtest_df

,기준년월,ID,연체입금원금_B5M,연체입금원금_B2M,이용금액_R3M_신용체크,_1순위카드이용금액,이용금액_R3M_신용,이용카드수_신용체크,Life_Stage,이용개월수_신용_R12M,...,청구금액_R3M,청구금액_B0,청구서발송여부_B0,할인건수_R3M,할인건수_B0M,방문횟수_앱_R6M,방문횟수_PC_R6M,방문일수_PC_R6M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M
2,201807,TEST_00002,0,0,40758,27071,40758,2,자녀성장(1),12,...,50508,13223,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
10,201807,TEST_00010,1304,1150,45764,7544,7024,2,자녀성장(1),11,...,6847,0,0,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
12,201807,TEST_00012,3924,0,37849,24425,37849,2,자녀성장(2),12,...,33803,7283,1,10회 이상,1회 이상,1회 이상,1회 이상,1회 이상,10회 이상,10회 이상
16,201807,TEST_00016,8191,5958,51440,42636,51440,2,자녀출산기,12,...,41328,12194,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
32,201807,TEST_00032,306,0,54632,3885,4259,2,자녀출산기,12,...,4259,769,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599957,201812,TEST_99957,3411,2557,61148,38644,59950,4,자녀성장(1),12,...,28638,14349,1,1회 이상,1회 이상,40회 이상,40회 이상,30회 이상,1회 이상,1회 이상
599961,201812,TEST_99961,5812,3274,30318,25961,30318,1,자녀성장(2),12,...,26095,7195,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,10회 이상
599982,201812,TEST_99982,6871,2643,94440,70955,94440,1,노년생활,12,...,65023,11710,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
599994,201812,TEST_99994,9708,0,31697,29020,31697,1,자녀성장(2),9,...,98428,28423,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,20회 이상
599998,201812,TEST_99998,12448,9018,173263,63592,113786,6,가족구축기,12,...,48141,21273,1,1회 이상,1회 이상,40회 이상,1회 이상,1회 이상,1회 이상,1회 이상

In [14]:
X_test = Xtest_df.drop(columns=['기준년월','ID'])
X_test = X_test[scaler_columns]

In [15]:
X_test

,연체입금원금_B5M,연체입금원금_B2M,이용금액_R3M_신용체크,_1순위카드이용금액,이용금액_R3M_신용,이용카드수_신용체크,Life_Stage,이용개월수_신용_R12M,이용개월수_신판_R12M,이용개월수_일시불_R12M,...,청구금액_R3M,청구금액_B0,청구서발송여부_B0,할인건수_R3M,할인건수_B0M,방문횟수_앱_R6M,방문횟수_PC_R6M,방문일수_PC_R6M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M
2,0,0,40758,27071,40758,2,자녀성장(1),12,12,12,...,50508,13223,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
10,1304,1150,45764,7544,7024,2,자녀성장(1),11,11,11,...,6847,0,0,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
12,3924,0,37849,24425,37849,2,자녀성장(2),12,12,12,...,33803,7283,1,10회 이상,1회 이상,1회 이상,1회 이상,1회 이상,10회 이상,10회 이상
16,8191,5958,51440,42636,51440,2,자녀출산기,12,12,12,...,41328,12194,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
32,306,0,54632,3885,4259,2,자녀출산기,12,12,12,...,4259,769,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599957,3411,2557,61148,38644,59950,4,자녀성장(1),12,12,12,...,28638,14349,1,1회 이상,1회 이상,40회 이상,40회 이상,30회 이상,1회 이상,1회 이상
599961,5812,3274,30318,25961,30318,1,자녀성장(2),12,12,12,...,26095,7195,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,10회 이상
599982,6871,2643,94440,70955,94440,1,노년생활,12,12,12,...,65023,11710,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
599994,9708,0,31697,29020,31697,1,자녀성장(2),9,9,9,...,98428,28423,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,20회 이상
599998,12448,9018,173263,63592,113786,6,가족구축기,12,12,12,...,48141,21273,1,1회 이상,1회 이상,40회 이상,1회 이상,1회 이상,1회 이상,1회 이상

In [16]:
X_test['할인건수_R3M'] = Encoder1.transform(X_test['할인건수_R3M'])
X_test['할인건수_B0M'] = Encoder2.transform(X_test['할인건수_B0M'])
X_test['방문횟수_앱_R6M'] = Encoder3.transform(X_test['방문횟수_앱_R6M'])
X_test['방문횟수_PC_R6M'] = Encoder4.transform(X_test['방문횟수_PC_R6M'])
X_test['인입횟수_ARS_R6M'] = Encoder5.transform(X_test['인입횟수_ARS_R6M'])
X_test['Life_Stage'] = Encoder6.transform(X_test['Life_Stage'])
X_test['이용메뉴건수_ARS_R6M'] = Encoder7.transform(X_test['이용메뉴건수_ARS_R6M'])
X_test['방문일수_PC_R6M'] = Encoder8.transform(X_test['방문일수_PC_R6M'])

In [17]:
# 데이터 표준화
scaled_data = scalerX.transform(X_test)
scaled_data

array([[-0.65785815, -0.59918034,  0.38005302, ...,  0.07669481,
         0.22070759,  0.09921615],
       [-0.31734976, -0.29120081,  0.54351191, ...,  0.07669481,
         0.22070759,  0.09921615],
       [ 0.36680054, -0.59918034,  0.28506662, ...,  0.07669481,
        -4.53088177, -3.58425652],
       ...,
       [ 1.13633906,  0.10863697,  2.13290962, ...,  0.07669481,
         0.22070759,  0.09921615],
       [ 1.87715371, -0.59918034,  0.08418785, ...,  0.07669481,
         0.22070759,  3.78268882],
       [ 2.59263913,  1.8159148 ,  4.70668512, ...,  0.07669481,
         0.22070759,  0.09921615]])

In [18]:
# 입력데이터를 test_X 변수에 담아준다.
X_text2 = scaled_data

In [19]:
# 예측한다.
y_pred = best_model.predict(X_text2)
y_pred_labels = le.inverse_transform(y_pred)
y_pred_labels

array(['D', 'D', 'D', ..., 'C', 'D', 'C'], dtype=object)

In [20]:
# 결과를 붙힌다음 저장한다.
# 예측할 데이터를 다시 불러온다.
result_df = Xtest_df
result_df['Segment'] = y_pred_labels

In [21]:
result_df2 = result_df[['ID', 'Segment']]

In [22]:
result_df2['Segment'].value_counts()

Segment
D    70208
C    26200
Name: count, dtype: int64

In [23]:
most_common_by_id = result_df2.groupby('ID')['Segment'] \
    .agg(lambda x: x.mode().iloc[0]) \
    .reset_index()

# 컬럼명 확인
most_common_by_id.columns = ['ID', 'Segment']

In [24]:
most_common_by_id

               ID Segment
0      TEST_00002       D
1      TEST_00010       D
2      TEST_00012       D
3      TEST_00016       D
4      TEST_00032       D
...           ...     ...
16063  TEST_99957       D
16064  TEST_99961       C
16065  TEST_99982       C
16066  TEST_99994       D
16067  TEST_99998       C

[16068 rows x 2 columns]

In [25]:
most_common_by_id['Segment'].value_counts()

Segment
D    11582
C     4486
Name: count, dtype: int64

In [26]:
most_common_by_id.to_csv('/content/drive/MyDrive/은서님 파일/model8459_C,D.csv', index=False, encoding='utf-8-sig')
print('저장완료')

저장완료