In [ ]:
# 기본
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 경고 뜨지 않게 설정
import warnings
warnings.filterwarnings('ignore')

# 그래프 설정
sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False

# 데이터 전처리 알고리즘
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# 학습용과 검증용으로 나누는 함수
from sklearn.model_selection import train_test_split

# 교차 검증
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

# 평가함수
# 분류용
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

# 회귀용
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

# 모델의 최적의 하이퍼 파라미터를 찾기 위한 도구
from sklearn.model_selection import GridSearchCV

# 머신러닝 알고리즘 - 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import VotingClassifier

# 머신러닝 알고리즘 - 회귀
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from sklearn.ensemble import VotingRegressor

# 학습 모델 저장을 위한 라이브러리
import pickle

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# 학습이 완료된 모델을 저장할 파일 이름
best_model_path = '/content/drive/MyDrive/은서님 파일/best_model_cd_10.dat'

In [ ]:
with open(best_model_path, 'rb') as fp :
    best_model = pickle.load(fp)
    scalerX = pickle.load(fp)
    scaler_columns = pickle.load(fp)
    le = pickle.load(fp)
    Encoder1 = pickle.load(fp)
    Encoder2 = pickle.load(fp)
    Encoder3 = pickle.load(fp)
    Encoder4 = pickle.load(fp)
    Encoder5 = pickle.load(fp)
    Encoder6 = pickle.load(fp)
    Encoder7 = pickle.load(fp)
    Encoder8 = pickle.load(fp)

display(best_model)
display(scalerX)
display(scaler_columns)
display(le)
display(Encoder1)
display(Encoder2)
display(Encoder3)
display(Encoder4)
display(Encoder5)
display(Encoder6)
display(Encoder7)
display(Encoder8)

XGBClassifier(base_score=None, booster='gbtree', callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=np.float64(0.993330963808734), device=None,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, feature_types=None,
              gamma=np.float64(0.4818099885446264), grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=np.float64(0.26590283664020803), max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=7, max_leaves=None,
              min_child_weight=5, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=259, n_jobs=-1,
              num_parallel_tree=None, predictor='gpu_predictor', ...)

StandardScaler()

['연체입금원금_B5M',
 '연체입금원금_B2M',
 '이용건수_오프라인_R3M',
 '이용개월수_신용_R3M',
 '이용카드수_신용',
 '_1순위카드이용건수',
 '이용건수_오프라인_R6M',
 '청구서발송여부_R3M',
 '최대이용금액_일시불_R12M',
 '이용개월수_신판_R3M',
 '이용개월수_일시불_R3M',
 '쇼핑_도소매_이용금액',
 '_1순위교통업종_이용금액',
 '최종이용일자_할부',
 '이용후경과월_일시불',
 '연속무실적개월수_기본_24M_카드',
 '이용개월수_온라인_R6M',
 '이용가능카드수_신용체크',
 '쇼핑_슈퍼마켓_이용금액',
 '_1순위업종_이용금액',
 '이용개월수_간편결제_R6M',
 '이용개월수_페이_온라인_R6M',
 '유효카드수_신용체크',
 '평잔_일시불_6M',
 '이용여부_3M_해외겸용_본인',
 '쇼핑_마트_이용금액',
 '이용가능카드수_신용',
 '교통_주유이용금액',
 '이용건수_간편결제_R3M',
 '이용건수_간편결제_B0M',
 '이용건수_간편결제_R6M',
 '평잔_일시불_3M',
 '월중평잔_일시불',
 '월중평잔_일시불_B0M',
 '_2순위카드이용건수',
 '청구서발송여부_R6M',
 '이용후경과월_할부',
 '_2순위교통업종_이용금액',
 '이용건수_페이_온라인_R6M',
 '이용후경과월_할부_무이자',
 '유효카드수_신용',
 '이용건수_온라인_B0M',
 '_2순위카드이용금액',
 '이용건수_온라인_R3M',
 '이용개월수_할부_R12M',
 '잔액_일시불_B0M',
 '이용건수_페이_온라인_R3M',
 '이용건수_온라인_R6M',
 '최대이용금액_할부_R12M',
 '이용금액_페이_온라인_B0M',
 '소지카드수_이용가능_신용',
 '이용개월수_할부_무이자_R12M',
 '이용건수_페이_온라인_B0M',
 '이용여부_3M_해외겸용_신용_본인',
 '변동률_RVCA평잔',
 '이용금액_온라인_B0M',
 '이용개월수_결제일_R6M',
 '잔액_신판ca최대한도소진율_r6m',
 '최종이용일자_일시불',
 '최대이용금액_할부_무이자_R12M',
 '소지카드수_유효_신용',
 '변동률_RV일시불평잔',
 '혜택수혜금액',
 '이용금액_할부_R12M',
 '최종이용일자_신판',
 '쇼핑_기타_이용금액',
 '최종이용일자_기본',
 '혜택수혜금액_R3M',
 '이용금액_간편결제_B0M',
 '이용금액_페이_온라인_R3M',
 '잔액_신판ca최대한도소진율_r3m',
 '쇼핑_편의점_이용금액',
 '잔액_일시불_B2M',
 '잔액_일시불_B1M',
 '_1순위쇼핑업종_이용금액',
 '이용개월수_결제일_R3M',
 '잔액_신판ca평균한도소진율_r3m',
 '이용금액_페이_온라인_R6M',
 '잔액_신판ca평균한도소진율_r6m',
 '컨택건수_이용유도_TM_R6M',
 'CA한도금액',
 '연체입금원금_B0M',
 '할부금액_6M_R12M',
 '이용금액_온라인_R6M',
 '카드이용한도금액',
 '잔액_신판최대한도소진율_r6m',
 '이용금액_간편결제_R3M',
 '이용금액_할부_무이자_R12M',
 '_3순위교통업종_이용금액',
 '카드이용한도금액_B1M',
 '카드이용한도금액_B2M',
 '이용건수_할부_R12M',
 '할부금액_3M_R12M',
 '이용개월수_할부_R6M',
 '_1순위납부업종_이용금액',
 '최종이용일자_CA',
 '잔액_신판최대한도소진율_r3m',
 '이용가능여부_해외겸용_본인',
 '이용금액_간편결제_R6M',
 '할부건수_3M_R12M',
 '상환개월수_결제일_R6M',
 '이용건수_할부_무이자_R12M',
 '할부금액_무이자_6M_R12M',
 '잔액_신판평균한도소진율_r3m',
 '교통_택시이용금액',
 '이용개월수_할부_무이자_R6M',
 'RP건수_B0M',
 '이용금액_할부_R6M',
 '입회일자_신용',
 '입회경과개월수_신용',
 '잔액_신판평균한도소진율_r6m',
 '이용개월수_할부_R3M',
 '이용금액_R3M_신용체크',
 '_1순위카드이용금액',
 '이용금액_R3M_신용',
 '이용카드수_신용체크',
 'Life_Stage',
 '이용개월수_신용_R12M',
 '이용개월수_신판_R12M',
 '이용개월수_일시불_R12M',
 '이용금액_일시불_R6M',
 '이용금액_일시불_B0M',
 '이용금액_일시불_R3M',
 '이용금액_일시불_R12M',
 '이용개월수_신용_R6M',
 '이용건수_신용_R6M',
 '이용건수_신용_B0M',
 '이용건수_신판_R6M',
 '이용건수_신용_R3M',
 '이용건수_신판_B0M',
 '이용건수_일시불_R6M',
 '이용건수_신판_R3M',
 '이용건수_일시불_B0M',
 '이용개월수_신판_R6M',
 '이용건수_일시불_R3M',
 '이용개월수_일시불_R6M',
 '이용후경과월_신판',
 '이용건수_신용_R12M',
 '이용건수_신판_R12M',
 '이용건수_일시불_R12M',
 '이용가맹점수',
 '이용후경과월_신용',
 '이용금액_오프라인_B0M',
 '이용금액_오프라인_R3M',
 '이용건수_오프라인_B0M',
 '_3순위업종_이용금액',
 '_3순위쇼핑업종_이용금액',
 '_2순위업종_이용금액',
 '이용개월수_오프라인_R6M',
 '이용금액_오프라인_R6M',
 '_2순위쇼핑업종_이용금액',
 '정상청구원금_B5M',
 '정상청구원금_B2M',
 '연속유실적개월수_기본_24M_카드',
 '정상청구원금_B0M',
 '정상입금원금_B0M',
 '정상입금원금_B5M',
 '정상입금원금_B2M',
 '이용개월수_전체_R6M',
 '이용개월수_전체_R3M',
 '청구금액_R6M',
 '청구금액_R3M',
 '청구금액_B0',
 '청구서발송여부_B0',
 '할인건수_R3M',
 '할인건수_B0M',
 '방문횟수_앱_R6M',
 '방문횟수_PC_R6M',
 '방문일수_PC_R6M',
 '인입횟수_ARS_R6M',
 '이용메뉴건수_ARS_R6M']

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

### Target

In [ ]:
tg_df = pd.read_csv('/content/drive/MyDrive/Segment.csv')
tg_df = tg_df['Segment']
tg_df

0          D
1          E
2          C
3          D
4          E
          ..
2399995    E
2399996    D
2399997    C
2399998    E
2399999    E
Name: Segment, Length: 2400000, dtype: object

In [ ]:
test_cols =['ID','기준년월',
 '연체입금원금_B5M',
 '연체입금원금_B2M',
 '이용건수_오프라인_R3M',
 '이용개월수_신용_R3M',
 '이용카드수_신용',
 '_1순위카드이용건수',
 '이용건수_오프라인_R6M',
 '청구서발송여부_R3M',
 '최대이용금액_일시불_R12M',
 '이용개월수_신판_R3M',
 '이용개월수_일시불_R3M',
 '쇼핑_도소매_이용금액',
 '_1순위교통업종_이용금액',
 '최종이용일자_할부',
 '이용후경과월_일시불',
 '연속무실적개월수_기본_24M_카드',
 '이용개월수_온라인_R6M',
 '이용가능카드수_신용체크',
 '쇼핑_슈퍼마켓_이용금액',
 '_1순위업종_이용금액',
 '이용개월수_간편결제_R6M',
 '이용개월수_페이_온라인_R6M',
 '유효카드수_신용체크',
 '평잔_일시불_6M',
 '이용여부_3M_해외겸용_본인',
 '쇼핑_마트_이용금액',
 '이용가능카드수_신용',
 '교통_주유이용금액',
 '이용건수_간편결제_R3M',
 '이용건수_간편결제_B0M',
 '이용건수_간편결제_R6M',
 '평잔_일시불_3M',
 '월중평잔_일시불',
 '월중평잔_일시불_B0M',
 '_2순위카드이용건수',
 '청구서발송여부_R6M',
 '이용후경과월_할부',
 '_2순위교통업종_이용금액',
 '이용건수_페이_온라인_R6M',
 '이용후경과월_할부_무이자',
 '유효카드수_신용',
 '이용건수_온라인_B0M',
 '_2순위카드이용금액',
 '이용건수_온라인_R3M',
 '이용개월수_할부_R12M',
 '잔액_일시불_B0M',
 '이용건수_페이_온라인_R3M',
 '이용건수_온라인_R6M',
 '최대이용금액_할부_R12M',
 '이용금액_페이_온라인_B0M',
 '소지카드수_이용가능_신용',
 '이용개월수_할부_무이자_R12M',
 '이용건수_페이_온라인_B0M',
 '이용여부_3M_해외겸용_신용_본인',
 '변동률_RVCA평잔',
 '이용금액_온라인_B0M',
 '이용개월수_결제일_R6M',
 '잔액_신판ca최대한도소진율_r6m',
 '최종이용일자_일시불',
 '최대이용금액_할부_무이자_R12M',
 '소지카드수_유효_신용',
 '변동률_RV일시불평잔',
 '혜택수혜금액',
 '이용금액_할부_R12M',
 '최종이용일자_신판',
 '쇼핑_기타_이용금액',
 '최종이용일자_기본',
 '혜택수혜금액_R3M',
 '이용금액_간편결제_B0M',
 '이용금액_페이_온라인_R3M',
 '잔액_신판ca최대한도소진율_r3m',
 '쇼핑_편의점_이용금액',
 '잔액_일시불_B2M',
 '잔액_일시불_B1M',
 '_1순위쇼핑업종_이용금액',
 '이용개월수_결제일_R3M',
 '잔액_신판ca평균한도소진율_r3m',
 '이용금액_페이_온라인_R6M',
 '잔액_신판ca평균한도소진율_r6m',
 '컨택건수_이용유도_TM_R6M',
 'CA한도금액',
 '연체입금원금_B0M',
 '할부금액_6M_R12M',
 '이용금액_온라인_R6M',
 '카드이용한도금액',
 '잔액_신판최대한도소진율_r6m',
 '이용금액_간편결제_R3M',
 '이용금액_할부_무이자_R12M',
 '_3순위교통업종_이용금액',
 '카드이용한도금액_B1M',
 '카드이용한도금액_B2M',
 '이용건수_할부_R12M',
 '할부금액_3M_R12M',
 '이용개월수_할부_R6M',
 '_1순위납부업종_이용금액',
 '최종이용일자_CA',
 '잔액_신판최대한도소진율_r3m',
 '이용가능여부_해외겸용_본인',
 '이용금액_간편결제_R6M',
 '할부건수_3M_R12M',
 '상환개월수_결제일_R6M',
 '이용건수_할부_무이자_R12M',
 '할부금액_무이자_6M_R12M',
 '잔액_신판평균한도소진율_r3m',
 '교통_택시이용금액',
 '이용개월수_할부_무이자_R6M',
 'RP건수_B0M',
 '이용금액_할부_R6M',
 '입회일자_신용',
 '입회경과개월수_신용',
 '잔액_신판평균한도소진율_r6m',
 '이용개월수_할부_R3M',
 '이용금액_R3M_신용체크',
 '_1순위카드이용금액',
 '이용금액_R3M_신용',
 '이용카드수_신용체크',
 'Life_Stage',
 '이용개월수_신용_R12M',
 '이용개월수_신판_R12M',
 '이용개월수_일시불_R12M',
 '이용금액_일시불_R6M',
 '이용금액_일시불_B0M',
 '이용금액_일시불_R3M',
 '이용금액_일시불_R12M',
 '이용개월수_신용_R6M',
 '이용건수_신용_R6M',
 '이용건수_신용_B0M',
 '이용건수_신판_R6M',
 '이용건수_신용_R3M',
 '이용건수_신판_B0M',
 '이용건수_일시불_R6M',
 '이용건수_신판_R3M',
 '이용건수_일시불_B0M',
 '이용개월수_신판_R6M',
 '이용건수_일시불_R3M',
 '이용개월수_일시불_R6M',
 '이용후경과월_신판',
 '이용건수_신용_R12M',
 '이용건수_신판_R12M',
 '이용건수_일시불_R12M',
 '이용가맹점수',
 '이용후경과월_신용',
 '이용금액_오프라인_B0M',
 '이용금액_오프라인_R3M',
 '이용건수_오프라인_B0M',
 '_3순위업종_이용금액',
 '_3순위쇼핑업종_이용금액',
 '_2순위업종_이용금액',
 '이용개월수_오프라인_R6M',
 '이용금액_오프라인_R6M',
 '_2순위쇼핑업종_이용금액',
 '정상청구원금_B5M',
 '정상청구원금_B2M',
 '연속유실적개월수_기본_24M_카드',
 '정상청구원금_B0M',
 '정상입금원금_B0M',
 '정상입금원금_B5M',
 '정상입금원금_B2M',
 '이용개월수_전체_R6M',
 '이용개월수_전체_R3M',
 '청구금액_R6M',
 '청구금액_R3M',
 '청구금액_B0',
 '청구서발송여부_B0',
 '할인건수_R3M',
 '할인건수_B0M',
 '방문횟수_앱_R6M',
 '방문횟수_PC_R6M',
 '방문일수_PC_R6M',
 '인입횟수_ARS_R6M',
 '이용메뉴건수_ARS_R6M']

In [ ]:
# 예측할 데이터를 읽어온다.
df1 = pd.read_parquet('/content/drive/MyDrive/abcde/ab_cde_test.parquet')
df1 = df1[test_cols]
df1

,ID,기준년월,연체입금원금_B5M,연체입금원금_B2M,이용건수_오프라인_R3M,이용개월수_신용_R3M,이용카드수_신용,_1순위카드이용건수,이용건수_오프라인_R6M,청구서발송여부_R3M,...,청구금액_R3M,청구금액_B0,청구서발송여부_B0,할인건수_R3M,할인건수_B0M,방문횟수_앱_R6M,방문횟수_PC_R6M,방문일수_PC_R6M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M
0,TEST_00000,201807,2414,840,48,3,2,51,53,1,...,11441,4931,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
1,TEST_00001,201807,2959,763,14,3,1,40,19,1,...,20522,10152,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
2,TEST_00002,201807,0,0,151,3,2,154,262,1,...,50508,13223,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
3,TEST_00003,201807,0,196,27,3,1,105,44,1,...,4604,2112,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
4,TEST_00004,201807,0,0,31,3,2,52,55,1,...,6788,4406,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,TEST_99995,201812,0,0,0,0,0,-2,0,0,...,0,0,0,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
599996,TEST_99996,201812,689,0,13,3,1,4,19,1,...,1256,359,1,1회 이상,1회 이상,10회 이상,1회 이상,1회 이상,1회 이상,1회 이상
599997,TEST_99997,201812,0,186,0,0,0,6,0,0,...,0,0,0,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
599998,TEST_99998,201812,12448,9018,197,3,4,185,396,1,...,48141,21273,1,1회 이상,1회 이상,40회 이상,1회 이상,1회 이상,1회 이상,1회 이상
599999,TEST_99999,201812,8,0,4,3,2,0,6,1,...,56,18,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상

In [ ]:
notE = pd.read_csv('/content/drive/MyDrive/은서님 파일/model3_notE(2).csv')
notE

               ID Segment
0      TEST_00010   Not_E
1      TEST_00016   Not_E
2      TEST_00032   Not_E
3      TEST_00034   Not_E
4      TEST_00037   Not_E
...           ...     ...
16698  TEST_99947   Not_E
16699  TEST_99957   Not_E
16700  TEST_99961   Not_E
16701  TEST_99982   Not_E
16702  TEST_99998   Not_E

[16703 rows x 2 columns]

In [ ]:
# 1. 'Not_E'인 ID만 필터링
filtered_ids1 = notE[notE['Segment'] == 'Not_E']['ID']

# 2. df2에서 해당 ID만 골라오기
df2 = df1[df1['ID'].isin(filtered_ids1)]

In [ ]:
df2

,ID,기준년월,연체입금원금_B5M,연체입금원금_B2M,이용건수_오프라인_R3M,이용개월수_신용_R3M,이용카드수_신용,_1순위카드이용건수,이용건수_오프라인_R6M,청구서발송여부_R3M,...,청구금액_R3M,청구금액_B0,청구서발송여부_B0,할인건수_R3M,할인건수_B0M,방문횟수_앱_R6M,방문횟수_PC_R6M,방문일수_PC_R6M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M
10,TEST_00010,201807,1304,1150,0,2,1,9,0,1,...,6847,0,0,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
16,TEST_00016,201807,8191,5958,154,3,2,120,260,1,...,41328,12194,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
32,TEST_00032,201807,306,0,6,3,1,11,16,1,...,4259,769,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
34,TEST_00034,201807,601,0,85,3,1,110,132,1,...,56962,15282,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
37,TEST_00037,201807,13221,11589,114,3,3,85,203,1,...,26337,12512,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,10회 이상,10회 이상
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599947,TEST_99947,201812,1874,1463,131,3,3,122,249,1,...,38929,10998,1,30회 이상,10회 이상,60회 이상,1회 이상,1회 이상,1회 이상,1회 이상
599957,TEST_99957,201812,3411,2557,84,3,3,115,183,1,...,28638,14349,1,1회 이상,1회 이상,40회 이상,40회 이상,30회 이상,1회 이상,1회 이상
599961,TEST_99961,201812,5812,3274,90,3,1,57,198,1,...,26095,7195,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,10회 이상
599982,TEST_99982,201812,6871,2643,119,3,1,101,236,1,...,65023,11710,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
599998,TEST_99998,201812,12448,9018,197,3,4,185,396,1,...,48141,21273,1,1회 이상,1회 이상,40회 이상,1회 이상,1회 이상,1회 이상,1회 이상

In [ ]:
notAB = pd.read_csv('/content/drive/MyDrive/은서님 파일/model3_notAB(2).csv')
notAB

               ID Segment
0      TEST_00010   notAB
1      TEST_00016   notAB
2      TEST_00032   notAB
3      TEST_00034   notAB
4      TEST_00037   notAB
...           ...     ...
16683  TEST_99947   notAB
16684  TEST_99957   notAB
16685  TEST_99961   notAB
16686  TEST_99982   notAB
16687  TEST_99998   notAB

[16688 rows x 2 columns]

In [ ]:
# 1. 'Not_E'인 ID만 필터링
filtered_ids2 = notAB[notAB['Segment'] == 'notAB']['ID']

# 2. df2에서 해당 ID만 골라오기
Xtest_df = df2[df2['ID'].isin(filtered_ids2)]

In [ ]:
Xtest_df

,ID,기준년월,연체입금원금_B5M,연체입금원금_B2M,이용건수_오프라인_R3M,이용개월수_신용_R3M,이용카드수_신용,_1순위카드이용건수,이용건수_오프라인_R6M,청구서발송여부_R3M,...,청구금액_R3M,청구금액_B0,청구서발송여부_B0,할인건수_R3M,할인건수_B0M,방문횟수_앱_R6M,방문횟수_PC_R6M,방문일수_PC_R6M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M
10,TEST_00010,201807,1304,1150,0,2,1,9,0,1,...,6847,0,0,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
16,TEST_00016,201807,8191,5958,154,3,2,120,260,1,...,41328,12194,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
32,TEST_00032,201807,306,0,6,3,1,11,16,1,...,4259,769,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
34,TEST_00034,201807,601,0,85,3,1,110,132,1,...,56962,15282,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
37,TEST_00037,201807,13221,11589,114,3,3,85,203,1,...,26337,12512,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,10회 이상,10회 이상
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599947,TEST_99947,201812,1874,1463,131,3,3,122,249,1,...,38929,10998,1,30회 이상,10회 이상,60회 이상,1회 이상,1회 이상,1회 이상,1회 이상
599957,TEST_99957,201812,3411,2557,84,3,3,115,183,1,...,28638,14349,1,1회 이상,1회 이상,40회 이상,40회 이상,30회 이상,1회 이상,1회 이상
599961,TEST_99961,201812,5812,3274,90,3,1,57,198,1,...,26095,7195,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,10회 이상
599982,TEST_99982,201812,6871,2643,119,3,1,101,236,1,...,65023,11710,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
599998,TEST_99998,201812,12448,9018,197,3,4,185,396,1,...,48141,21273,1,1회 이상,1회 이상,40회 이상,1회 이상,1회 이상,1회 이상,1회 이상

In [ ]:
X_test = Xtest_df.drop(columns=['기준년월','ID'])
X_test = X_test[scaler_columns]

In [ ]:
X_test

,연체입금원금_B5M,연체입금원금_B2M,이용건수_오프라인_R3M,이용개월수_신용_R3M,이용카드수_신용,_1순위카드이용건수,이용건수_오프라인_R6M,청구서발송여부_R3M,최대이용금액_일시불_R12M,이용개월수_신판_R3M,...,청구금액_R3M,청구금액_B0,청구서발송여부_B0,할인건수_R3M,할인건수_B0M,방문횟수_앱_R6M,방문횟수_PC_R6M,방문일수_PC_R6M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M
10,1304,1150,0,2,1,9,0,1,11332,2,...,6847,0,0,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
16,8191,5958,154,3,2,120,260,1,44108,3,...,41328,12194,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
32,306,0,6,3,1,11,16,1,8307,3,...,4259,769,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
34,601,0,85,3,1,110,132,1,29384,3,...,56962,15282,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
37,13221,11589,114,3,3,85,203,1,38447,3,...,26337,12512,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,10회 이상,10회 이상
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599947,1874,1463,131,3,3,122,249,1,20281,3,...,38929,10998,1,30회 이상,10회 이상,60회 이상,1회 이상,1회 이상,1회 이상,1회 이상
599957,3411,2557,84,3,3,115,183,1,14203,3,...,28638,14349,1,1회 이상,1회 이상,40회 이상,40회 이상,30회 이상,1회 이상,1회 이상
599961,5812,3274,90,3,1,57,198,1,18616,3,...,26095,7195,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,10회 이상
599982,6871,2643,119,3,1,101,236,1,130090,3,...,65023,11710,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
599998,12448,9018,197,3,4,185,396,1,64459,3,...,48141,21273,1,1회 이상,1회 이상,40회 이상,1회 이상,1회 이상,1회 이상,1회 이상

In [ ]:
X_test['할인건수_R3M'] = Encoder1.transform(X_test['할인건수_R3M'])
X_test['할인건수_B0M'] = Encoder2.transform(X_test['할인건수_B0M'])
X_test['방문횟수_앱_R6M'] = Encoder3.transform(X_test['방문횟수_앱_R6M'])
X_test['방문횟수_PC_R6M'] = Encoder4.transform(X_test['방문횟수_PC_R6M'])
X_test['인입횟수_ARS_R6M'] = Encoder5.transform(X_test['인입횟수_ARS_R6M'])
X_test['Life_Stage'] = Encoder6.transform(X_test['Life_Stage'])
X_test['이용메뉴건수_ARS_R6M'] = Encoder7.transform(X_test['이용메뉴건수_ARS_R6M'])
X_test['방문일수_PC_R6M'] = Encoder8.transform(X_test['방문일수_PC_R6M'])

In [ ]:
# 데이터 표준화
scaled_data = scalerX.transform(X_test)
scaled_data

array([[-0.31734976, -0.29120081, -0.91240972, ...,  0.07669481,
         0.22070759,  0.09921615],
       [ 1.48102546,  0.99642144,  1.56638218, ...,  0.07669481,
         0.22070759,  0.09921615],
       [-0.57795357, -0.59918034, -0.81583342, ...,  0.07669481,
         0.22070759,  0.09921615],
       ...,
       [ 0.85980655,  0.277624  ,  0.5362349 , ...,  0.07669481,
         0.22070759, -3.58425652],
       [ 1.13633906,  0.10863697,  1.00302039, ...,  0.07669481,
         0.22070759,  0.09921615],
       [ 2.59263913,  1.8159148 ,  2.25851239, ...,  0.07669481,
         0.22070759,  0.09921615]])

In [ ]:
# 입력데이터를 test_X 변수에 담아준다.
X_text2 = scaled_data

In [ ]:
# 예측한다.
y_pred = best_model.predict(X_text2)
y_pred_labels = le.inverse_transform(y_pred)
y_pred_labels

array(['D', 'D', 'D', ..., 'D', 'C', 'C'], dtype=object)

In [ ]:
# 결과를 붙힌다음 저장한다.
# 예측할 데이터를 다시 불러온다.
result_df = Xtest_df
result_df['Segment'] = y_pred_labels

In [ ]:
result_df2 = result_df[['ID', 'Segment']]

In [ ]:
result_df2['Segment'].value_counts()

Segment
D    72745
C    27383
Name: count, dtype: int64

In [ ]:
most_common_by_id = result_df2.groupby('ID')['Segment'] \
    .agg(lambda x: x.mode().iloc[0]) \
    .reset_index()

# 컬럼명 확인
most_common_by_id.columns = ['ID', 'Segment']

In [ ]:
most_common_by_id

               ID Segment
0      TEST_00010       D
1      TEST_00016       D
2      TEST_00032       C
3      TEST_00034       D
4      TEST_00037       C
...           ...     ...
16683  TEST_99947       D
16684  TEST_99957       D
16685  TEST_99961       C
16686  TEST_99982       C
16687  TEST_99998       C

[16688 rows x 2 columns]

In [ ]:
most_common_by_id['Segment'].value_counts()

Segment
D    11927
C     4761
Name: count, dtype: int64

In [ ]:
most_common_by_id.to_csv('/content/drive/MyDrive/은서님 파일/model8968_C,D_NotE.csv', index=False, encoding='utf-8-sig')
print('저장완료')

저장완료